---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      organizationID: 75e686e6-28b0-452a-a55d-b4ae00641718
      projectID: f657941e-befa-4e87-a975-b4ae006cada3
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
      auth:
        secretRef:
          credentials:
            name: bitwarden-secretsmanager
            key: token
            namespace: external-secrets
