apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-secretsmanager
stringData:
  #ENC[AES256_GCM,data:U8FcwPx688jfGg9FJbv0I0iBJXdQ3Epn1ejJe01iERHtTpnLzgswfjh9MugJd+AN046b9ikZK1QBwHwRuw==,iv:LCXCT3RXeYK6bJD9eJXIzGpiLWkFPl6XqDK8q0LXDRU=,tag:BgLQFP+nsF8ga9G9LbVPJw==,type:comment]
  #ENC[AES256_GCM,data:KEgymlMtXYifc/XugT4yBnHsUJvr5L4oNJcWUtEpchULAyggwjleCzOcn/Y1WP+/REEkfqQEorkx4ti623FB+bbc1qa0I3Lr2Pyd/5faV+jt,iv:FxxhIOg+GtlhpQN+8ey3qLaSEwz1huIQbmtxoTXOH/s=,tag:uKGR5NjoCssCCESKrHkvwQ==,type:comment]
  token: ENC[AES256_GCM,data:nTmQ2KcXmeJdHQDrKe76ahFS4Q78sXTpzROd6z3QqEOvUabpa85ljJdD38+IxovK2CqWRER8KsgLi1AY6HFLNt7VUl6UA6PpfhOnmU/Oz9a7KwPLHdae3qtdc/1GFA==,iv:oTm7qInSPjZU0TvI8Ta+mDLr1ghvA0mFs9LWgj35aEE=,tag:fZjHB4RuxNhE32WjtxMV7w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNmZWN01jdTVudmd0Szdl
        QjA4SkoxVVFXNmtMeHhEU2h3NmhFeEdiZzJnCjFBSlZtV1RjM3c2NFprNkxaeERH
        TlRHNTNrMnhPOFJxYkVISGJlYjNWR0EKLS0tIEpJTXREcDhQb2dKYzJ1ZkNGbTJN
        NU1IRXBDRHJpL3VXRlhVY3JvaklqLzAK8Cd4xDpx2w2RqXs1dJhzRIJ6bx25w4mZ
        2NeI+Ju/vJyU4M5kQgiJfgwpScy/7BuAydJpt4/pU4PTVw1lrBjmrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T07:09:26Z"
  mac: ENC[AES256_GCM,data:dOzZ6yaXsH4xHp2ZsiEGkYqy6ABiFzRzraQllEDTEYMmme+gURsslouXdKDcWBu5UvzZQa2aasoCdZMsUCOpGwmHnqjes94pXwdDR/fqwvCbdYdDlwRQje2z3DAYnpTW9L78hVrIuAJsN8sREz74BsYZgm7R4Afj9XKzic5g0Z8=,iv:Xcv17WwcvJVzSLoyjogiW52wFTtbcI5YPmGEoBBDcNU=,tag:SXu7bMxQKDfpxOrvALZAQw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
