apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-iot",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp87s0",
          "mode": "bridge",
          "capabilities": { "ips": true, "mac": true },
          "ipam": {
            "type": "static",
            "addresses": [
              {
                "address": "10.0.101.10/24",
                "gateway": "10.0.101.1"
              }
            ],
            "routes": [
              { "dst": "10.0.0.0/16", "gw": "10.0.101.1" }
            ]
          }
        },
        {
          "type": "tuning"
        }
      ]
    }
