---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cilium
  namespace: &namespace kube-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/kube-system/cilium/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cilium-gateway
  namespace: &namespace kube-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager-issuers
      namespace: cert-manager
    - name: akeyless-stores
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/kube-system/cilium/gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 15m
  wait: true
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
# ---
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: GitRepository
# metadata:
#   name: gateway-api-crds
# spec:
#   interval: 30m
#   url: https://github.com/kubernetes-sigs/gateway-api.git
#   ref:
#     tag: v1.3.0
#   ignore: |
#     # exclude
#     /*
#     # include
#     !config/crd/experimental/gateway*.yaml
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: gateway-api-crds
#   namespace: &namespace kube-system
# spec:
#   targetNamespace: *namespace
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   interval: 1h
#   retryInterval: 2m
#   timeout: 5m
#   healthChecks:
#     - &crds
#       apiVersion: apiextensions.k8s.io/v1
#       kind: CustomResourceDefinition
#       name: backendtlspolicies.gateway.networking.k8s.io
#     - <<: *crds
#       name: gatewayclasses.gateway.networking.k8s.io
#     - <<: *crds
#       name: gateways.gateway.networking.k8s.io
#     - <<: *crds
#       name: httproutes.gateway.networking.k8s.io
#     - <<: *crds
#       name: tlsroutes.gateway.networking.k8s.io

