apiVersion: v1
kind: Secret
metadata:
    name: lubelog-secret
stringData:
    #ENC[AES256_GCM,data:bJAifDg=,iv:J3EZvkfM062AgCqBJEggt5kBxHKmoAx0CblnD+EPxaU=,tag:CdnH7ojHxw5ls8vFF5hOIA==,type:comment]
    OpenIDConfig__Name: ENC[AES256_GCM,data:K2HesVLymSI=,iv:sNQCgiGOHMJJSgSea9E5sTfWLjf+rrqfE/jN9pNW5Ew=,tag:YDINaclXU5XO/ouHukK9aw==,type:str]
    OpenIDConfig__ClientId: ENC[AES256_GCM,data:+mvlVhQW8A==,iv:mOgalplPFjAl9R6qqp+N8q5oePE9Pv7SwUdQJC5efVw=,tag:T13n4BERAFM+MjZFsQHz+w==,type:str]
    OpenIDConfig__ClientSecret: ENC[AES256_GCM,data:S7KtbKgjJMrHlMla6VOq+kh4AcZcr2jbQl7IerGPqjEgVZFVSZ1Awc+JK9dgWcgMOXJS4tdR14KLx7GYo21nsK/+voF10tvB,iv:0uTzXj4Uxpq/NY7IH5w0dCYOXQ9/lCquhh/RcVjFhv4=,tag:6Dsc5aSANmRuqsSDr98cew==,type:str]
    OpenIDConfig__AuthURL: ENC[AES256_GCM,data:8Msv0T8cJXw1cqpdDKF8r0zMHz9GapbZt8dQrGTSvpoMpII7aFqrK/rM5wdVMq04RN4gAQ==,iv:ejUUpzcEJGRI+iICAt1kRXlWa8YLicEUTiyMI9Bx2qM=,tag:F03w1F5ORgudn8m/RByymg==,type:str]
    OpenIDConfig__TokenURL: ENC[AES256_GCM,data:wCR3mpf80k6xaUc0RZ0/nmYFuFfgMMlVOPwcJpHB9Taq6k6F0bVK7xCtLx8=,iv:m06u1/NMXOR7zNGS56gRQfhuCamkUtwNh015SUD5azg=,tag:+kQhg+tvGMi0EZrru7cirQ==,type:str]
    OpenIDConfig__RedirectURL: ENC[AES256_GCM,data:xnzDVDFzMCyu+6a4wSokOPjsbwmhVZB8xn+TcEnP4n8JNNHG9vhB8LInz5X4hkRUBg==,iv:rrdpz217Hm8+ouCqptXgg0qO4dnYGW4KisTJqAwP3FA=,tag:VF4khZf3XCqZ5jfyUPbm3g==,type:str]
    OpenIDConfig__LogOutURL: ENC[AES256_GCM,data:cZ3fOYVBmZmA6r55ZcJZS7aHYUPU9LJSOQ9mcSL/wBmK4q44,iv:kmGCE/rv4gGwkK8IJFgURcQLH+dNH06SmTB/PR5dRZg=,tag:ex26ZSxZNkof93QXOOgfng==,type:str]
    OpenIDConfig__Scope: ENC[AES256_GCM,data:0HPoFVTMeKOkwFOZ4nGeuYSQYyw=,iv:pR4/+qbj1rf/e8m60ICXHkN4i+QGSJMSxMGS3HGx6go=,tag:EVYq4IwUHmd7qaVfzsGrzA==,type:str]
    OpenIDConfig__UsePKCE: ENC[AES256_GCM,data:Ojud1A==,iv:h3sUpky3VtQZzQ9+HtRZvrpv95muYTwYHUoa0q0bhlI=,tag:UWYVPKvGlN0fy6URNkgdlQ==,type:str]
    OpenIDConfig__DisableRegularLogin: ENC[AES256_GCM,data:Rh10Tg==,iv:TLeBIu7NxZ8qLMUFHyw0yQpOVRmKLebwbiOs5hRkPDk=,tag:nGuzLDtw6Ko933ez8vke/Q==,type:str]
    #ENC[AES256_GCM,data:E/R+JdfMkrSwWi8La2g=,iv:FJwScLUNRvPQutoR0ga7IU/Mq2cM6HHmOdmFyTf+8Ww=,tag:0xpRKrejta9v9O4xizIopQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Fnm77AKFVA==,iv:/SDOKyMnjqZsn9plSpSRNFrelQDnvj/DwpL6snZk02k=,tag:PEZ1CAeg6QMxdbAvnbkVfw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:y5W+Ax+nqVwDFmnOuyoFbSvh4LjE,iv:nhWB4lsQwdqlRtSgnEod/JIDgo2i6FfdnyFAEFX2nlc=,tag:rS303kGxPqJCL3wGNzml2w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:x3FsKc93Dw==,iv:YRY0T9/by12kmaPpDkqlql/n4IhF8QfThRKxY54DvLg=,tag:7rs1E879qXTNtJ3PhgpFHw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:KPwUnkSuBwtB2Ov+Fg3iwseKmi+GO2ZsMAShe5RsEZqqVH6wtgQk8skbZzrZeRuR2v7Ptm4p6H4RpOoU,iv:uYE5h8OHiNkRFEwd6j9A34vUSvWX2Ei0amZsiOHcRds=,tag:mT4kXDT/w1mLDMsY9/wM4A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:VnhamNAtUUaR/5jXSsQFYzB3V07/hTvcazs0,iv:6XCSrtP8cX5AZc0jaekViGJghrvfGC961Yr5XOuD3sU=,tag:CI39BQ5Z9sXWumonxR8KMQ==,type:str]
    #ENC[AES256_GCM,data:d4SMr/esLcCl,iv:3d8A/pWhX+oyA0zYwCoLOzv9L/ulVh25nDWl9l57UnU=,tag:eLuZHpVl2cEtszJSvc/tOg==,type:comment]
    POSTGRES_CONNECTION: ENC[AES256_GCM,data:spNfjFxC1wxSav/kKYE/nj5iZjQpXtTTyIwOdLMJ6WjdGpx2JR5T3BeplIHYnM6px5cv9grVYGISLCerXMfBSCxCRPXpwpWQtq57h7TD/QAVT0Gb1LNwHg2loCyGJTLe1mNZK4xwkO/cNI5Y5XoUIMT0RKwFu0a4ZjU5kraGquVmlI2Q34zk8QLD5x5h/sQznUmi/OvH,iv:gSHTO4Rf5MmSM0vqu6KWz52L9U537Z+V5bGJNt9ZMe4=,tag:R03lrOe4iOeoZH1lOWpjyw==,type:str]
    #ENC[AES256_GCM,data:HhMRDQvnNbrgJwMhc0U=,iv:pF7dmOqYMmEE5fkbir7DtsEDSo3DYyrsvwzSifZ9f4o=,tag:VEPueUK5SVtFlKeNuMjvRw==,type:comment]
    MailConfig__EmailServer: ENC[AES256_GCM,data:yHy7IHS1q9PsyAVBR1DddDOhlzM3cA==,iv:tWGxW8hS73AZXj+7MWj3QptOduzOxxoGnWKmgdDYudQ=,tag:jxwpL0mTvwOSFKJJeaWVzw==,type:str]
    MailConfig__EmailFrom: ENC[AES256_GCM,data:wOVUyLcG/Yjb1GXImjnZO71//+jKriNFkId3Al4x8nQnww==,iv:BNaUmCpWY0gwCVOBBv7xwvWtytG05/BabjQIE2yqwXU=,tag:T+H56+w32+h4fa6wl58LJg==,type:str]
    MailConfig__Port: ENC[AES256_GCM,data:avBw,iv:XrQKD0u6FjQwmpMIs6g5CtFcVjv74MiLPV3Ki3crxJ4=,tag:40ftN9M4hpSgIb5e+AHt0Q==,type:str]
    MailConfig__Username: ENC[AES256_GCM,data:QDcEJw45YcAzS4LsBCdRXCRLpo3Mayg=,iv:rIdDcDVyPX/8o4UuZbe/bHf/0NDAfApfeV012M6xl5M=,tag:g0tJYluUDdP4o8AU17imQw==,type:str]
    MailConfig__Password: ENC[AES256_GCM,data:qLekXVZJenFraIAhSwWn3L8m1CX7zk4=,iv:5kdNX9bR8Dc92V4+3bJRdFH87qTHqcngOPMUo+ZSiko=,tag:9fANKuRSydL/tPFNxUJDDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUVA0Q2lMVm0zMDQ5bEpv
            OEhQVXZWMzQrblU2M05oNnRvV0Y3aUM3MmhJClJ0MkVTUHozNUVmakdUczE3emZL
            ZEV6aFVQMTdrWVVSQUpKTmNWMjZGQVUKLS0tIHBheDhCSk1NVDQ3R1RMNzRxUlZ6
            Tk14d0lzbmNkeDV4R012RG8xdHV6SGsK3hVHZyh7H/h2Qjyt/0sOqH7i9LXgvvrp
            cOnVuJ1F9w3Dz6Rnn4Ykvvvtt7eX0ZkxiUdouddBPGLn1URppywadQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T22:31:31Z"
    mac: ENC[AES256_GCM,data:Wajcdu+kIrUmZgbDMNaOZnN5ZyEKZ4bCP127oG9egtQwiV773JZlrnB6aIQ9m60yM9EWZ0KKaKffwqJgOwfV5lgwIoA4Ab4T9UWjcd9w4KckI+gnCIzDmBmEU6634lqJ878JtGcGyoLhhRGxrM6PkbOAGQ3QW0KjEAXJ5yjGhsQ=,iv:CJkdbbH+1+9hc+n+dRgaaq2ja40IM31xnSojqxtkU7s=,tag:HzxtlKP39SM2T587Db3qAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
