# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: babybuddy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: babybuddy-secret
    template:
      data:
        SECRET_KEY: "{{ .BABYBUDDY_SECRET_KEY }}"
  data:
    - secretKey: BABYBUDDY_SECRET_KEY
      remoteRef:
        key: babybuddy
        property: BABYBUDDY_SECRET_KEY
