---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./overseerr/ks.yaml
  # - ./immich/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
  # - ./qbittorrent/ks.yaml
