---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
  - ../../components/repos/app-template
resources: []
  # # - ./autom4b/ks.yaml
  # #TODO: find way to implement autom4b into beets using https://github.com/Neurrone/beets-audible
  # # - ./beets/ks.yaml
  # - ./overseerr/ks.yaml
  # - ./plex/ks.yaml
  # - ./tautulli/ks.yaml
  # - ./wizarr/ks.yaml
