apiVersion: v1
kind: Secret
metadata:
    name: emqx-authz-secret
stringData:
    init-user.json: ENC[AES256_GCM,data:3k0BTa7nxJ+AyJYIqSmL2Nn5VK9Hh6KdKsUjq8pIyZmdi2mf5fj/QE4pduOn51LAWuF4KOQE1vg27GpMfoPZbI3W2qPr9bEUGUbR3uXW3MJxriCAINeC9VxP3+/4yp7tF8pF0VSH9VotbhdbNv3oa8xdu1wjxF32GXY5cpkpTjjk49m1Ov3C8BfuF4L2kW0KDrRtaehrh70wzPU6X/SyOXRiMy2k9YKXKNFLFQGxHDXXw02Ndpj33xIUlrmfHGO1Cy4CMDJ1A0Y1FKZxYIDZBjEJ/NOPWznAwGb7XJFsCTTvk0fb68QYKpBlzuasYEEOAkV7NDiaHTlawQ3OVlsTaVgY+o3mpKaDpvPXWVyPy3IJ9EiD792fMzyKXy0KeE7YwCqP3uVCtV5tMza5NKP+FQNTYJAc8MPxiKStA26o4t3eXnQmzRFi9/yCcxwK9OzKsS0CdUWeoJ6hZ9oLhWpa7azc7SNSWp7Cxdtx3KIkq4cDZHtUi2KFt1Dpo53sD2HP1g==,iv:QDnex9jFvNRf2dTCpp0uJgs00SghlfJJJjV6ui6bYkw=,tag:ywvFobsPcSn/f+2aRNE2pw==,type:str]
    acl.conf: ENC[AES256_GCM,data:tU8ZaHg/R+tthTcqlxCWxZ5+aciVU1S08t4SF3TJno/5aZRUaEjTxI4p+UZ1mMabU+V7520hxcyp1UOIUQE2kKhOpKn9eUa+c06ROxRZAYOw0xNY8SclgddUiKy0BCBA2YBGFvd8S1IL/tMQbz+h/S6dCnaDUQVoZDNUjJxNtWMTJ7XVTx86wevmlM12IIPa3yhp6Fk+pzVePRJj8LszgYqbWcke+uMvcip0d5TBFaPNdUzIs3LWZp/X1S10ea40hgu9hJiWV9TXE0ep3yCIPJtAR2Pq9rudYyyughgkyDQ9yjs9Rq+L+AJKC4toC5RNgNG09Oaj9C2g5n6Mu81Depp01JdoYkJRvQPdrKQPiONCUISJpFGwEhiOFNPXbxvwXLp1UqEJC5igy47xOltu4ujeZnxOAMZa1YYv98JeP4YRcc2siiXRAuzeekNeOcr6cQIGiX6jnMm+iUEYyLyWHv0L/VkOZVHky6diMDZ1FfjDffyDaRtJwEu4f96Ju9qWai7r9hYKukoODPv5JR/Q2zwgTt24OOtBv6gE3Js7TaTltPm9igDqKOzbk+3Ltcsn655TtQ8N47jgez7HalDmexAjvfqhL5REPvzyJIRK4X1Nd18Li0u0PIPOvdcO0g2rL8jdgeQ6gI4hMtiXzpqQ9e9R42WZufbO5lQOTBbWsn82c8w33UXYYeh3VKIYY+6HWTXiyDCizSnpWYqPAEgbrSW7CasnHH8mBKrQ0HrOc1QRo9taciogB0Q1kL6qSyd2Wpj59XVh+2eYYm0QrMmYQhpIVduKS31hGSm9fzAcpjUzjav5EC2gJLQfZqkT9sgoqCJhbLU6I5BTox4I2eEtgM6IfBJUscRnW2Id4GtOSo7aeCdILVsyXE1XFLoPBRlbYhEmsgtkmYS8FpakZdnn14SQxaPjetF6GJoJBTJObGkSNVXEDDAqHtFllkVMO/RXAe+91IvKKr0LM1ZVHmMjrcCVjOJ41JsL5FuV9kgTvvsTtQVx6vPgPFIEjIck+kUziFiW3B9teBkg7BaUImb6Po2Gg2H5A3Uv67wbJuv5sY+Qe1l4PPNBzTRzN4oNInCUL+c7hartuX1JvzQ2SQ67uKgoSfnARj2bD1RLcqJxIcc/0oocD5vfb5IhU18u,iv:ILsvkDH2FNGDwhYbi8HhOUKE7GEOmYw5CJ+NLrZEXTk=,tag:qA+/5ZjOQoqfQ1Icwb+oig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaFBxdUk1TzA0Q2hreCtx
            NDJvUDlpeW9xR04xRTFSMXhzRlBtV3ZNd21JCnVYSVRaNUxmTWVyZWhYYkpua0Rq
            QkpVN2JiTWdqUzZkWklCMWJMT3BsbzAKLS0tIHJlVTJQM3hMaEQ2T05wWUxzQ2J1
            MkZPMkkxTmN4ZWd2c2pLdHZCZTc2UWMKo16dhqOOWKeHCGmdqBDrzilFIhBvjRJC
            yCWO4SrpwZqhu2SR2swHbTZdJHpH5cpF3FNBhxJEyLgu6hmaYaMGVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T03:55:04Z"
    mac: ENC[AES256_GCM,data:jyaayl9Ss8FxYZCI6U5pwCfdx6IToKpv4ZOqFR5Wq5HsfAseY3J9Qy00bLns0pAWPjsh+zzcQ7oM4sXqqyZJxnGoyPbGf9y/iPyC45rzEgQ3PJTO0BONrN+C3VbucI5zlo2tPnh4aLUZcROHf9+ekKhC5aMA29jypPfBm61TUr4=,iv:4KOyNo/r2gK3J5pZEZ7yncLdG9GDsCjDe0egpeXEahE=,tag:KEv1A3AncH/wvZpeqv9zZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
