---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: minio-secret
    template:
      engineVersion: v2
      data:
        MINIO_ROOT_USER: "{{ .MINIO_USER }}"
        MINIO_ROOT_PASSWORD: "{{ .MINIO_PASSWORD }}"
  dataFrom:
    - extract:
        key: /minio
