apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:OD2IORI=,iv:4mZOavZeJpQSPd2oY1UIrWeTpqVkzlOgOWOhwbJVEtg=,tag:1s0OOaQIhBhCueV+fjOnmg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:SEAZcCSSWSgZJdoM99cglgC/wpVl/N58mTQud6H07M6wWFu7jmUHddA=,iv:K9C0qE0PlQqAf1pQQ5QatjpRjxettqTr18kys8lbroc=,tag:xJBm5nJTwpk5n19kr0FWiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaFBxdUk1TzA0Q2hreCtx
            NDJvUDlpeW9xR04xRTFSMXhzRlBtV3ZNd21JCnVYSVRaNUxmTWVyZWhYYkpua0Rq
            QkpVN2JiTWdqUzZkWklCMWJMT3BsbzAKLS0tIHJlVTJQM3hMaEQ2T05wWUxzQ2J1
            MkZPMkkxTmN4ZWd2c2pLdHZCZTc2UWMKo16dhqOOWKeHCGmdqBDrzilFIhBvjRJC
            yCWO4SrpwZqhu2SR2swHbTZdJHpH5cpF3FNBhxJEyLgu6hmaYaMGVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T02:18:54Z"
    mac: ENC[AES256_GCM,data:2XE6KCEKLG7CFeMM7HSGNAb6009KrM9aY8j1CiUlROhSPseAsCf1od/khCGbl++in2h6z8GzHIrx9IeM4XKl3A9xUP0e890Zb3OWtIQ3Ojt7vn8414TCNn28Zngek1DKad3X/01N+SQnHovc1Br/QEtLIzZCOZS3KFGysAU86wA=,iv:XGQBAysjaGM9wHMyFYgPNjn1AoAVI4kaTruRT2lDDyY=,tag:RUrijE3e+5De/cOawJjzPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
