---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: pgadmin-auth-secret
    template:
      engineVersion: v2
      data:
        # config_local.py: |-
        #   AUTHENTICATION_SOURCES = ['oauth2', 'internal']
        #   OAUTH2_AUTO_CREATE_USER = True
        #   OAUTH2_CONFIG = [{
        #       'OAUTH2_NAME': 'pocketid',
        #       'OAUTH2_DISPLAY_NAME': 'Pocket ID',
        #       'OAUTH2_CLIENT_ID': "{{ .PGADMIN_CLIENT_ID }}",
        #       'OAUTH2_CLIENT_SECRET': "{{ .PGADMIN_CLIENT_SECRET }}",
        #       'OAUTH2_TOKEN_URL': 'https://id.${SECRET_DOMAIN}/api/oidc/token',
        #       'OAUTH2_AUTHORIZATION_URL': 'https://id.${SECRET_DOMAIN}/authorize',
        #       'OAUTH2_USERINFO_ENDPOINT': 'https://id.${SECRET_DOMAIN}/api/oidc/userinfo',
        #       'OAUTH2_SERVER_METADATA_URL': 'https://id.${SECRET_DOMAIN}/.well-known/openid-configuration',
        #       'OAUTH2_API_BASE_URL': 'https://id.${SECRET_DOMAIN}/',
        #       'OAUTH2_SCOPE': 'openid email profile',
        #       'OAUTH2_BUTTON_COLOR': '#fd4b2d',
        #       'OAUTH2_ICON': 'fa-openid',
        #   }]
        pgpass: |
          postgres-rw.dbms.svc.cluster.local:5432:postgres:postgres:"{{.POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: /pgadmin
    - extract:
        key: /cloudnative-pg
    - extract:
        key: /generic
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: pgadmin-secret
    template:
      engineVersion: v2
      data:
        PGADMIN_DEFAULT_EMAIL: "{{ .PGADMIN_DEFAULT_EMAIL }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .PGADMIN_DEFAULT_PASSWORD }}"
  dataFrom:
    - extract:
        key: /pgadmin
