---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        HOME_ASSISTANT_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        HOME_ASSISTANT_LATITUDE: "{{ .HASS_LATITUDE }}"
  dataFrom:
    - extract:
        key: /home-assistant
