---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: teslamate-secret
    template:
      data:
        ENCRYPTION_KEY: "{{ .TESLAMATE_ENCRYPTION_KEY }}"
        # DATABASE_PASS: "{{ .${APP}_postgres_password }}"
  dataFrom:
    - extract:
        key: teslamate
    - extract:
        key: cnpg-users
