---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app gramps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: gramps-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
        INIT_POSTGRES_DBNAME: gramps
        INIT_POSTGRES_USER: &dbuser "{{ .GRAMPS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbpass "{{ .GRAMPS_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App
        GRAMPSWEB_SECRET_KEY: "{{ .GRAMPS_SECRET_KEY }}"
        GRAMPSWEB_POSTGRES_USER: *dbuser
        GRAMPSWEB_POSTGRES_PASSWORD: *dbpass
        GRAMPSWEB_USER_DB_URI: 'postgresql://{{ .GRAMPS_POSTGRES_USER }}:{{ .GRAMPS_POSTGRES_PASSWORD }}@{{ .POSTGRES_HOST }}:5432/gramps_users'
        GRAMPSWEB_SEARCH_INDEX_DB_URI: 'postgresql://{{ .GRAMPS_POSTGRES_USER }}:{{ .GRAMPS_POSTGRES_PASSWORD }}@{{ .POSTGRES_HOST }}:5432/gramps_search'
        # Smtp
        GRAMPSWEB_EMAIL_HOST: "{{ .SMTP_HOST }}"
        GRAMPSWEB_EMAIL_PORT: "587"
        GRAMPSWEB_EMAIL_HOST_USER: "{{ .SMTP_USERNAME }}"
        GRAMPSWEB_EMAIL_HOST_PASSWORD: "{{ .SMTP_PASSWORD }}"
        GRAMPSWEB_EMAIL_USE_TLS: "true"
        GRAMPSWEB_DEFAULT_FROM_EMAIL: Gramps-Admin <noreply@${SECRET_DOMAIN}>

  dataFrom:
    - extract:
        key: /gramps
    - extract:
        key: /cloudnative-pg
    - extract:
        key: /generic
