---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app gramps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: gramps-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
        INIT_POSTGRES_DBNAME: gramps
        INIT_POSTGRES_USER: "{{ .GRAMPS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .GRAMPS_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Smtp
        GRAMPSWEB_EMAIL_HOST: "{{ .SMTP_HOST }}"
        GRAMPSWEB_EMAIL_PORT: "587"
        GRAMPSWEB_EMAIL_HOST_USER: "{{ .SMTP_USERNAME }}"
        GRAMPSWEB_EMAIL_HOST_PASSWORD: "{{ .SMTP_PASSWORD }}"
        GRAMPSWEB_EMAIL_USE_TLS: "true"

  dataFrom:
    - extract:
        key: /cloudnative-pg
    - extract:
        key: /generic
