apiVersion: v1
kind: Secret
metadata:
    name: gramps-secret
stringData:
    #ENC[AES256_GCM,data:juYw60K2cLka9YuZS/A=,iv:P90bIQsov2URUz04STu2FhIfViu9JC/nq9LtO0prYss=,tag:FRHVkAN++1bMG0rdHOR9OA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Jj7wlZ9n,iv:w8T/uyextCrahUvAzklZ/5KMVGFc/2lXu8369+QkIQo=,tag:Mk12+Iny88puYmGNaXEkRQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:EmxMgodyXKgPNXw8RPZ6m9WmBSzR,iv:hTSKl37mC3vhEBi693v5XgB/j2AnNXW/JKs/sFiZuhM=,tag:wJirsFeHuKwpkgRXLIbm9w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:BtUNQECf,iv:9d3u1Yo0c5KlhVHTP+vcpCWus3R7Rx4b2KqVx3hWGko=,tag:4AaXv49N2iZgSFcrOxZwzA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:mJKrlDBuB9Fi6Fjabo2Rx1jIE+dDnGuH0w==,iv:I9jGMp/dP8B/OC12c7+Y9EiFWvCMVIeNZoAxnDLYvn8=,tag:3Kv8p1NNkolyqO00W7dqwA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:DzK1hJMAdGky5G3musE3iJeDOndUjbVEyYIR,iv:RE3t4/qKhGYJZKArVrGAiVyftfjrshxD5z4NpKwgITQ=,tag:0XvgkJG2BVTJ1BxeajSEbQ==,type:str]
    #ENC[AES256_GCM,data:i8wEDvg=,iv:sJTJMx574ojGZeaDHXDlofeZhttvEqqt35ddJm+h4uw=,tag:j4MWXylYFhaC3mtsSf2MKw==,type:comment]
    GRAMPSWEB_EMAIL_HOST: ENC[AES256_GCM,data:rUC394DegCASmlzfy+ucKZfU1yxZNQ==,iv:lc6l5VbWAD9U+JlQQkhn4ptOMjCDFyThz6Je7pIxfYg=,tag:Eewltza6kRlDCoI0j/qFmw==,type:str]
    GRAMPSWEB_EMAIL_PORT: ENC[AES256_GCM,data:7zPd,iv:79P0fUMY3w0rIn/TfFPg1sFUz7GbzAz9UexJZO0Wi04=,tag:xbr6ZjRJIC5pE2bfAF/+kA==,type:str]
    GRAMPSWEB_EMAIL_HOST_USER: ENC[AES256_GCM,data:4Q20QfsIG6C5PdBX29ZNttQbsJAe0JQ=,iv:5XEKs4uDazFCy5ComZ+yR6sI+b0P8rjrROPhNZnRfvE=,tag:gDZHcZoWHqwikYKp4ouVnQ==,type:str]
    GRAMPSWEB_EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:k2FgtTyeDI+aVjFw1+AXeBptuLgotAk=,iv:Dyu9F58M0vHatVHc91YIfdrO8FWwLPl7Ks+po2Zql98=,tag:42G/oS6YHwL95Quv+iDdmw==,type:str]
    GRAMPSWEB_EMAIL_USE_TLS: ENC[AES256_GCM,data:xunjfw==,iv:tbwHVV+gJTkGu31bJgtJ3TgIcYQtdxjyc1onYkQIpE8=,tag:iqdhuTVou08CRykZWGBi5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T23:06:31Z"
    mac: ENC[AES256_GCM,data:zTa5GuIGwS2WZQOTex6QFiC1RWtWK/zI4UbWgOZMimGthhJ+Mb0+zAdjPDla/EgipSK7hSUntI117wrnx3Mu+7Z30zby8/s1c4BfLe+KKymPH2rvFHL/Vfdaf1yUf+2GD9UQsw1jvHZ2rNs7ZO6ygYZYkK9+NvK6jrvsLdYv7jk=,iv:1reOLD4x504VoIf2xUNV1o9mpeKuSTke9tUMfYGu1Pk=,tag:lt7npDpaBqCoK+5d7VsoBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
