---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app wger
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: wger-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: &host "postgres-rw.dbms.svc.cluster.local"
        INIT_POSTGRES_DBNAME: &db wger
        INIT_POSTGRES_USER: &user "{{ .WGER_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &pass "{{ .WGER_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        # App
        DJANGO_DB_DATABASE: *db
        DJANGO_DB_USER: *user
        DJANGO_DB_PASSWORD: *pass
        DJANGO_DB_HOST: *host
        DJANGO_DB_PORT: "5432"
        DJANGO_PERFORM_MIGRATIONS: "True"
        SECRET_KEY: "{{ .WGER_SECRET_KEY }}"
        SIGNING_KEY: "{{ .WGER_SIGNING_KEY }}"
        DJANGO_ADMINS: admin,admin@${SECRET_DOMAIN}
        # CELERY_FLOWER_PASSWORD: "{{ .WGER_ADMIN_PASS }}"

        # Email
        # https://docs.djangoproject.com/en/4.1/topics/email/#smtp-backend
        ENABLE_EMAIL: "true"
        EMAIL_HOST: "{{ .SMTP_HOST }}"
        EMAIL_PORT: "587"
        EMAIL_HOST_USER: "{{ .SMTP_USERNAME }}"
        EMAIL_HOST_PASSWORD: "{{ .SMTP_PASSWORD }}"
        EMAIL_USE_TLS: "True"
        EMAIL_USE_SSL: "False"
        FROM_EMAIL: 'wger Workout Manager <noreply@${SECRET_DOMAIN}>'

  dataFrom:
    - extract:
        key: /cloudnative-pg
    - extract:
        key: /wger
    - extract:
        key: /generic
