---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wger
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      wger:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17@sha256:894a38169bf4135fb1e85a1112c64fc24a267d1191887cbf6fb8c0a17893770d
            envFrom: &envFrom
              - secretRef:
                  name: wger-secret
        containers:
          app:
            image:
              repository: wger/server
              tag: 2.4-dev@sha256:168f5fe0d480e9909546e61edda859a16f52acef88ac6624e6971f487ce3b99d
            envFrom: *envFrom
            env:
              DJANGO_DB_ENGINE: django.db.backends.postgresql
              TZ: America/Los_Angeles
              SITE_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
              ALLOW_REGISTRATION: True
              ALLOW_GUEST_USERS: False
              WGER_INSTANCE: https://wger.de
              ALLOW_UPLOAD_VIDEOS: True
              MIN_ACCOUNT_AGE_TO_TRUST: "21"
              SYNC_EXERCISES_ON_STARTUP: True
              SYNC_EXERCISES_CELERY: True
              SYNC_EXERCISE_IMAGES_CELERY: True
              SYNC_EXERCISE_VIDEOS_CELERY: True
              USE_CELERY: False
              # CELERY_BROKER: &redis "redis://dragonfly.dbms.svc.cluster.local:6379"
              # CELERY_BACKEND: *redis
              # CELERY_FLOWER_PASSWORD: adminadmin
              DJANGO_CACHE_BACKEND: django_redis.cache.RedisCache
              DJANGO_CACHE_LOCATION: *redis
              DJANGO_CACHE_TIMEOUT: "1296000" # in seconds - 60*60*24*15, 15 Days
              DJANGO_CACHE_CLIENT_CLASS: django_redis.client.DefaultClient
              AXES_ENABLED: True
              AXES_FAILURE_LIMIT: "10"
              AXES_COOLOFF_TIME: "30" # in minutes
              AXES_HANDLER: axes.handlers.cache.AxesCacheHandler
              AXES_LOCKOUT_PARAMETERS: ip_address
              AXES_IPWARE_PROXY_COUNT: "1"
              AXES_IPWARE_META_PRECEDENCE_ORDER: HTTP_X_FORWARDED_FOR,REMOTE_ADDR
              DJANGO_DEBUG: False
              WGER_USE_GUNICORN: True
              EXERCISE_CACHE_TTL: 18000 # in seconds - 5*60*60, 5 hours
              ACCESS_TOKEN_LIFETIME: "10"
              REFRESH_TOKEN_LIFETIME: "24"
            resources:
              requests:
                cpu: 15m
                memory: 80M
              limits:
                memory: 256M
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port "8000"
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      app:
        existingClaim: *app
        globalMounts:
          - path: /home/wger/static
            subPath: static
          - path: /home/wger/media
            subPath: media
