---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: akeyless
spec:
  provider:
    akeyless:
      akeylessGWApiURL: https://api.akeyless.io
      authSecretRef:
        secretRef:
          accessID:
            name: akeyless-secret
            key: accessId
            namespace: external-secrets
          accessType:
            name: akeyless-secret
            key: accessType
            namespace: external-secrets
          accessTypeParam:
            name: akeyless-secret
            key: accessTypeParam
            namespace: external-secrets
