apiVersion: v1
kind: Secret
metadata:
    name: akeyless-secret
stringData:
    accessId: ENC[AES256_GCM,data:SusxL/0w+votVQPF/SwtSQ==,iv:7gh2Xq3iJcVVpGATtZseo6qR0lp3N7abMkk3oa9ixfM=,tag:ZNhaW+QwgY85FbYZSx8/Bw==,type:str]
    accessType: ENC[AES256_GCM,data:PJt58xsZ8JOQFQ==,iv:7HrDu79nUfHYekxZ7+iPA1VhNb5Ad/BMFPyBrbiIwwk=,tag:5EUxhAW4V+LRUcwa/Pb7Lg==,type:str]
    accessTypeParam: ENC[AES256_GCM,data:gbz7rsT/GZp9ph011i2t6I1epF7ih82KvohrNg9OoMMmmG9NHxECwE49cPI=,iv:NExeuTIHtnT+g7WBpM9mp5uhLjn27+iCh9rM4hanveo=,tag:u28jZoG053AGB+NS3zLdeA==,type:str]
sops:
    age:
        - recipient: age1qez67uw84ygk7q39yr3ht5nxzr32c8pf2zxc4znvn8lvtx3kqgmqv5wgu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTXEvWlVsVGpSQ2dmdWYv
            N2Y2YUdTUEEvR2RVTG5yUlI1L0dEcDJBS3gwCkJ1ZXNJRWZET2cxYXF5MUJTV1hH
            bXphZjJMNmhIUnpSQllKV1NtS3BsT3cKLS0tIDlaZWdaOGszaDl1ekh4ZGlkQWIz
            bEFSSTdHWFhMMEJ2OXM4MHhGWXRzSXMK8cLW8Dehs2KFaE+eHWNfuPxuhxULLZJP
            DNi4JrjYxcMNcXWn/Ugh8JPYHW1hnkMwnd7rwvVdjYSneo2s7JdKTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T09:41:05Z"
    mac: ENC[AES256_GCM,data:Ztn2KCULioHcNMVwhnDmuvvUpz4BZknjzSASsFwqZN3lLnjp0ezLNLV9WfG/sPLOW3+3WATlNEBGOVsJsO25UeUobrihY63jKfnvVqM6L8/7D1K8bnCxqoa4SRpKZ49FEFc+u4ND5XoHJh33HGT2f5kJifAhcigsgPrimAFT/2w=,iv:I74oV8Lu/J7nWdpBfA8bgu0Wa/GHf79RqyQhrvn4xIQ=,tag:NiRtAyvoNBjW9EDenQI8mw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
