apiVersion: v1
kind: Secret
metadata:
    name: akeyless-secret
stringData:
    accessId: ENC[AES256_GCM,data:WwXXmSByRkANLcgHwNtg1g==,iv:NZ+VUle7pwgVJO0t2VarkNcoZSIsE9H7B1Pt9BxuFU8=,tag:YMvGS6/roZu4E1BukU0Y1g==,type:str]
    accessType: ENC[AES256_GCM,data:BQqclBfZaNcIFg==,iv:f0IH1R56NUycST9srsH4aNKQG0YMYf5MqrhQDhdjwQY=,tag:vD47XwhAXXZSzuBiHTDjgw==,type:str]
    accessTypeParam: ENC[AES256_GCM,data:izV2uKuOp+apBwaKgiSUzGjSRtn3c8N3FbBacNTSE3ADaG1o+4s7DpHx/tY=,iv:ZzkoY9XOSFww5MSI9emPY+X/nEF82JFFqzxvKFr/j3M=,tag:ZTUhApGXcP17OkKDbUCLow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T18:06:34Z"
    mac: ENC[AES256_GCM,data:/9cvmv0sT+BaJB/9uRSgzp3WwTbMPFEdijTgQgRyyhVNgiZ6MvKLlCBTPIdIlNU6Jr34TGhSnqMWMdZbe60hTUBG5OIAtSxDgdTXDZfOgtyAcBX4ktTCvwPWMtTdniFW4YtarwFedgcpQXPa65ljDxM68cBXzn/sGzj3J7x1ato=,iv:yiHla32vTYGbpMAzT7QuZCEZ7qrRbwXtHc4lpAAc2ks=,tag:1EDf4lTFs8nnh6KaGbJUMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
