apiVersion: v1
kind: Secret
metadata:
    name: akeyless-secret
stringData:
    accessId: ENC[AES256_GCM,data:/Tcd5g12DTmyl5B7z05O5w==,iv:rsNBAon06ggPr86BAqn8QQ76mEqa8hFOCIY7HA2M+HU=,tag:4OZZvAzASPBLc7bqd/KooA==,type:str]
    accessType: ENC[AES256_GCM,data:sI7vEPjrtEwyaw==,iv:MmsTMe53MmGwLdZy3FdIslBA0+yG8yesxe/oHfh/GTU=,tag:u6qBbSfY3jWVCRsorziKkQ==,type:str]
    accessTypeParam: ENC[AES256_GCM,data:KNQmqV8A6JIJ5Jo/kyoXUkTYUEpzH9JXPS6yZ9h0P05vnQyy0IggXApA1t8=,iv:jCqcNvLD0m5xqOEjeXG/hYcxpFwHGHu8iPN70vgdhUw=,tag:vQMHLGd3x+27VqkVBbmzTA==,type:str]
sops:
    age:
        - recipient: age1pj705hhyh9u9dwxsj2ak9l49tv3nqqlfxj4zxsj0wkrpnlywdvzqf7vz08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiblRXQ2hUZ280UDlwekZF
            RUU1YWNCR1RvNktCcWt3QUhSS2FadDhTOGl3CkIxd01rZEpDb0ZObEs0b0U1TDVM
            VHJncTdXTUdOUnFMT0xmZ0p2Z0YyWkEKLS0tIHlrbzVtdUZxUlpTWjBrODZBVyty
            SzRnaUkvcXRPcGdicytpUGM0aEFkemMKG9+SwjfR8nE2KHCmqiacl0RoPp7cVSQw
            ZQNWK3gFx4ErOLb8eB0rcStLMtgR4yPMKIa7K1bdNueU5ysKwapsPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T18:57:40Z"
    mac: ENC[AES256_GCM,data:84VwFvYWCZfqSHyP+tBIA+0buNre3pGDM5T9Pahs1lUEgfdy+Az+Z7UZkW4ffCGKwlFeDhJGt1T1c5r0fQsOIVaZnMaox1EmpwA1HdrGnmil0QBGLd7Pn96f2EwGqij7d2LWEWufN+xad9JsUjNpK87u4WYH8QLu9md0cXluxmM=,iv:rVvpmlNTwHu1mYWVOPuRm+/mDZRhwCahH6NY1oshPtY=,tag:zFXR1b0F/aaPVDmwY1017w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
