# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:bKlNmojBCr+gH/UD3LZUe70WCxsep+1l3w0QUxOuNrAXH79VEwCo/A==,iv:XK44GNYckpUJXcGcv5H0YR2pJ2CfeHZzUUP7lbd0Y1g=,tag:U9RXcvmcKNeWTBsumFaI2Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Q2NaUHJEQk4rRjhaMlV3
        eU5nZ1hMSmY5SkwvVEI5Ukt1ajhPT2xsUEE4CmdxMHlaRUlIdWh6Z1l0WmwvUXg1
        WWRUNGIrMnFUSnEyYlV1ZzdFa3FIdEEKLS0tIExJOTBiZ3hFZk12SHdnazBPUE1K
        OTVwaXkvcVE5MmJSRmI2VTNCMkJsMDgKwKHRA67IfUIJIK6jFuMZMtClhg0pCo6R
        t7O59ct2rTi8SL9onGebCc5yMgWbZ5loKYQxqNrl6nBg7bvuTNVyog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T14:16:58Z"
  mac: ENC[AES256_GCM,data:RF+JezXIKEjNQnzIzA1jxKX2fZBHpNnvehBdOMD+eH16WIdwg9E80mBexTqEjkuod9szBFiobhs9qUE2JmywUgorcwtHu9S0nX63bV8gGJbGAJJcK9vp7F3Y74NTJkKWgABSDDQTzpRhtjV9CvNtTWL4W8n03Z53jdkowZ5u4Ps=,iv:hupQ2rISypf+HUnakkZNelGYt7C0WChApCB961nQWHI=,tag:t30OibqP12snykAfuxpd/Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
