apiVersion: batch/v1
kind: Job
metadata:
  name: cnpg-local-restore
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: restore
          image: postgres:17-alpine
          command:
            - sh
            - -c
            - |
              echo "Scanning for backups in /backups/daily/..."

              # Extract unique DB names from filenames
              for db_name in $(ls /backups/daily/*.sql.gz 2>/dev/null | sed -E 's|.*/(.+)-(latest|[0-9]{8}).*\.sql\.gz|\1|' | sort -u); do
                echo "Processing DB: $db_name"

                # Find the latest backup file for this DB
                latest_backup=$(ls -1 /backups/daily/${db_name}-*.sql.gz 2>/dev/null | sort | tail -n 1)

                if [ -f "$latest_backup" ]; then
                  echo "Found latest backup: $latest_backup"

                  # Create the DB if it doesn't exist
                  echo "CREATE DATABASE $db_name;" | \
                    PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres-rw.dbms.svc.cluster.local -U $POSTGRES_USER -d postgres 2>/dev/null || true

                  # Restore the backup
                  gunzip -c "$latest_backup" | \
                    PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres-rw.dbms.svc.cluster.local -U $POSTGRES_USER -d "$db_name"

                  echo "Restore completed for $db_name"
                else
                  echo "No backup found for $db_name"
                fi
              done

              echo "All restores complete."
          envFrom:
            - secretRef:
                name: postgres-backup-secret
          volumeMounts:
            - name: backup
              mountPath: /backups
      volumes:
        - name: backup
          nfs:
            server: shango.internal
            path: /mnt/user/backup/cnpg-db
