apiVersion: batch/v1
kind: Job
metadata:
  name: cnpg-local-restore
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: restore
          image: postgres:17-alpine
          command:
            - sh
            - -c
            - |
              echo "Scanning for backups in /backups/daily/..."

              TODAY=$(date +%Y%m%d)

              for backup_file in /backups/daily/*-${TODAY}.sql.gz; do
                if [ ! -f "$backup_file" ]; then
                  continue
                fi

                # Extract DB name from filename
                db_name=$(basename "$backup_file" | sed -E "s/-${TODAY}\.sql\.gz$//")

                echo "Processing DB: $db_name"

                # Create DB if it doesn't exist
                echo "CREATE DATABASE $db_name;" | \
                  PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres-rw.dbms.svc.cluster.local -U $POSTGRES_USER -d postgres 2>/dev/null || true

                # Restore DB
                gunzip -c "$backup_file" | \
                  PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres-rw.dbms.svc.cluster.local -U $POSTGRES_USER -d "$db_name"

                echo "Restore completed for $db_name"
              done

              echo "All restores complete."
          envFrom:
            - secretRef:
                name: postgres-backup-secret
          volumeMounts:
            - name: backup
              mountPath: /backups
      volumes:
        - name: backup
          nfs:
            server: shango.internal
            path: /mnt/user/backup/cnpg-db
