apiVersion: batch/v1
kind: Job
metadata:
  name: cnpg-local-restore
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: restore
          image: postgres:17-alpine
          command:
            - sh
            - -c
            - |
              echo "Scanning for backups in /backups/daily/..."

              TODAY=$(date +%Y%m%d)

              for db_name in $(ls /backups/daily/*-$TODAY.sql.gz 2>/dev/null | sed -E "s@.*/(.+)-$TODAY\.sql\.gz@\1@" | sort -u); do
                echo "Processing DB: $db_name"

                backup_file="/backups/daily/${db_name}-${TODAY}.sql.gz"

                if [ -f "$backup_file" ]; then
                  echo "Found today's backup: $backup_file"

                  echo "CREATE DATABASE $db_name;" | \
                    PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres-rw.dbms.svc.cluster.local -U $POSTGRES_USER -d postgres 2>/dev/null || true

                  gunzip -c "$backup_file" | \
                    PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres-rw.dbms.svc.cluster.local -U $POSTGRES_USER -d "$db_name"

                  echo "Restore completed for $db_name"
                else
                  echo "No backup found for $db_name with today's date"
                fi
              done

              echo "All restores complete."
          envFrom:
            - secretRef:
                name: postgres-backup-secret
          volumeMounts:
            - name: backup
              mountPath: /backups
      volumes:
        - name: backup
          nfs:
            server: shango.internal
            path: /mnt/user/backup/cnpg-db
