---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-xtm
spec:
  secretName: k8s-xtm-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames: ["${SECRET_DOMAIN}", "*.${SECRET_DOMAIN}"]
