---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autobrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: autobrr-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: &dbHost postgres-rw.dbms.svc.cluster.local
        INIT_POSTGRES_DBNAME: &dbName autobrr
        INIT_POSTGRES_USER: &dbUser "{{ .AUTOBRR_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .AUTOBRR_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        # App
        AUTOBRR__DATABASE_TYPE: postgres
        AUTOBRR__POSTGRES_DATABASE: *dbName
        AUTOBRR__POSTGRES_HOST: *dbHost
        AUTOBRR__POSTGRES_PORT: "5432"
        AUTOBRR__POSTGRES_USER: *dbUser
        AUTOBRR__POSTGRES_PASS: *dbPass
        AUTOBRR__SESSION_SECRET: "{{ .AUTOBRR_SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: /autobrr
    - extract:
        key: /cloudnative-pg
