http {
    client_body_temp_path /tmp/nginx/client_temp;
    proxy_temp_path /tmp/nginx/proxy_temp;
    fastcgi_temp_path /tmp/nginx/fastcgi_temp;
    scgi_temp_path /tmp/nginx/scgi_temp;
    uwsgi_temp_path /tmp/nginx/uwsgi_temp;

    upstream wger {
        server wger-app.self-hosted.svc.cluster.local:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://wger;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
            proxy_set_header X-Forwarded-Host $host:$server_port;
            proxy_redirect off;
        }

        location /static/ {
            alias /wger/static/;
        }

        location /media/ {
            alias /wger/media/;
        }

        client_max_body_size 100M;
    }
}
