---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app wger
  namespace: &namespace self-hosted
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./kubernetes/apps/self-hosted/wger/app
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: postgres-cluster
      namespace: dbms
    - name: dragon-cluster
      namespace: dbms
    - name: longhorn
      namespace: longhorn-system
    - name: volsync
      namespace: volsync-system
    - name: akeyless-stores
      namespace: external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
