apiVersion: v1
kind: Secret
metadata:
    name: hoarder-secret
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:/s1mJ7eRFt08T6YXvrU43glQIZNBRe6C6hQKSD5T1z/ezow2,iv:8zdWHEcaRUJ5So/ANybygwN0vDnpkatRAXnfKoj9RFc=,tag:k3dkEiMSHgXJ1egx64C54A==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:r8ep2Prt7o8M+8t4TbS2VyoDPJHELhkR6AAfKhZAIDYlEvgw,iv:PF077Qbhl9taygr/e30B8z+AuXwwA8ZkElyYAXsxrcY=,tag:CqUMaKeWiqk/W8tfo7XCbg==,type:str]
    #ENC[AES256_GCM,data:V5VFaSI2LgqEABwufFK8SkknJWAZw5CAS9DnFUiKOZU/AUsc3G0vJ6XyoZzx7njAsc51HmcmCH0Fsi1UMNaY8PwGJAFy2Jm+HBv3R7jhbV/g5JMBGshDK3dYLeO0JvkwuUhVuqQVqRPtej9BggwrMVTAFq1m0TH4dsudf+FgNPfoOgb7pIcJGbwpt9SpZVCr4Gy8N1KgxmmQAxJKSP8KPw7HXC2BgLCPyKeDJXKA6a2YMqGA2A==,iv:RRdMqU+zDJOCBv+e5vpRfgLsgQi/R1fptFVirbN7nHA=,tag:vcy7Mrx2Qzc/Nm8EFdfaUw==,type:comment]
    OAUTH_WELLKNOWN_URL: ENC[AES256_GCM,data:gKGBRZxdI5ZV3BeXsqqWYx6XKRt7+FldGx7cMZN5WdIcNgRlYpoaECaMK+ubDZY5jUsd0p1k2szgE7kzrTU=,iv:WhU725Er4aTnB8TApUqCvoOhL+S7s8giai/fikRBti8=,tag:+vL+W93JUvClilRX5d+2ew==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:NY1Rx0ApXA==,iv:ft8bKPUqpjtCMIRKBK2AIBptzMoi51SDccev4Vhadx4=,tag:z7pTge8k/SyUZTt08xdhNQ==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:dLR4KNeJJWt2wD1KudUgPWtmDlPfQaf+HCoJbi/90L9lXFZjUpVDb4BJWiHOTYVMnS0uehAsLMbRswivlGI+I2Tn1NPzDxSS,iv:9+HQZmdQeQzdZVi3pUjpjzDn3ngglb2GJ9rnGCciFqs=,tag:DSOkTWN2JnnxqKevC4vBtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T23:07:55Z"
    mac: ENC[AES256_GCM,data:ln2CL46MOHABDrDJ9CpuA0Vf3X3sphXgwWG/6EuKnjYPqTRaIDPeuhnD8WG/14yakQR8q4XoloW4AJHKcDgJEbLVz6wbGhULcyaYooMwJGYy1usp7N+VjEyJ7QIDP9Nbj3kD0bgYjCCoaJodI3oSvbFyLhq7Wg3LIb3MY2mKApo=,iv:kNRp4KLeInf5JEiDO8ja5in9dUFl4+qHijFt5Oqc01Q=,tag:d5gM+PuPA0iPViPPDwvGgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
