# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:JF1+9WG70BUNCTSvEV+cLjwYfpnWX95VTgJ4MXZYA/X7bK9sIXZ7YA==,iv:h/bMhB//peaiVO6g51D50OLbaZ4YurNGyL21gSkFcnM=,tag:Ni2QMWwzVBQEGwNY2habWA==,type:str]
sops:
  age:
    - recipient: age1pj705hhyh9u9dwxsj2ak9l49tv3nqqlfxj4zxsj0wkrpnlywdvzqf7vz08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTlVTYm9OOG9xR25HcXE1
        ZGQybkhMU0ZzZnE4cXFmWFI1SVdKZHlVeHdZCk5DR2NuaTJiWXBXblFxSDdSU0xZ
        cXQ5ZkhvdEhNbnlsUWpzUkJKOXZnTnMKLS0tIExpZWIyQkMvWjNLa3FQeXd6a24z
        WHdCNkFzRFEyYXc3RC9qRStvUU9iczAKHz9Ph7cbwWqKO2il5i/jjTxdFg/pQHQg
        cOGwAbFJrvF6jGtACMVrUkPIzrcTb85CcSdHDADOTOe6M5KY42YP7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-12T16:55:42Z"
  mac: ENC[AES256_GCM,data:TBEaSohydVVYKy5nerMP+1HI58hfhHXlwDFTvo91pFhW2z+FybJbWGnozclZRDDv2vUovr9eaMIPT1UXVfJwaDQ80Rv4GyQySfRZpaDoE2PZVNP1fsV+Yc687btg/wJYTX2gplsqBb9fNgf0BHRZm2RbNgUVWtdK0g1TdlVsje0=,iv:EJaPnFEiNBw5+5OKURErcgneLRXFzfplgwGdFtXfte4=,tag:Zyoa5Olvvat1ZXm1IWdthg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
