# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:UolvThoUszjQ8u25o0JppUGrdEnEPkDtL7AurRXHhhRRD+tlhftfsw==,iv:rDc13X2Jug2lumGG7Bf0Ca8oy9Noxexk0XKvQAWSenQ=,tag:EVJrPn7SNq1xqSu778y9OQ==,type:str]
sops:
    age:
        - recipient: age1pj705hhyh9u9dwxsj2ak9l49tv3nqqlfxj4zxsj0wkrpnlywdvzqf7vz08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTlVTYm9OOG9xR25HcXE1
            ZGQybkhMU0ZzZnE4cXFmWFI1SVdKZHlVeHdZCk5DR2NuaTJiWXBXblFxSDdSU0xZ
            cXQ5ZkhvdEhNbnlsUWpzUkJKOXZnTnMKLS0tIExpZWIyQkMvWjNLa3FQeXd6a24z
            WHdCNkFzRFEyYXc3RC9qRStvUU9iczAKHz9Ph7cbwWqKO2il5i/jjTxdFg/pQHQg
            cOGwAbFJrvF6jGtACMVrUkPIzrcTb85CcSdHDADOTOe6M5KY42YP7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T19:02:03Z"
    mac: ENC[AES256_GCM,data:0RbpCxsIpxi2AP3XsSgNnWUBulj5UQXccwUjzpBGesG+SC8Hv3uIeL8S8W/qrx4BQyiSJyV0ODREnbbx0XfMsohssOR9KRSLyLIicpC9cwvzrhn/UD7FVbkKMhRqnCJ3jYSt/ZexAMbNqjY/ixMTUwfA14Mx/97JS8gehLF+eb4=,iv:yxsItEbvJcXqRgep1F0LSuwcCFWQnCRCLUAwkCOImBs=,tag:PKxp7KpvIqD8MvitMO6nvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
