# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Y7tTooMLDoLWf9SADesQWsqFFBigwY2iL8utHspSl6yJ6SjvC7CLgw==,iv:X7vYQtJQqk99kvaXgoKE56qQy3pT0a+RRmkR8G/79EM=,tag:wijRaRx1aGl9Ju3qPM+Nlg==,type:str]
sops:
    age:
        - recipient: age1pj705hhyh9u9dwxsj2ak9l49tv3nqqlfxj4zxsj0wkrpnlywdvzqf7vz08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTlVTYm9OOG9xR25HcXE1
            ZGQybkhMU0ZzZnE4cXFmWFI1SVdKZHlVeHdZCk5DR2NuaTJiWXBXblFxSDdSU0xZ
            cXQ5ZkhvdEhNbnlsUWpzUkJKOXZnTnMKLS0tIExpZWIyQkMvWjNLa3FQeXd6a24z
            WHdCNkFzRFEyYXc3RC9qRStvUU9iczAKHz9Ph7cbwWqKO2il5i/jjTxdFg/pQHQg
            cOGwAbFJrvF6jGtACMVrUkPIzrcTb85CcSdHDADOTOe6M5KY42YP7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T17:31:52Z"
    mac: ENC[AES256_GCM,data:9axJU/finvXYHQH3/z01vSOSHZJ6b2/Z6gMSr9b1W58beOREJs+SVBQNqUbYNMfF7GfqghVEjkAkNbNrsd3aihJIdS3WPS01cWpDuUpW/8B8u7yti0IiipkRyu2n8sSSh8FlBpuq0iic9IlQ+I/5lcDICXt9ldao7bE7JtWBc+w=,iv:gbbmq52avT1rRSE7V8pHkxCg0JJ/AZIUKfMhLdPqGzY=,tag:WIG62jp6qFoVf7KNuAHpeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
