---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sparkyfitness
spec:
  chartRef:
    kind: OCIRepository
    name: sparkyfitness
  interval: 30m
  values:
    controllers:
      sparkyfitness:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/codewithcj/sparkyfitness-server
              tag: v0.17.0@sha256:6dcf967461eab4c81dbfce6f4751dba7fd2485403042e490266a0224ca6d48e4
            env:
              TZ: "America/Los_Angeles"
              SPARKY_FITNESS_EMAIL_SECURE: true
              SPARKY_FITNESS_FORCE_EMAIL_LOGIN: true
              SPARKY_FITNESS_DISABLE_SIGNUP: true
              ALLOW_PRIVATE_NETWORK_CORS: true
              NODE_ENV: "production"
              SERVER_UPLOADS_PATH: /uploads
              SPARKY_FITNESS_FRONTEND_URL: fitness.${SECRET_DOMAIN}
              SPARKY_FITNESS_DB_HOST:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-psql-app"
                    key: host
              SPARKY_FITNESS_DB_PORT:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-psql-app"
                    key: port
              SPARKY_FITNESS_DB_NAME:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-psql-app"
                    key: dbname
              SPARKY_FITNESS_DB_USER:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-psql-superuser"
                    key: user
              SPARKY_FITNESS_DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-psql-superuser"
                    key: password
              SPARKY_FITNESS_APP_DB_USER:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-psql-app"
                    key: user
              SPARKY_FITNESS_APP_DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-psql-app"
                    key: password
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 512Mi
          frontend:
            image:
              repository: ghcr.io/codewithcj/sparkyfitness-frontend
              tag: v0.17.0@sha256:17a2bb8ab60bce2995495ca5cfcb3c821341d9114859bd09b58d775df01220a9
            env:
              PROMETHEUS_ENABLED: "true"
              SPARKY_FITNESS_LOG_LEVEL: error
              SPARKY_FITNESS_SERVER_HOST: localhost
              SPARKY_FITNESS_SERVER_PORT: 3010
              SPARKY_FITNESS_FRONTEND_URL: fitness.${SECRET_DOMAIN}
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
    service:
      app:
        controller: sparkyfitness
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - fitness.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      uploads:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          sparkyfitness:
            app:
              - path: /app/SparkyFitnessServer/uploads
