---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: peanut
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: peanut-secret
    template:
      engineVersion: v2
      data:
        API_PASSWORD: "{{ .NUT_API_PASSWORD }}"
  dataFrom:
    - extract:
        key: /peanut
