---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguardhome-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: adguardhome-sync-secret
    template:
      engineVersion: v2
      data:
        ORIGIN_USERNAME: "{{ .ADGUARD_HOME_USER }}"
        ORIGIN_PASSWORD: "{{ .ADGUARD_HOME_PASSWORD }}"
        REPLICA_USERNAME: "{{ .ADGUARD_HOME_REPLICA_USER }}"
        REPLICA_PASSWORD: "{{ .ADGUARD_HOME_REPLICA_PASSWORD }}"
  dataFrom:
    - extract:
        key: /adguard-home

