---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sparkyfitness-server
spec:
  chartRef:
    kind: OCIRepository
    name: sparkyfitness
  interval: 30m
  values:
    controllers:
      sparkyfitness-server:
        forceRename: sparkyfitness-server
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf
            envFrom:
              - secretRef:
                  name: "sparkyfitness-initdb-secret"
        containers:
          app:
            image:
              repository: ghcr.io/codewithcj/sparkyfitness-server
              tag: v0.16.5.0@sha256:b03cf52f8eeee07eff039b3134b594a135503165fa3cee731e191d9302f681f1
            env:
              SPARKY_FITNESS_DISABLE_EMAIL_LOGIN: true
              SPARKY_FITNESS_FRONTEND_URL: https://fitness.${SECRET_DOMAIN}
              SPARKY_FITNESS_DISABLE_SIGNUP: true
              SPARKY_FITNESS_FORCE_EMAIL_LOGIN: true
              SPARKY_FITNESS_LOG_LEVEL: debug
              SPARKY_FITNESS_EMAIL_SECURE: true # Use 'true' for TLS/SSL, 'false' for plain text
              NODE_ENV: "production"
              TZ: "America/Los_Angeles"
              SERVER_UPLOADS_PATH: /uploads
            envFrom:
              - secretRef:
                  name: "sparkyfitness-secret"
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 128M
    service:
      app:
        ports:
          http:
            port: 3010
    persistence:
      config:
        enabled: true
        existingClaim: sparkyfitness
        globalMounts:
          - path: /uploads
