---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-gitops-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: k8s-gitops-runner-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        github_app_id: "{{ .ACTION_RUNNER_GITHUB_APP_ID }}"
        github_app_installation_id: "{{ .ACTION_RUNNER_GITHUB_INSTALLATION_ID }}"
        github_app_private_key: |
          {{ .ACTION_RUNNER_GITHUB_PRIVATE_KEY | b64dec }}
  dataFrom:
    - extract:
        key: /actions-runner
