---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autopulse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: autopulse-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: postgres-rw.dbms.svc.cluster.local
        INIT_POSTGRES_DBNAME: autopulse
        INIT_POSTGRES_USER: "{{ .AUTOPULSE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .AUTOPULSE_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
  dataFrom:
    - extract:
        key: /autopulse
    - extract:
        key: /cloudnative-pg
