---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wizarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: wizarr
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      wizarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/wizarrrr/wizarr
              tag: v2025.9.7@sha256:a2475c3404d5d16d2b9f05ff70ad17612cd2e1e1088debc1bd2d3571ed4fc1f5
            env:
              TZ: America/Los_Angeles
              PUID: &uid 1000
              PGID: &gid 1000
            resources:
              requests:
                cpu: 15m
                memory: 180Mi
              limits:
                memory: 300Mi
    service:
      app:
        ports:
          http:
            port: &port 5690
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
          - "onboard.${SECRET_DOMAIN}"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /data/database
      tmpfs:
        type: emptyDir
        advancedMounts:
          wizarr:
            app:
              - path: /.cache
