apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3Jf4hrnln3wzrUc=,iv:yy3Bbi8SBCAT+Fo4xt2uQPMqblmq0KgT/gAwq0hnw3E=,tag:hpFMWugalmyAK+VJlSQ5+g==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ZYI7y1SDgZktt+cwT8vRm898SLHX23O9CYZfQ4godJIR4O0m,iv:DctWg9b0LWK967XgAsu7KwSCCKfhcN+fnCgdHSjPHhU=,tag:DGwRCCH4lcIzsFqC+ospkg==,type:str]
sops:
    age:
        - recipient: age1qez67uw84ygk7q39yr3ht5nxzr32c8pf2zxc4znvn8lvtx3kqgmqv5wgu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNkdGM2dNY1lNMWUvTXBV
            ZVM3eHRZZmtMMmlMbzEreDlHV3VZRGJXTzM4CmtmeUR1Tmg2cml0RHVDL09QdVAr
            bkE4dG5jaXd4ZVhRek1HZXRVMlVNVFEKLS0tIFRURWtFUTBIZlBwQmhCUHVBNlUr
            ZVk2S25CRFpDTzZ5Y1pWT0NLcDI5RzQKqG8ivQG8eex0+BINcw1jPYRa05MjFC++
            25+xYvni/XSsuxMYmIrv15lXrm+H0bY1CBEeGGrYU2p+CX7QyZYfGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T09:30:27Z"
    mac: ENC[AES256_GCM,data:hF6FWwVLRgCk/2QCJwwrPZATkBaO4MMg46TcwehCUyMYbxK3TAwPs0fOMGb+E0PwXTCAjE9SwNlY2oV87MDRy4UtCVXEkoHtfWQofGSVXWS+J/08oTepyEyWWP6eynJ7EBDYd4i5h41hWkXoTnjuGPHS789F3wObbIHxRaRddME=,iv:ddjyEzxCCYFDEmIkOWkTDN8+QqkZ/CMeyNkgXzQ1u9A=,tag:ftZ4Z4rabIUC8vWRZEsgiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
