apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:2/1lgytTCZWEWsU=,iv:TaS5R/xH6qPxPnA4re3ZXTB9L8RwS1LV622WNlNMEzw=,tag:WgyXPXIQooRScFQk51utDQ==,type:str]
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:lTX+FxD1FX9iiVU36qPmQVUP8Mgd8ZgtGoszLDPfwmw=,iv:x/CUGXCMxq+GMWC6p/29Y0hleUyfCKrOble6i1EKX7o=,tag:jmCicGGOFdyrIMzSqT6vag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bytOOUkzanRxSFkzekQr
            U0xybDhSQjlpMUNmeCtZVWdkQ1ZZZnBtYUJFCjRQWlFZek02SkFHaGxianVrY0N3
            ZE44ZWRrSU8vUkEzODVSZEp3RjM5YVkKLS0tIFFZaFhmM3U5MU4ycTQydGpnRkRK
            c0NBMU1hUTZ2OXQwQm91OTZQbzhKbWMKhHSuDNZKggla3l07hmSMO1l1cPCmLhxI
            Fis1NiYKELYBkQ0ihccEWlRMiq9G6mkGkJrdgFy420gXPHf0kHY0Xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T21:45:44Z"
    mac: ENC[AES256_GCM,data:9sPGaywex+iLOUR/+PPdu877g97suwD5K8NMPL7DgwckWVk+qEdTCx/OP5zS9Uj4er9iswVLlMTMnRcy8ilhM36HB/7J8VjjouvmOmmQvFQRk0AKnv4jI7ijp3ORsu9jcFNA7YtdfIEC7pIBJ8W6hsMuBx9tnSeO91iqfqL9/WE=,iv:PI/U914ohrf/JYgceNlpvi1kWdH9O/XFHFcRO9bx3Wc=,tag:aQxDaYC2NAn6uNiQQrpTzA==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
