apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3Jf4hrnln3wzrUc=,iv:yy3Bbi8SBCAT+Fo4xt2uQPMqblmq0KgT/gAwq0hnw3E=,tag:hpFMWugalmyAK+VJlSQ5+g==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ZYI7y1SDgZktt+cwT8vRm898SLHX23O9CYZfQ4godJIR4O0m,iv:DctWg9b0LWK967XgAsu7KwSCCKfhcN+fnCgdHSjPHhU=,tag:DGwRCCH4lcIzsFqC+ospkg==,type:str]
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:X3V3+Qqve/KD6xAbX4DEWMmqMUfFCXUCzqXYH5pOZas=,iv:w0NrfNcTvYyJ7WiJGGk6vV+ak8lnU7Z+lOZbWCA+Zk8=,tag:Vvb949FoAR+IUWbqrB3qwQ==,type:str]
sops:
    age:
        - recipient: age1qez67uw84ygk7q39yr3ht5nxzr32c8pf2zxc4znvn8lvtx3kqgmqv5wgu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNkdGM2dNY1lNMWUvTXBV
            ZVM3eHRZZmtMMmlMbzEreDlHV3VZRGJXTzM4CmtmeUR1Tmg2cml0RHVDL09QdVAr
            bkE4dG5jaXd4ZVhRek1HZXRVMlVNVFEKLS0tIFRURWtFUTBIZlBwQmhCUHVBNlUr
            ZVk2S25CRFpDTzZ5Y1pWT0NLcDI5RzQKqG8ivQG8eex0+BINcw1jPYRa05MjFC++
            25+xYvni/XSsuxMYmIrv15lXrm+H0bY1CBEeGGrYU2p+CX7QyZYfGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T06:20:52Z"
    mac: ENC[AES256_GCM,data:SJlRSonZj9c8+XZeZSI0GGANsY0j25Hz9wrasRw3oOp/DN/FZb3tRps+NeBky3xFI4NPcbkEPNAmErqFZYATKYoz5u7HtylL7fqvMMDCd6SyREGJMwjI8oCDcg11jp+HsjbWalRExi5O0v53eWo3UqjTBwaBeATz1DuMTTqYspA=,iv:4nFQWR5On32+auAR/pyLguYvPLrOXtuNaeSntbJ39pk=,tag:uI2H4JIdoQlpgScEFG72WQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
