---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: beets-secret
    template:
      engineVersion: v2
      data:
        config.toml: |
          [frontend]
          username = "{{ .BETANIN_USERNAME }}"
          password = "{{ .BETANIN_PASSWORD }}"
          [clients]
          api_key = "{{ .BETANIN_API_KEY }}"
          [server]
          num_parallel_jobs = 1
          [notifications.services]
          [notifications.strings]
          title = "Music Imported"
          body = "$name"
  dataFrom:
    - extract:
        key: /beets
