---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app beets
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      autom4b:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          autom4b:
            image:
              repository: lscr.io/linuxserver/beets
              tag: 2.3.1-ls283
            env:
              TZ: America/Los_Angeles
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    persistence:
      audiobooks:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/media/audiobooks
        globalMounts:
          - path: /audiobooks
      input:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/autom4b/untagged
        globalMounts:
          - path: /input
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config
      scripts:
        type: configMap
        name: beets-scripts
        globalMounts:
          - path: /scripts
            subPath: /custom-cont-init.d

