---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: beets
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      beets:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          auto-m4b:
            image:
              repository: seanap/auto-m4b
              tag: latest@sha256:bf50bb8c674a6cced23115fc260791a72782e1ab57dbeff5184b848f4737bc6e
            args:
              - --input-dir=/import
              - --output-dir=/import
              - --watch
              - --delete
              - --output-format=m4b
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/beets
              tag: 2.3.1@sha256:cc4975f1a0be4e238d29fe13c18ce37e08964af0d5ceb1811485751b6490bcaf
            command: ["/bin/sh", "-c"]
            args:
              - |
                echo "Installing inotify-tools..."
                apk add --no-cache inotify-tools
                echo "Watching /import for changes..."
                while true; do
                  inotifywait -r -e close_write,move,create,delete /import && \
                  echo "Detected change, importing..." && \
                  beet -c /config/.config/beets/config.yaml import /import
                  sleep 5
                done
            env:
              TZ: America/Los_Angeles
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 8337
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        type: emptyDir
      audiobook:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/media
        globalMounts:
          - path: /audiobooks
            subPath: audiobooks
      import:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/media
        globalMounts:
          - path: /import
            subPath: audiobooks-import
      config-file:
        type: configMap
        name: beets-configmap
        globalMounts:
          - path: /config/.config/beets/config.yaml
            subPath: config.yaml
            readOnly: true
      # secret-file:
      #   type: secret
      #   name: beets-secret
      #   globalMounts:
      #     - path: /config/.config/betanin/config.toml
      #       subPath: config.toml
      #       readOnly: true
      tmp:
        type: emptyDir


