---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app beets
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      beets:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          beets:
            image:
              repository: ghcr.io/home-operations/beets
              tag: 2.3.1@sha256:cc4975f1a0be4e238d29fe13c18ce37e08964af0d5ceb1811485751b6490bcaf
            env:
              TZ: America/Los_Angeles
            # probes:
            #   liveness: &probes
            #     enabled: true
            #   readiness: *probes
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        type: emptyDir
      audiobooks:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/media/audiobooks
        globalMounts:
          - path: /audiobooks
      input:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/autom4b/untagged
        globalMounts:
          - path: /input
      config-file:
        type: configMap
        name: beets-configmap
        globalMounts:
          - path: /config/.config/beets/config.yaml
            subPath: config.yaml
            readOnly: true

