---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/heads/main/install/kubernetes/cilium/values.schema.json
autoDirectNodeRoutes: false
bpf:
  datapathMode: netkit
  masquerade: true
  preallocateMaps: true
  tproxy: true
bgpControlPlane:
  enabled: true
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
debug:
  enabled: false
endpointRoutes:
  enabled: true
pmtuDiscovery:
  enabled: true
# Doesn't work on talos
sysctlfix:
  enabled: false
envoy:
  rollOutPods: true
  connectTimeoutSeconds: 15
  debug:
    admin:
      enabled: true
gatewayAPI:
  enabled: true
  enableAlpn: true
  xffNumTrustedHops: 1
  externalTrafficPolicy: Cluster
dashboards:
  enabled: true
hubble:
  enabled: true
  listenAddress: ":4244"
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
    dashboards:
      enabled: true
  relay:
    enabled: true
    rollOutPods: true
    prometheus:
      enabled: true
  ui:
    enabled: true
ipam:
  mode: kubernetes
# So I don't have to worry about this again
k8sClientRateLimit:
  qps: 20
  burst: 40
  operator:
    qps: 200
    burst: 400
ipv4NativeRoutingCIDR: "10.42.0.0/16"
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: "dsr"
  dsrDispatch: geneve
cluster:
  id: 1
  name: dormammu
nodePort:
  enabled: true
  dsrDispatch: geneve
operator:
  replicas: 2
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
rollOutCiliumPods: true
routingMode: tunnel
tunnelProtocol: geneve
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cni:
  exclusive: false
socketLB:
  hostNamespaceOnly: true
# Graceful Helmfile to HelmRelease takeover
commonLabels:
  helm.toolkit.fluxcd.io/name: cilium
  helm.toolkit.fluxcd.io/namespace: kube-system
