---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: longhorn-secret
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_ENDPOINTS: http://minio.storage.svc.cluster.local:9000
  dataFrom:
    - extract:
        key: /minio
