apiVersion: v1
kind: Secret
metadata:
    name: s3-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:GIpczajHR+6ZOzoxuACYylRU,iv:pgrtLmTOBVdb2ZY14hRt1k5xSrHbrpU6UBrwjRxVmHQ=,tag:mimWPxd9BEwEbfi4ggdnTA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5E+SsxuO8/DRbhQqJq9F7A5GM2IgRA==,iv:v07H0Ugyqs/V3jQc4B2HhrnrBhwFkBem/dLv1mp+0Ek=,tag:OLZ3FY2+c12rHnDphX8ifw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Gmcb4BAMOyDKCh0VFGUaovS+zQwOnOAgfM7GRAOI4dpDcIbhNaSR0FENZA==,iv:nQXiwYLHW9ULk9kzEkR9rPgX99XTP3i5FdjzNHpeA84=,tag:oFhMmePjVoGT+Vlgct9K9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaFBxdUk1TzA0Q2hreCtx
            NDJvUDlpeW9xR04xRTFSMXhzRlBtV3ZNd21JCnVYSVRaNUxmTWVyZWhYYkpua0Rq
            QkpVN2JiTWdqUzZkWklCMWJMT3BsbzAKLS0tIHJlVTJQM3hMaEQ2T05wWUxzQ2J1
            MkZPMkkxTmN4ZWd2c2pLdHZCZTc2UWMKo16dhqOOWKeHCGmdqBDrzilFIhBvjRJC
            yCWO4SrpwZqhu2SR2swHbTZdJHpH5cpF3FNBhxJEyLgu6hmaYaMGVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T02:06:56Z"
    mac: ENC[AES256_GCM,data:PD77nC7/QQj86+doJJy2lUtKxqQvsQ2q0g41JibLmUGIhMV0T1xxWAR9AFb49woxe5AkyhBgrObGcb05lbVVJ+OvFk6gmp7Z/gmovLQixYlwuwXBBMIStPm62eCBumK/8qkXgc0ANlKc9+t2Ql1/AOO2iTTNnKQV4hpCiasZYyU=,iv:6u+tnakb4cV3aGj6lH2f/CLzLltN8G/6D7FzxdRgbVg=,tag:HAU7NcX8rY8CyohIVNL4hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
