---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: authelia-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: &dbHost "{{ .POSTGRES_HOST }}"
        INIT_POSTGRES_DBNAME: &dbName authelia
        INIT_POSTGRES_USER: &dbUser "{{ .AUTHELIA_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .AUTHELIA_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        # App
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
        AUTHELIA_STORAGE_POSTGRES_ADDRESS: *dbHost
        AUTHELIA_STORAGE_POSTGRES_DATABASE: *dbName
        AUTHELIA_STORAGE_POSTGRES_USERNAME: *dbUser
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: *dbPass
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .LLDAP_LDAP_USER_PASS }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}"

        # Other Variables
        JWT_SECRET: "{{ .AUTHELIA_JWT_SECRET }}"
        JWKS_KEY: |
          {{ .AUTHELIA_JWKS_KEY | b64dec }}

        # Oidc
        # docker run authelia/authelia:latest authelia crypto hash generate argon2 --random --random.length 64 --random.charset alphanumeric
        SECRET_DOMAIN: "{{ .SECRET_DOMAIN }}"
        GRAFANA_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OAUTH_CLIENT_SECRET }}"
        PGADMIN_OAUTH_CLIENT_SECRET: "{{ .PGADMIN_OAUTH_CLIENT_SECRET }}"
        HOARDER_OAUTH_CLIENT_SECRET: "{{ .HOARDER_OAUTH_CLIENT_SECRET }}"
        LUBELOG_OAUTH_CLIENT_SECRET: "{{ .LUBELOG_OAUTH_CLIENT_SECRET }}"
        MEALIE_OAUTH_CLIENT_SECRET: "{{ .MEALIE_OAUTH_CLIENT_SECRET }}"

        # Smtp
        AUTHELIA_NOTIFIER_SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        AUTHELIA_NOTIFIER_SMTP_ADDRESS: "{{ .SMTP_HOST }}:587"
        AUTHELIA_NOTIFIER_SMTP_SENDER: "{{ .AUTHELIA_SMTP_ADDRESS }}"
        AUTHELIA_NOTIFIER_SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        AUTHELIA_NOTIFIER_SMTP_STARTUP_CHECK_ADDRESS: "{{ .SECRET_ACME_EMAIL }}"

  dataFrom:
    - extract:
        key: /cloudnative-pg
    - extract:
        key: /authelia
    - extract:
        key: /lldap
    - extract:
        key: /generic

