apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:CbTq+Cs716YRynJI9OKnfC2KKHxRIH9Ew0YMrrd5WEQ=,iv:7WTMzUpe6R+J5K2eNl+RONcKFfX0VKr7EY2FmDF9N7k=,tag:3xy0iyCX2UpkDjabNv6RGg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZER0S0lVUVl1cW5Ed2NG
        MEdoS1BCaDV3NnJNYnp2V3c4R2lsTXE4Z1N3CmcxdEZiQ0h1dmUzTjB1Vkg5RGRo
        UkxxSW9udmtRM2xqNGZHRnFyVHNRVncKLS0tIFpkM1BucDQ3ZHRCVGlXYk9vcENX
        blVCWnZVZXRzYVJ1TWVQcXg1QzlyRTgKhzUdGrP8K6oReVUszI5RwO6jSv+DXtU7
        AX08XYXPwg5Q0Vc6kNyAsopmsVoQjpGTOdbTTOLIrxM9EAjo8OjyHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T14:16:58Z"
  mac: ENC[AES256_GCM,data:ZUMGajAm82le8UTxhoKN8U/o106VJKSDPJhwZIHzuYpntvhti/Z6ieVr8zv+jGZmPfnlR1erlKHTCGpWqQvkaTlKcZN7EX+kXUYh3+RGVoI5vPLNSSb2ZymyepKaeBLxUXvEOqWHFmtJWVGrKacAK737UGkSHLpA2/QQqzm8OzM=,iv:50zTh6UGKytd5bjQI4tvSiTgvUvM/Hu8bXUSUu65vOM=,tag:aWDnsUfBZ/Kv0f/CCALgGg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
