# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:YKKz0JdV1nxTGCOAOIpsXJjo7BSkCvEB3sAUmYgdzkI=,iv:OStxuiNkU7IMyqkIz8UxyDt95H+rpYCfWYL+jUh+fGk=,tag:WC3RjTR6Rh9SsrA2PQrajQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaFBxdUk1TzA0Q2hreCtx
        NDJvUDlpeW9xR04xRTFSMXhzRlBtV3ZNd21JCnVYSVRaNUxmTWVyZWhYYkpua0Rq
        QkpVN2JiTWdqUzZkWklCMWJMT3BsbzAKLS0tIHJlVTJQM3hMaEQ2T05wWUxzQ2J1
        MkZPMkkxTmN4ZWd2c2pLdHZCZTc2UWMKo16dhqOOWKeHCGmdqBDrzilFIhBvjRJC
        yCWO4SrpwZqhu2SR2swHbTZdJHpH5cpF3FNBhxJEyLgu6hmaYaMGVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-24T00:58:49Z"
  mac: ENC[AES256_GCM,data:Sw+emqlzjfnLnzFF7O5Z8f7OsmCFCSAhjlNNgIsK4M64gP67HIT+Lh4DMEji9iJLSIJwg9dd4T7iv/xZMjpmBIwLBge6d0ulWSDDBiQl1kyL7eRma0vOjcuCXPbl3vz9P9UZ68YOXFHb+zFJhcPIXp+VauK+gPkVaMQdg3IaYwU=,iv:FZrktWlQstlwyqYtWXhcZw/BALq4mzPrEeAYwCT10OI=,tag:iwi1qC0/j8u9JvKyLMGP2A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
