apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:hNPB1B5AlKiaKANizLJDiz2f9NHdpNzoQLRGreVieoE=,iv:rjfEEOB9/JBnHKiI3oYCTdQTGAK4aFi/AMTKdZDuMCY=,tag:Zud0ebmBytwe2plwF6FyXA==,type:str]
sops:
  age:
    - recipient: age1qez67uw84ygk7q39yr3ht5nxzr32c8pf2zxc4znvn8lvtx3kqgmqv5wgu5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0a1VVc1BkUXdVNmI5VVlE
        UWZqVUtsRyt4QnBkKzROMytjbDFJQ2tZY2p3CmV3WUIyZHRpSFJVU2c1RzNDaEps
        aXZueEMvdGpSUnorMmkrUFRQVzhFVHcKLS0tICt6cHU3TEpMVzMrWEpYN0d1c0Ra
        czdqSkgrL0Fhb1NyQVZFT1JpZ3hEMmsKuXG4pKjwGvC+OGLsff00LnQfPMo12y7T
        NEShRZSg0ry8Q7Lp5swzwx6SeCAjGY6dyQbshpp7BIZdNZffWCHK7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T09:09:52Z"
  mac: ENC[AES256_GCM,data:3cAsAcFp21rODlGvh3AvLejyCafuA3fReeLUPo6XkaFB02gwYWh9sp3+weMUZyHJFi50Oiv67/1P0EnCFqRqVI1/JUNUCv2iXs1ADnZRHwGbX7fOrJR/4d44nHxPIIBUUsa+bjmtAdIu/lOKCso634cnEUtC0Q7tTgmyiQYGCNs=,iv:UKFQ4oEL5Vcm4VntnGtY//YlUu8SyxJsJZGWRjCcYro=,tag:fxtEvZ3rgmQYPZaHUzafuA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
