---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: external-dns-cloudflare-secret
    template:
      engineVersion: v2
      data:
        CF_API_TOKEN: "{{ .CLOUDFLARE_EXTERNAL_DNS_TOKEN }}"
  dataFrom:
    - extract:
        key: /cloudflare
