apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:oX1AxzvLHFgeE5tD3wG/gtZAL/qYNmMKMcDmeKNGmE9YHrm41TvMnA==,iv:ikNJplgfH033z27L9dDvGqVKoRglXLVr4ikyAQJUX6w=,tag:jL6oRC4NT0U1GlA+hlpq6w==,type:str]
    CF_ZONE_ID: ENC[AES256_GCM,data:tVEqiTtMX0DHw8ZvIk9pltWHbJBtKtOX/2aSIVqDUb0=,iv:dPzcmGRFln6vemIVuzdyfFkjrn2pa3C8sjpxZribLZI=,tag:X8XH5ALiylHBDu6nyB0xGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Q2NaUHJEQk4rRjhaMlV3
            eU5nZ1hMSmY5SkwvVEI5Ukt1ajhPT2xsUEE4CmdxMHlaRUlIdWh6Z1l0WmwvUXg1
            WWRUNGIrMnFUSnEyYlV1ZzdFa3FIdEEKLS0tIExJOTBiZ3hFZk12SHdnazBPUE1K
            OTVwaXkvcVE5MmJSRmI2VTNCMkJsMDgKwKHRA67IfUIJIK6jFuMZMtClhg0pCo6R
            t7O59ct2rTi8SL9onGebCc5yMgWbZ5loKYQxqNrl6nBg7bvuTNVyog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-23T21:22:25Z"
    mac: ENC[AES256_GCM,data:oExIsAw2si0xCqfzboa9RRpF00/ZEYdQR+9Fgbt6d+Ld1XJ00XZNps9KvS+iFWf3uhBH0k2we5ItOPy/mIB4UFGqeUuAenX20mL3yUc1Fq2IO9KrHEUZh6VZ/bSxPv4AlSVVl9xZ5+j45Ri3VUdPk7gWiYhcXb8nS+mXYxRhMig=,iv:TTKyF/mhgn+fgB8EZMi7FTt11651t43L2OEdsqtz5IQ=,tag:fK3/58SgVtwv+6sNG5RA9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
