apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:NrFcCh2Oq7RmHpmCNwhTroMNKkgyFr5bpunpKzZ/ELnRbnt/P0q2Rw==,iv:p+uitqAxAfdn9ekjBRMrRBfBHoAkZDoityVOhWBdPVA=,tag:UgCetaJz7leaHPACGVpDzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-25T03:09:37Z"
    mac: ENC[AES256_GCM,data:2Vp3OZuoF6AgDtCydbAMUa8e+8tmsdYaQvwUxcSlCTyXncgOfSOczM+0yhaCE7oFJ4vufJOpDOY/AulRjphr2+RZsgAprditjV+856o7xMLYR3vwOdSQnmP5elGXAK9ySpO2y69dP3eTv/tX2F8NCPx3QamJLRRmGzna2ZnGXkg=,iv:tZVe2+IvkO4t1bRSFvIs58O+fkHABC43qUEYlSgcxek=,tag:knlrnUXMsdDr27XSSGFD8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
