---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: mealie-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: &dbHost postgres-rw.dbms.svc.cluster.local
        INIT_POSTGRES_DBNAME: &dbName mealie
        INIT_POSTGRES_USER: &dbUser "{{ .MEALIE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .MEALIE_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        # App
        DEFAULT_EMAIL: "notification@${SECRET_DOMAIN}"
        DB_ENGINE: postgres
        POSTGRES_DB:  *dbName
        POSTGRES_SERVER: *dbHost
        POSTGRES_USER:  *dbUser
        POSTGRES_PASSWORD: *dbPass
        OIDC_CLIENT_ID: "{{ .MEALIE_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .MEALIE_CLIENT_SECRET }}"

        # Smtp
        MAIL_DRIVER: smtp
        SMTP_HOST: "{{ .SMTP_HOST }}"
        SMTP_PORT: "587"
        SMTP_FROM_NAME: Mealie Admin
        SMTP_FROM_EMAIL: notification@${SECRET_DOMAIN}
        SMTP_USER: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        SMTP_SECURE: "true"

  dataFrom:
    - extract:
        key: /mealie
    - extract:
        key: /cloudnative-pg
    - extract:
        key: /generic
