---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads

components:
  - ../../components/sops
  - ../../components/namespace

resources:
  # - ./brrpolice/ks.yaml
  # - ./decluttarr/ks.yaml
  - ./deduparr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./prowlarr/ks.yaml
  # - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./seasonpackerr/ks.yaml
  - ./sonarr/ks.yaml
