---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome-fleet-server
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: esphome-fleet-server-secret
    template:
      data:
        SERVER_TOKEN: "{{ .SERVER_TOKEN }}"
  dataFrom:
    - extract:
        key: esphome-fleet-server
