---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nebula-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: nebula-sync-secret
    template:
      engineVersion: v2
      data:
        PRIMARY: "{{ .PRIMARY_HOST }}"
        REPLICAS: "{{ .REPLICA_1_HOST }}"
  dataFrom:
    - extract:
        key: /nebula-sync

