---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: qbittorrent-secret
    template:
      engineVersion: v2
      data:

        GLUETUN_CONTROL_SERVER_API_KEY: "{{ .GLUETUN_CONTROL_SERVER_API_KEY }}"

        # wireguard
        WIREGUARD_ADDRESSES: "{{ .WIREGUARD_ADDRESSES }}"
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_PUBLIC_KEY: "{{ .WIREGUARD_PUBLIC_KEY }}"
        WIREGUARD_ENDPOINT_IP: "{{ .WIREGUARD_ENDPOINT_IP }}"
        WIREGUARD_ENDPOINT_PORT: "{{ .WIREGUARD_ENDPOINT_PORT }}"
        VPN_PORT_FORWARDING_USERNAME: "{{ .VPN_PIA_USER }}"
        VPN_PORT_FORWARDING_PASSWORD: "{{ .VPN_PIA_PASSWORD }}"
        SERVER_NAME: "{{ .SERVER_NAME }}"


        # Openvpn
        OPENVPN_USER: "{{ .VPN_PIA_USER }}"
        OPENVPN_PASSWORD: "{{ .VPN_PIA_PASSWORD }}"
        SERVER_REGIONS: "{{ .SERVER_REGIONS }}"

        #gluetun auth
        auth.toml: |
          [[roles]]
          name = "gluetun-qb-port-sync"
          routes = [
            "GET /v1/publicip/ip",
            "GET /v1/openvpn/portforwarded"
          ]
          auth = "apikey"
          apikey = "{{ .GLUETUN_CONTROL_SERVER_API_KEY }}"

  dataFrom:
    - extract:
        key: /qbittorrent
