---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: qbittorrent-secret
    template:
      engineVersion: v2
      data:
        # wireguard
        VPN_PIA_USER: "{{ .VPN_PIA_USER }}"
        VPN_PIA_PASS: "{{ .VPN_PIA_PASSWORD }}"

  dataFrom:
    - extract:
        key: /qbittorrent


