---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: qbittorrent-secret
    template:
      engineVersion: v2
      data:

        # # Openvpn
        # OPENVPN_USER: "{{ .VPN_PIA_USER }}"
        # OPENVPN_PASSWORD: "{{ .VPN_PIA_PASSWORD }}"
        # OPENVPN_CONFIG: "{{ .OPENVPN_CONFIG }}"
        # GLUETUN_CONTROL_SERVER_API_KEY: "{{ .GLUETUN_CONTROL_SERVER_API_KEY }}"

        # wireguard
        VPN_PIA_USER: "{{ .VPN_PIA_USER }}"
        VPN_PIA_PASS: "{{ .VPN_PIA_PASSWORD }}"
        # VPN_PIA_PREFERRED_REGION: "${{ .VPN_PIA_PREFERRED_REGION }}"
        # wg0.conf: "{{ .wg0conf }}"

  dataFrom:
    - extract:
        key: /qbittorrent


