---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      qbittorrent:
        containers:
          app:
            image:
              repository: ghcr.io/hotio/qbittorrent
              tag: release-5.1.2
            env:
              QBT_WEBUI_PORT: &port 8080
              PRIVOXY_ENABLED: false
              UNBOUND_ENABLED: false
              VPN_ENABLED: true
              VPN_CONF: wg0
              VPN_PROVIDER: pia
              VPN_LAN_NETWORK: 10.0.0.0/8
              VPN_AUTO_PORT_FORWARD: true
              VPN_FIREWALL_TYPE: auto
              VPN_PIA_PORT_FORWARD_PERSIST: false
              VPN_PIA_DIP_TOKEN: no
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            # probes:
            #   liveness: &probes
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /api/v2/app/version
            #         port: *port
            #       initialDelaySeconds: 0
            #       periodSeconds: 10
            #       timeoutSeconds: 1
            #       failureThreshold: 3
            #   readiness: *probes
            #   startup:
            #     enabled: true
            #     spec:
            #       failureThreshold: 30
            #       periodSeconds: 10
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        # runAsUser: 568
        # runAsGroup: 568
        # fsGroup: 568
        # fsGroupChangePolicy: OnRootMismatch
        # supplementalGroups: [65536]
    persistence:
      config:
        existingClaim: *app
      incomplete:
        type: custom
        volumeSpec:
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ReadWriteOnce]
                resources:
                  requests:
                    storage: 1Mi # Ignored
                storageClassName: longhorn
                volumeMode: Filesystem
      media:
        type: nfs
        server: shango.internal
        path: /mnt/user/data
      tmp:
        type: emptyDir
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
          - qb.${SECRET_DOMAIN}
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    service:
      app:
        forceRename: *app
        primary: true
        ports:
          http:
            port: *port
