---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
configMapGenerator:
  - name: qbittorrent-loki-rules
    files:
      - ./resources/lokirule.yaml
    options:
      labels:
        loki_rule: "true"
  - name: qbittorrent-coredns
    files:
      - ./resources/Corefile
    options:
      labels:
        coredns: "true"
generatorOptions:
  disableNameSuffixHash: true
