---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.13.9
  policy:
    rebootMode: powercycle
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      expr: |-
        !has(status.phase) || status.phase != 'Running'
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Restore
      expr: |-
        !has(status.phase) || !(status.phase in ['Resolving', 'Restoring'])
    - apiVersion: longhorn.io/v1beta2
      kind: Volume
      expr: |-
        !has(status.state) || status.state != "attached" || !has(status.robustness) || status.robustness != "healthy"
