---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: grafana-secret
    template:
      engineVersion: v2
      data:
        # Auth
        admin-user: "{{ .GRAFANA_ADMIN_USER }}"
        admin-password: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        # Database Init
        INIT_POSTGRES_HOST: &dbHost "{{ .POSTGRES_HOST }}"
        INIT_POSTGRES_DBNAME: &dbName grafana
        INIT_POSTGRES_USER: &dbUser "{{ .GRAFANA_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .GRAFANA_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App
        GF_DATABASE_NAME: *dbName
        GF_DATABASE_HOST: *dbHost
        GF_DATABASE_USER: *dbUser
        GF_DATABASE_PASSWORD: *dbPass
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        # Oidc
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .OIDC_GRAFANA_CLIENT_SECRET }}"
        GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
        GF_AUTH_GENERIC_OAUTH_NAME: Authelia
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .OIDC_GRAFANA_CLIENT_ID }}"
        GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email groups
        GF_AUTH_GENERIC_OAUTH_EMPTY_SCOPES: "false"
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://auth.${SECRET_DOMAIN}/api/oidc/authorization
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://auth.${SECRET_DOMAIN}/api/oidc/token
        GF_AUTH_GENERIC_OAUTH_API_URL: https://auth.${SECRET_DOMAIN}/api/oidc/userinfo
        GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: preferred_username
        GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: groups
        GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: name
        GF_AUTH_GENERIC_OAUTH_USE_PKCE: "true"
        # Datasources
        TESLAMATE_POSTGRES_PASSWORD: "{{ .TESLAMATE_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: /grafana
    - extract:
        key: /cloudnative-pg
    - extract:
        key: /generic
