---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: grafana-secret
    template:
      engineVersion: v2
      data:
        # Auth
        # admin-user: "{{ .GRAFANA_ADMIN_USER }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        # Datasources
        TESLAMATE_POSTGRES_PASSWORD: "{{ .TESLAMATE_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: /grafana
    - extract:
        key: /cloudnative-pg
