apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    #ENC[AES256_GCM,data:IHyiMMLZ0a8=,iv:nQhbeN9QarKOj13xjWwOH6e12TkQ0dtUZ5Gq1UUm3No=,tag:eYzd4JibK1eXD/WGl9cljw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:hPzE9I8i0g==,iv:if2cMdd8ruVOC0+i5n21NzDOEnmxVcG8ZdaCD07EDNU=,tag:ze0RVEb4BNGaJISqE09qCw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:EmxMgodyXKgPNXw8RPZ6m9WmBSzR,iv:hTSKl37mC3vhEBi693v5XgB/j2AnNXW/JKs/sFiZuhM=,tag:wJirsFeHuKwpkgRXLIbm9w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Sxn7vbGN,iv:t2eC/IV5TFjeJiYdYbv96C6vfkhgnAzWwwSpKPI20yw=,tag:CVT82oEwVvsg111RIAmRpw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:OSpRafLLiYnRqJEwkfgTuePYdxpfOWpcXV4x9ur4IWbZcVvU9fENkA4=,iv:QWUAAFpyv7hB4WKEiVwddahhxqGdtKrOenFXkPd5Nlk=,tag:HFWyhSeSGFuVkWl6h6m3Rg==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:Q4vPF4z8o8qsrrB+uHi67V/o3t2y8mh4N5Ax,iv:EiUWHcTRwH4qsA34QYeK38xdXtxOKibj8gKjM/DN6GU=,tag:ZGUI+f2VL9GH7GNBovBaEA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:DzK1hJMAdGky5G3musE3iJeDOndUjbVEyYIR,iv:RE3t4/qKhGYJZKArVrGAiVyftfjrshxD5z4NpKwgITQ=,tag:0XvgkJG2BVTJ1BxeajSEbQ==,type:str]
    #ENC[AES256_GCM,data:mVGT/50sWu05,iv:UVQqP8qcM5PyZYRrdAzxZf5au34d5Xu60sgHc6YQ+SA=,tag:V3gmqvi1/FEcWuiy2oO4IA==,type:comment]
    GF_DATABASE_USER: ENC[AES256_GCM,data:ZAGpXWnW,iv:c/MiqbD2Y5Z/Ihb1eg9JG1aJzoO8pAqjM0RpqusH6Eg=,tag:c6Qr9b0HhyIJcI24igKOgA==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:bSx8bURp7EiLZ4CWIRxvV85dq2rgWe4Gis8DvyNYzWQVW5tmcFc8wos=,iv:ocmEOF05lSmDMMVm9nK7dW9VApXFF+IamDjU7+0zHjw=,tag:zMnRWURrAK9a+KcPssoYQQ==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:5sPzUogT8/KXxCI1yFfqSuipKpuQ,iv:GpLuvimQG2Q7uZs3TEF81jB0PezjSgimtkbx0nbSiI4=,tag:T9XIO3kLNcFmHe9UTWNLdA==,type:str]
    GF_DATABASE_NAME: ENC[AES256_GCM,data:1XMcqEJzkA==,iv:HvSXumiAF+oVaPS3oIBlsgICDmTVugIyS5WyLaujqec=,tag:FBhyCquVL4uP7qXK2OO3rg==,type:str]
    TESLAMATE_DB_PASSWORD: ENC[AES256_GCM,data:An4svzJWqeHk9TDn0CoIuI5bKTjIsF+0qJBPVb1DuV2z+vhoyyWLUkAmcIDHvq4=,iv:5/JMoZdI1Ag64I8jGEDMJkre3nNVwRTgkkM41kP6Izo=,tag:NRqo2T+bydsm3PtP+my0XA==,type:str]
    #ENC[AES256_GCM,data:ajiZrIMKH40ixYJn/H4f2KFESHTFdqWd,iv:/ViBY0+kGyQI8Fk4Npqp/nWKVk/1vGhS05ewPCHRwpo=,tag:mjXoriqDd0i7LrypIIDqcQ==,type:comment]
    #ENC[AES256_GCM,data:seSUGzgKLLGMcFxptAlcjl3S,iv:jLC45YVOe428XDfYu+MF/zmX3DCu9Gv7j84ploC1Nnw=,tag:qr22ruonwZkYtkScycerdA==,type:comment]
    #ENC[AES256_GCM,data:TRFYiUwt2lnC8aRsyfZcDt56ubKgALx9TOBGkjMCluY8kraupC7u,iv:MiMEu1yG+ez/J0lBFyamUCnkfiqrDaW+MUmEz3zDWfU=,tag:AdHJmsp5c935um/mdaIybQ==,type:comment]
    #ENC[AES256_GCM,data:Uya1gcFSrGjglvhxL6LmujwUQxKwPiUnVS5Fzd2CIYvm+f8Uin9/PtUSt2L6LN40cLtxmQU9wD+GChp90HTDeQdx3p4ymyXAN/qyZZg7/JrnAL7S5zcYmGTkUmqgV7NGVbEML+9TtFGQ5OxPfYw=,iv:ePHBHYjl1jWrsR+h4R/Ypo0H01Yv/Qr/4h+IyBiSLC0=,tag:foTDDsLcUQTx6ZOgxHRVTQ==,type:comment]
    #ENC[AES256_GCM,data:t121+seVblbcMdSxDZNCMACo4qWTJko/J4Tg7+ha+ZlFrzJn184=,iv:rcP8n+phBIJUz2gP5q0x/+Y3jT9QSZQ1RYL1DTk2OQk=,tag:XzcPrpgHIgSWejHXS+OUhw==,type:comment]
    #ENC[AES256_GCM,data:Yp4vtWOF9Y258/Jjh6IuI6ADQDryJFJzmVvK9auaXnP2254Kwg==,iv:YA5Wigb7n9uq9C3sIN8NhXplYmi3R+lOng3Ear4atHk=,tag:E7WGzAHYP5zvdjRvqIR8Ug==,type:comment]
    #ENC[AES256_GCM,data:rAX52bOiOY015ush5NV4Dum64tUXpvZ0HeB04sn1jPJghNnY6zezweA=,iv:X9iu7ETcJoxu4jtJeNS/d+PM7ec4qFobGFHp9vvisSU=,tag:d5ezRCi1f9wQvguT8yJdhg==,type:comment]
    #ENC[AES256_GCM,data:RGKutL4St+zk26GcL8ZWaOhBr6Plv9FqgXg74yCGO0LWoDB6LAKhXnzaueS29zFjyd0lHfOr+64ZTQ==,iv:STJ5s27pp37c6CA0S58Wu58QI3Sm8gPnUwh2uPhxxmg=,tag:kBbMI7VlyGqLlbEQmDEB5g==,type:comment]
    #ENC[AES256_GCM,data:v5xqVQ3jjYW7MHS0iq5MSrkMz3Qc1HSJi9EEgEzHaSFwabxJgwFhPTNEgpg=,iv:GVSZ4oFVDVlFTW43iRioKg11QfQqEJmlzK0S/x6LkgQ=,tag:cLj39Y35WW69LR7ro9GxKQ==,type:comment]
    #ENC[AES256_GCM,data:lWkuVUPkox32D0YSEotQDUx3CmTiRhydbzXCw2DdHt8c/lQmU07x3HbkSVFBl8iJC6m+dcyjje6Z+krflcIb40diKzBPOYg1T9LLQ9uNi87boLkRAg==,iv:SJ/F0cOz9GTAOW+qfRr3CL9hPpcBViYuJRWINZnyivo=,tag:J2H87+ONJHVX9aKUJoTlJg==,type:comment]
    #ENC[AES256_GCM,data:KQoMW1XRSkUUJ8hARO/pcy5MfveP6sphPcxTzib1lurXVeSoSaTIFmiD6XNa728D51UTE/voHQmhWlN+7/YInkbS2+4G+uGBDE8HMTfj,iv:igMWUFFadl7jRSDNDLBU6jhLBF4zKlcfCEZaZ3iENC0=,tag:308pn8lWRwYn0XCOd/+acg==,type:comment]
    #ENC[AES256_GCM,data:grS1e5JIH5MV0TlsIRuxSq0q/PODX95INtlD7dMAP5nJW49TthASeL0CY/Vd/YEo4SFz7f8/w0E8hnOBoVJvMwGF+YYJ+KuyhfcsY2a7Zg==,iv:rwF39eksvaSqehN3i6Z2IX3M+tVsKhziR9ZPU6XGK00=,tag:+02b/sRjgn+RuEyOyzmrsA==,type:comment]
    #ENC[AES256_GCM,data:tMiYhr/5/WXxZ5ONbhfLD8UkVB1hVprUEBPOnRgMV9FwpBPx0lNf9KT90xhof2C0s18h6a5A0j92/qJJjENP,iv:QH96uCoVECbyg/j7lXFacqwwPgweVPsXSH3+jD9s2SY=,tag:gPqE4tddcPDo6Lwwqo34IQ==,type:comment]
    #ENC[AES256_GCM,data:q5EDWJfVzL/bdf7H2tigenUMlzzygzGDsifVJ/qw7qGTVdSHlXnxVuzFk2GVsQA8+yw5fQ==,iv:stnBX0aZYzcX5z/bFpImniYN9eCf9X7cjCyDhjMBxBk=,tag:qg6PRRSFFsLZqmfsc7MoSA==,type:comment]
    #ENC[AES256_GCM,data:SW8VDJCS40Pa2GiHHrISZyD7nTf3xSKp25jZKq2apWa1tpG+Vpc+/pVx0tVlTgeK,iv:K0Fu8BGK/4EqN8A7qFABiKIghfb0cpwJsiSWKMGOsI0=,tag:+YXM3C3IHGx2wNIfQADE4A==,type:comment]
    #ENC[AES256_GCM,data:UAfh+WuicZZa5fnsS2NHSCZaFKhrPK8iEdOdmAZWjHEQ4m1V4656,iv:cxt5FXlaVJKBQXS85jGMmOHQXFTIJ7/V2TBHQZJIz9Y=,tag:kEKsQrqlHAwVkA9GWazdgQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T19:19:33Z"
    mac: ENC[AES256_GCM,data:9I6+CNaGYEFb4AW3709RDke2mw8cIXXGAMhIxTNtYUtr2yLW0SbylFwsGo84wCvJCbJEFDwgUWI/Xd1/r6eC1YCHpaWY72OGw2Ov25nhQZVhdALO1r+JNOvXptLQ8IHX9AkFf78g0K+RP59hPpl7P/wC5Mmhwhv2oBSfAmDMZ+k=,iv:gMUj5evgIH2EZXV04SBi/twKV735kwWk2W/w+sgvjHw=,tag:giZDy9Lq4o8R2O/2GcYUKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
