apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    #ENC[AES256_GCM,data:IHyiMMLZ0a8=,iv:nQhbeN9QarKOj13xjWwOH6e12TkQ0dtUZ5Gq1UUm3No=,tag:eYzd4JibK1eXD/WGl9cljw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:hPzE9I8i0g==,iv:if2cMdd8ruVOC0+i5n21NzDOEnmxVcG8ZdaCD07EDNU=,tag:ze0RVEb4BNGaJISqE09qCw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:EmxMgodyXKgPNXw8RPZ6m9WmBSzR,iv:hTSKl37mC3vhEBi693v5XgB/j2AnNXW/JKs/sFiZuhM=,tag:wJirsFeHuKwpkgRXLIbm9w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Sxn7vbGN,iv:t2eC/IV5TFjeJiYdYbv96C6vfkhgnAzWwwSpKPI20yw=,tag:CVT82oEwVvsg111RIAmRpw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:OSpRafLLiYnRqJEwkfgTuePYdxpfOWpcXV4x9ur4IWbZcVvU9fENkA4=,iv:QWUAAFpyv7hB4WKEiVwddahhxqGdtKrOenFXkPd5Nlk=,tag:HFWyhSeSGFuVkWl6h6m3Rg==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:Q4vPF4z8o8qsrrB+uHi67V/o3t2y8mh4N5Ax,iv:EiUWHcTRwH4qsA34QYeK38xdXtxOKibj8gKjM/DN6GU=,tag:ZGUI+f2VL9GH7GNBovBaEA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:DzK1hJMAdGky5G3musE3iJeDOndUjbVEyYIR,iv:RE3t4/qKhGYJZKArVrGAiVyftfjrshxD5z4NpKwgITQ=,tag:0XvgkJG2BVTJ1BxeajSEbQ==,type:str]
    #ENC[AES256_GCM,data:mVGT/50sWu05,iv:UVQqP8qcM5PyZYRrdAzxZf5au34d5Xu60sgHc6YQ+SA=,tag:V3gmqvi1/FEcWuiy2oO4IA==,type:comment]
    GF_DATABASE_USER: ENC[AES256_GCM,data:ZAGpXWnW,iv:c/MiqbD2Y5Z/Ihb1eg9JG1aJzoO8pAqjM0RpqusH6Eg=,tag:c6Qr9b0HhyIJcI24igKOgA==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:bSx8bURp7EiLZ4CWIRxvV85dq2rgWe4Gis8DvyNYzWQVW5tmcFc8wos=,iv:ocmEOF05lSmDMMVm9nK7dW9VApXFF+IamDjU7+0zHjw=,tag:zMnRWURrAK9a+KcPssoYQQ==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:5sPzUogT8/KXxCI1yFfqSuipKpuQ,iv:GpLuvimQG2Q7uZs3TEF81jB0PezjSgimtkbx0nbSiI4=,tag:T9XIO3kLNcFmHe9UTWNLdA==,type:str]
    GF_DATABASE_NAME: ENC[AES256_GCM,data:1XMcqEJzkA==,iv:HvSXumiAF+oVaPS3oIBlsgICDmTVugIyS5WyLaujqec=,tag:FBhyCquVL4uP7qXK2OO3rg==,type:str]
    TESLAMATE_DB_PASSWORD: ENC[AES256_GCM,data:An4svzJWqeHk9TDn0CoIuI5bKTjIsF+0qJBPVb1DuV2z+vhoyyWLUkAmcIDHvq4=,iv:5/JMoZdI1Ag64I8jGEDMJkre3nNVwRTgkkM41kP6Izo=,tag:NRqo2T+bydsm3PtP+my0XA==,type:str]
    #ENC[AES256_GCM,data:wo1b+goM0VAiJpO7Gj8GPp7Sc2femg==,iv:kzwfiDF3DsVgVZ3Hlpw3R1yDJT+8AV1IietqbLec7aE=,tag:L8I1AW261dD22Kn6/Esu/w==,type:comment]
    admin-user: ENC[AES256_GCM,data:LuvAVI8=,iv:vfi8/f0mwjOfbnGVVdwoYKd0FvAgrHfPCeHpGIg1GpI=,tag:NCHoSdx90ksfQSt0DFdkHg==,type:str]
    admin-password: ENC[AES256_GCM,data:xVZ7NyHmJJbHOzGRPrXWkUoepH+uJA==,iv:ycnpf5lpXqOhZRpTns4KXoxB4QG1+SC6xwsI11XbIeY=,tag:8YsE9bvv1GQ0se5+ejkGDA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:y+1mCovpD+P+5iUHWzAr+yB94cx5a5YYF03asBlnVp/G+oho0853X/OaED24B4L98VPyhsZ5qyUQ6l5GY8VdXx0aXjnTChdG,iv:Bw9uNj7o6hfOdv5J2vB9lYTIp8/ShMPz3BxGcdvUxtY=,tag:8a1NYlrWYA8fwztdBiQ91A==,type:str]
    GF_AUTH_GENERIC_OAUTH_ENABLED: ENC[AES256_GCM,data:fgPR0w==,iv:ZiOoXHkdVf4fNbeK8oibTdF0aZjyjBIhmUW8Q0H/qgk=,tag:cqGSqRQ/i00IwAEk7LVzkw==,type:str]
    GF_AUTH_GENERIC_OAUTH_NAME: ENC[AES256_GCM,data:I+G9BzdW2HQ=,iv:fdXxI53jMU3FbEPc96VY5ir6hHGLT2KAzDVUWPL/q9I=,tag:gW+089HnsTVuRa4fRA/suA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:raFYTmH8QA==,iv:awKrzf4BlW1W5uPyv/lipOVmcYxkOAAs7NhIuENhSKQ=,tag:ShJ4+nJMjebtBTBvKZj82g==,type:str]
    GF_AUTH_GENERIC_OAUTH_SCOPES: ENC[AES256_GCM,data:Zao4HuRHwj1+svFrIB2olp/N4eKgYKTUof5E,iv:BpsH8UhYILhqI7jqy/5CG565E5dFGzhXtEMl35Hgzjo=,tag:kDPpF7YPv81lvTV2ClUzvQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_EMPTY_SCOPES: ENC[AES256_GCM,data:i3VLCfY=,iv:S4gYUMc9a3+pnzr5tF+O4eaGp4gbcqtOAgeFspR/2ow=,tag:iYeFH7X/bqvLdTqZKyEnqg==,type:str]
    GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:j+ERGxb/QSBHaHuwkbeV4DY+pT2tG27z5Z3TA7rA8lO9Wu0J8DeQTaLIxWehz20eOUBtUQ==,iv:BSnUXeo3NFiU0k/QsiupdlPUvznSMUVocrJ2OLgibJI=,tag:KIpfrnKvpIJIGrGO+/4m8g==,type:str]
    GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:py5BjbVAJRpFq5cwHrglTFcxbKxTXTROiwFY2FiUVFTFDu2xE27Eqh7xbSg=,iv:B5Fb7Q0mhhmRMPUJYkULGdoQK/13JhkLxS+uFZb6ks8=,tag:+GCr+INzwKohNDKCKNpNiQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:jecjnBkUiuUmA6BpYADtJAjdFJquW5vfVjp7160moy3JVW+JjFhRGfRUveAf6NY=,iv:mdKg4PYzgTABlz+16xxeuPOCpx187LdCnUJEJPNvckw=,tag:7piIDiK3K2sU72Poi3RZuQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: ENC[AES256_GCM,data:KUiQ9//EOu1g//bcFdEkU3gj,iv:n5UDvYylm3lMRXU6L8ZTOeYvBZlP4tIs6WRks0IHWds=,tag:MoM19MwEfXvqBoCjcopqDg==,type:str]
    GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: ENC[AES256_GCM,data:qnlei8G9,iv:pcSrgIKLzzF4PygtKuScDSWC5DrzFQN+3YIRaeTAOWU=,tag:4ziIGsyZa/1g8py4mY854Q==,type:str]
    GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: ENC[AES256_GCM,data:Q5ylNQ==,iv:rmZhRN/xFaPMugATj1HiMFEYpNPP+LHe9U7yfEj+nsM=,tag:fVgGuToR3upv98SlIjhxEQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_USE_PKCE: ENC[AES256_GCM,data:GsB7Pw==,iv:oSK27I1JE/vkKDE9wuqlwztZw6mVncvbjDNo/YcsJ74=,tag:3o5oY5WBn+ffFo7ycAlx6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T22:50:26Z"
    mac: ENC[AES256_GCM,data:BxogH7rlwNJ/dsTMkuju0gpGNK1blU6ScV/+B68ft7Rb5hyamhbGzRICGD9IHdxyuD7xyWnzgrYxJAdWODtnhBoEdkmCXtIE21ZdEUtW2LidELfjvpCVGNI517hB0QkUv25f8jVn+R0eVTuBIv6Y/3PWVQ33xJqx96Ei+3E6/N0=,iv:uJFNQ6dHjd4izqbnd3RIG15gI8GyOKtf6xcn3S04Y/4=,tag:oAQNbhZuOCUNjzNh+Tp4AA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
