# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: esphome-secret
    template:
      data:
        wifi_ssid: "{{ .ESPHOME_WIFI_SSID }}"
        wifi_pwd: "{{ .ESPHOME_WIFI_PASSWORD }}"
        # api_encryption_key: "{{ .ESPHOME_API_ENCRYPTION_KEY }}"
        SERVER_TOKEN: "{{ .SERVER_TOKEN }}"
  dataFrom:
    - extract:
        key: esphome
    - extract:
        key: esphome-fleet-server
