---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
components:
  - ../../components/common
resources:
  - ./scrypted/ks.yaml
  - ./home-assistant/ks.yaml
  - ./matter-server/ks.yaml
  - ./mosquitto/ks.yaml
  - ./zigbee2mqtt/ks.yaml

