---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
components:
  - ../../components/common
  - ../../components/repos/app-template
resources: []
  # - ./scrypted/ks.yaml
  # - ./zigbee2mqtt/ks.yaml
  # - ./home-assistant/ks.yaml
  # - ./mealie/ks.yaml
