apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
stringData:
    EMQX_DASHBOARD__DEFAULT_USERNAME: ENC[AES256_GCM,data:AcRDFy0=,iv:QwIqtgOJQy/dMv0FvCYeQQ080zsMPpWHQCSHfv6jJ68=,tag:7IHCjcRiyaug3r9WPsmD3Q==,type:str]
    EMQX_DASHBOARD__DEFAULT_PASSWORD: ENC[AES256_GCM,data:A8fyh/rD7lVvnI5ZytMNa4ZGbFKmBUmKSfIK8r2zAKQrJYE=,iv:dUKW2OFsCUXvIdqJJbdGVMKmzAWhthBmAF/+sKPl5UI=,tag:5hVjKjjfceOvXiWmy6121g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaFBxdUk1TzA0Q2hreCtx
            NDJvUDlpeW9xR04xRTFSMXhzRlBtV3ZNd21JCnVYSVRaNUxmTWVyZWhYYkpua0Rq
            QkpVN2JiTWdqUzZkWklCMWJMT3BsbzAKLS0tIHJlVTJQM3hMaEQ2T05wWUxzQ2J1
            MkZPMkkxTmN4ZWd2c2pLdHZCZTc2UWMKo16dhqOOWKeHCGmdqBDrzilFIhBvjRJC
            yCWO4SrpwZqhu2SR2swHbTZdJHpH5cpF3FNBhxJEyLgu6hmaYaMGVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T03:54:18Z"
    mac: ENC[AES256_GCM,data:pYqgCKQWlh1zv/tCeaxdSZd8JLhVqcON0M1PSlkiefcNOV/OkO8J8ycq5IvaWInpriqjGb0ON7JCRrjLC/zXJLNvLEC5RDuXoxmPIMRtCXHqUitU75S6BtEl3iws45mDuxuMXPanqBD7x0Rbf6JutxtCGdH/fjWYclpzykvywAI=,iv:Ai/lUvZKwJ+ymUkEm37WOSMwrCJqjkGkeqhRYPySdno=,tag:i36vQF3K9ftGX7WJSVK/Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
