# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:9i5uFBpE4ZalLbDAlq+GCLxm68/WOoHUkUK1ZdaaCOErl0sQ/nG2Kw==,iv:k9xEvuavrW+QCQon3k8FKboNA4+lYd/6U25zzmSKB2I=,tag:5wvFeUi1n5KrJLZd1hWd8Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTnpKMVhHRGVrUlUwU1JL
        ZGd1L2UrbHhMV2h3K29HNDUycUIvcVNyblR3ClBBVXN5UE11ekdOOWU0aU0yUmZk
        VlhVSlQzVFBBVldXTC9PR2J6ek9KWHcKLS0tIHJkZWxDQS8yVFA0dWUyMUhBUEtN
        d2doZkxsa09OS1pzaXEwYmxqdFNPeUkKGeqk3koj34ODwycVddVJswIgXdXPAfTJ
        JZIgfHIC63kOGz3aJn3QjfZ2pWOIbVLeRfULYfV0N+T2dk4aMhlUfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-24T00:58:49Z"
  mac: ENC[AES256_GCM,data:+bTy+IVnlEAKmsif7xc3JcNRwl8+UvYsLfIG8L6p0ZB+40rZ+N9zxjuH1H435ZY8EkjnP3rH+qWz8R8d4V/lFHLixyV6MKTs8ZYT3BQHklQlqgk9D6sxnsHGpMZIZ7yTHjWInjCRYyEE3yQD07hgry+Ez5wDJIlZuHLaNF0Gpgo=,iv:CZScN1vlWorMgdFk53xyEBCcqFrqHoCrEG5e53hmO4U=,tag:5EAvy7W4VnMBjXcVlxEr7w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
