---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: immich-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: &dbHost immich-rw.media.svc.cluster.local
        INIT_POSTGRES_DBNAME: &dbName immich
        INIT_POSTGRES_USER: &dbUser "{{ .IMMICH_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .IMMICH_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER_FLAGS: "-s"
        # App
        DB_DATABASE_NAME:  *dbName
        DB_HOSTNAME: *dbHost
        DB_USERNAME:  *dbUser
        DB_PASSWORD: *dbPass
        JWT_SECRET: "{{ .JWT_SECRET }}"

  dataFrom:
    - extract:
        key: /cloudnative-pg
    - extract:
        key: /immich
