apiVersion: v1
kind: Secret
metadata:
    name: gatus-secret
stringData:
    #ENC[AES256_GCM,data:PkC8nkFdiX0=,iv:+gBmNYM3Y2BnmoZ/9BzcEd6wMtP+FmmIPKgOMrSkhuc=,tag:JOqy3jS3ekcLyYR04SXgcQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:M5GoAkQ=,iv:gfYgqDkebKHDWZW8yVqjXwHcsVg/2GmFVCJ3LXOnLsc=,tag:7c+Kf37gRQnaFrDUHTPJjg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:y5W+Ax+nqVwDFmnOuyoFbSvh4LjE,iv:nhWB4lsQwdqlRtSgnEod/JIDgo2i6FfdnyFAEFX2nlc=,tag:rS303kGxPqJCL3wGNzml2w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:5RCQHZ8=,iv:nWbZBClz8FCQttBmFu8dMGMnCOiSPGpXPznrO/L+mWU=,tag:Qk6XKFVtLKiHxBftPQxJiw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:4mt9Z+HfmVKqZzbAg5rXoixFJ2JX32k0yheJo43xmZXXrLWuqIRFnhm4RyXT0IeDj5nYdOyyWvI4HngWEqC5qiurE6Eb4t58,iv:v0SVsVSgobw+KyiJD8zV65TpC353mx+fuDBaT/FdVzo=,tag:UcbDMgI2py3gzTkh0u+QkQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:VnhamNAtUUaR/5jXSsQFYzB3V07/hTvcazs0,iv:6XCSrtP8cX5AZc0jaekViGJghrvfGC961Yr5XOuD3sU=,tag:CI39BQ5Z9sXWumonxR8KMQ==,type:str]
    #ENC[AES256_GCM,data:w0nDgxFhkW8QQLoGmw==,iv:3e/cekxp/rFxd0oh5mDh5IH657HYYyAU0A6mY4z4O6U=,tag:N2x8E/4U9KGZMvwSsrwUjg==,type:comment]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:nzhlVE3m1DawYw6u1cSwlNiWeqrDfvKCD+feMbi1,iv:ApbMY2S3jcOumvOTk5hmstx4Wy+abPWN00o5R8eulJo=,tag:sBKbC4g9zKnxWHmVwX5WLQ==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:5+PZQ97g2qqcjdJHUDlg+a4AU+GMxgbonvSla3bp,iv:smVGUFmmQrg9bKFZRH9rB/PfWTgk9J/UxWIvgP0H1xQ=,tag:Vv/+yfUkNKIyxDmR+9V1Gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUVA0Q2lMVm0zMDQ5bEpv
            OEhQVXZWMzQrblU2M05oNnRvV0Y3aUM3MmhJClJ0MkVTUHozNUVmakdUczE3emZL
            ZEV6aFVQMTdrWVVSQUpKTmNWMjZGQVUKLS0tIHBheDhCSk1NVDQ3R1RMNzRxUlZ6
            Tk14d0lzbmNkeDV4R012RG8xdHV6SGsK3hVHZyh7H/h2Qjyt/0sOqH7i9LXgvvrp
            cOnVuJ1F9w3Dz6Rnn4Ykvvvtt7eX0ZkxiUdouddBPGLn1URppywadQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-25T19:45:01Z"
    mac: ENC[AES256_GCM,data:09H/z0P4lIoC4xBhAImX+NAl12+M/JhF1Im43Y4okhP6Zf9Kamb9pyrKvWMeVcKqjqmhqYNMA4JyL3GHVPkbuq8gidOY1FeHNzwjV++D97D9lAnwy5UZFi2x7TfnOg4RmaPnErth3EIMzQyAgDDTvdsNvZX0IvveivVj5gJukrg=,iv:iJeFLeGQPQyxZgJzvMMlRqGLyVQIihX7GEx+x11a9bI=,tag:rvokLpbWFed51odn2/T0pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
