apiVersion: v1
kind: Secret
metadata:
    name: teslamate-secret
stringData:
    MQTT_USERNAME: ENC[AES256_GCM,data:kYwEzOE=,iv:1qnri7q5GgFH4WFsxczednzLbR0SiPDQCMAkd9TFogo=,tag:BHxggEKyLQVnQjzE2vAY2Q==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:kMtJXfeeH2Xa4ilwoJVH4ThYWLrKnDhvoPsBiiyAqxk=,iv:qa2D/oxJP2NrGDGTmxXenANPqpNnm1E9QAYQT3S/uVo=,tag:FxO4mFeAUikWvI4zbquDKQ==,type:str]
    DATABASE_PASS: ENC[AES256_GCM,data:3TsDe9kE6UisWcyNwJPHGkPaCFTlW8OSY3X9XGTxDy81Y3WTCW5PuZfotYU6pYo=,iv:4GsFoNbflADCGHM7fPHGLfHrMGxzyxqVcceVUzV5DSU=,tag:PEPfGja5BIW6doC2hcSV8g==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:7BF3VKM=,iv:in0IB3gcrZ5I7CZHJvfNOZxvCZ4c5vMZ82wWuKboVAQ=,tag:9EI76gs5iOGn3s7dHQM8eA==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:tpWthClZWwody2WLbnwGNNnkkGpsAHgafnFfZbOlkOHOO2c39e3rU6Er,iv:pKvOJO5hZ3QM6aHNN+i8OedwtvJ96886SBXsFmN72dA=,tag:hMtxQLb2S6xx09ehpv7Sag==,type:str]
    #ENC[AES256_GCM,data:jbnqFJc/CHECSpOJ9Mw=,iv:ObXr+ddMmr35u5UF1QlPmSZI6VDvZI/hDheicpqr8XQ=,tag:5y1erCCxdt9Bmkbi2Zsslw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:2utxwZ6YJLWJ,iv:ZDvpoCunGux5WPejux2n/Bi4VYqhkWPmw1Rmq1d8xqA=,tag:c2hQHhfE4S4//nHGVVCcqw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:y5W+Ax+nqVwDFmnOuyoFbSvh4LjE,iv:nhWB4lsQwdqlRtSgnEod/JIDgo2i6FfdnyFAEFX2nlc=,tag:rS303kGxPqJCL3wGNzml2w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:yebmxPk=,iv:kgTbcDNj6sGNyATblDzF1+FOjtvuw25Mo1jgh6wcpMc=,tag:Qy9x8SmVNvKOF0Fxcr4Qig==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Z7Hdf+scnRzwbClnPIB1xSzGNdhJ97AZP7Q+nfXkGfQO2GXR4mu05KuiN4mz70s=,iv:U6nP8pQyplQgqUP4ZbJcbN1WCp16cWfsk5HnhGXbW2Y=,tag:xY0VrR7GJ+PozA0C293q6A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:VnhamNAtUUaR/5jXSsQFYzB3V07/hTvcazs0,iv:6XCSrtP8cX5AZc0jaekViGJghrvfGC961Yr5XOuD3sU=,tag:CI39BQ5Z9sXWumonxR8KMQ==,type:str]
    INIT_POSTGRES_SUPER_USER: ENC[AES256_GCM,data:jlpc8qhrZxLErVdCl4HMkWglo44Yk3Z8ipb3,iv:czQOkxfz73H4kCF67PHF+RFC9n7yixiHYs5etFinObk=,tag:BoLlWubTk97ebZTokK1Wfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUVA0Q2lMVm0zMDQ5bEpv
            OEhQVXZWMzQrblU2M05oNnRvV0Y3aUM3MmhJClJ0MkVTUHozNUVmakdUczE3emZL
            ZEV6aFVQMTdrWVVSQUpKTmNWMjZGQVUKLS0tIHBheDhCSk1NVDQ3R1RMNzRxUlZ6
            Tk14d0lzbmNkeDV4R012RG8xdHV6SGsK3hVHZyh7H/h2Qjyt/0sOqH7i9LXgvvrp
            cOnVuJ1F9w3Dz6Rnn4Ykvvvtt7eX0ZkxiUdouddBPGLn1URppywadQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T22:30:21Z"
    mac: ENC[AES256_GCM,data:WEEl0a47j0hKOKpAYH3xtTQ9ItVgC04bkylZib2fFqo6ZzY975AXvE6sMAdxGJZ/JkzN6Xjb005U5jfSI5/jRO8Saq0iOg32bnVWcItGoHj7Wap3WoCheMyrh+7Odj3vDAknDuZzBlcpFp22MsywWlOMWg/seLoB8GxpRl6lO6M=,iv:CFDlCqVY1TevFk1mzTfFWa8Fjj7hNAUHNrQpl/geQHY=,tag:SiG93ECJCvtIGMNa7ZyTDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
