---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: prowlarr-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: &dbHost postgres17-rw.dbms.svc.cluster.local
        INIT_POSTGRES_DBNAME: prowlarr_main prowlarr_log
        INIT_POSTGRES_USER: &dbUser "{{ .PROWLARR_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .PROWLARR_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        # App
        PROWLARR__AUTH__APIKEY: "{{ .PROWLARR_API_KEY }}"
        PROWLARR__POSTGRES__HOST: *dbHost
        PROWLARR__POSTGRES__PORT: "5432"
        PROWLARR__POSTGRES__USER: *dbUser
        PROWLARR__POSTGRES__PASSWORD: *dbPass
        PROWLARR__POSTGRES__MAINDB: prowlarr_main
        PROWLARR__POSTGRES__LOGDB: prowlarr_log

  dataFrom:
    - extract:
        key: /prowlarr
    - extract:
        key: /cloudnative-pg
