apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:KnwwFPNbzfOuX45tiXHJf0QHsnLYUG0ymsT1aCfxc6CldDtMWCEcgPHnMvB6QxA29Hgx3P09J7kjV3uBszVJlAtHZkHDHCwMlV2fDn2i3ud/o0wplIwwiUDLzzQcpquvhmzfUqD9ryLYzIH+3R+Nu5bEdcsauvWZyUwf779Q45o+EiB/uiQf1+R+ZmKauocTognvjk+oIIx4bnNNKr257RlMjNivBDS/cdJPBy2iqppSdCJh,iv:ylGKIM0B5RHbtT3iRx7XCkGBDTFnFokJ3lceigNBHEA=,tag:l5sMYPpjbljjPF1OjeTJJA==,type:str]
sops:
  age:
    - recipient: age1qez67uw84ygk7q39yr3ht5nxzr32c8pf2zxc4znvn8lvtx3kqgmqv5wgu5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTXEvWlVsVGpSQ2dmdWYv
        N2Y2YUdTUEEvR2RVTG5yUlI1L0dEcDJBS3gwCkJ1ZXNJRWZET2cxYXF5MUJTV1hH
        bXphZjJMNmhIUnpSQllKV1NtS3BsT3cKLS0tIDlaZWdaOGszaDl1ekh4ZGlkQWIz
        bEFSSTdHWFhMMEJ2OXM4MHhGWXRzSXMK8cLW8Dehs2KFaE+eHWNfuPxuhxULLZJP
        DNi4JrjYxcMNcXWn/Ugh8JPYHW1hnkMwnd7rwvVdjYSneo2s7JdKTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T09:09:52Z"
  mac: ENC[AES256_GCM,data:5Ep1e3Qhz+Z/GHW42YTDjrj6JZIvz0ESUlw8Wm8Bz5iFN6ZqpkKS6jNn3rynmHXHjIGwU3vsmcn1muBC/HlsT4D9YZCu6959Dm3KCAlL+GRCchVOfPp9qyI9PnEv5Pfec13cVR3buPHgntMIK2pwO3krzBQv4KhtCXU9x7VCC5A=,iv:loRWToEhCDxE5MCizVNePAJzfAcH4htbf4Ale2v7Epc=,tag:oJn2VSQAnNFpnXtzXO+R2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
