apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:5apcRWoya2PY0pvqYP6yf9Ey9wj1aiJwDAeZ3z1ZlnXs8H0YuJ6uX5jkjY0PQApd8RRWfdRehfO3hjKLyRU7UeFY265O3N9/m1enrlShPaox+wQgmnlWI59CcPJKRf39MGW7aKHlgV1wvCvmC2O2lWgqR6iwVaoVhdho3HsV/t94ekZlYhVErWW8shBwNW/sn6WTkxg6k624L114wdjhLt7hU+u7Ig83X3H8UdlHcEewnsv3,iv:v9moCQxPY8fft7cs3cCsz/POToXqzN64JatA61d6kkA=,tag:VhE4WJryYm+bEetGYcHJgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRVNqWkFKemF6MlVZNWhq
            TW9Kb2pram5NUEc4alp2R3ZTWUlvbWxUZ0JFCmw3VjRFYzdPZThRQitpb1drMFY1
            TS9rM0dSVU96UTgzMjVnZ2pqSE16UFkKLS0tIEk0RExESjBlOTBsczhkS0pZdWtZ
            K2dWd29MTjVBMW8rMkRBekxFdzRVTUkKAOuF2xz6KktntmNr0RaD6VM2Qz5qGkNB
            /fYBxQ+TPJfyoA4Mxym5BOtenp0jVFjIAF84vtJXKt+CgJCCFcWw5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T22:44:02Z"
    mac: ENC[AES256_GCM,data:bYNcBKs+pyPVW3jSovU9bV6HTXy2F/5kisfpvaErlD8chwd2ZF/sWRy/XaG1hI6gJ9j2V2Ue2CvG3FOMCH6WnJJ/qglrU+lN84eWxCUwa0f7XGwAvjPLcATtqwKVc1s9kXETlcrl4wBzoa8LaNESISNTurIs/sroVbHhqL3fjIo=,iv:rE0iXM5isMXkVAFTMzJLSUHAm0WRVE+QDsuznbCMUaM=,tag:ZrSP/Hj8aVP7maLojC8keQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
