# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:ZHsNf0M5teIGNfd5cWazs9EQaebpeitQ9r2SWfy/nHniManOTXjE5xJhL8kF89SyyCiyA6uXevRWq+A5u+vHaBh3SHbjcFOxPI1ZU7A+OwFzSOb9S3gVnMz0my9V25A5k+QXKuj5RzvPpq3jcL8qvLOdy9HhX9qong1hykGOgwNfojnQOTvfzN9A/X9+i3Q/HU9lDFEtfyUsuvURVtwKvocHajJwW0QEcWJmO8T1UN1Rl58H,iv:oZnqnvxDPoWEGPVv5MqQLPQ1flERhhCUf68DG65HDt8=,tag:Fr2xT5AazthUlIdTM5Niuw==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:IUN24YRxta3hEs99YH6Q06b61TK1tLDAm4YLsbq5om3PyxPD,iv:fnnVghzcxCnFTV2WHFLujXnfB4P8xXvZRVhwwuL/re8=,tag:992tWUBnD56Y45efeQ9cXQ==,type:str]
sops:
    age:
        - recipient: age1pj705hhyh9u9dwxsj2ak9l49tv3nqqlfxj4zxsj0wkrpnlywdvzqf7vz08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaWpUNkFsL3hLOWRkcWV4
            Y3kxVi84bFdvNlNmZzMrNzAvUGk2S05Xa0FFCktleUhHNHllbGZidjdLK25JaldZ
            QTAyZExpcVErd3FBcUN1a0JnRkdJRWMKLS0tIFFJcDc0cXNZcm1qaU9DaGlsZ095
            d2pjSGRNZHZKQmJNZzlpK1M4VSs2TE0KjiXrxHCGp+kd7K5mdFHHQLt9XW2BGoMO
            EUFvLnRNlvwzphu4KkQ/OFSyfEfWzIMVLD7eCvBnHq+/Vce7jApk7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T05:07:14Z"
    mac: ENC[AES256_GCM,data:tVmNoycFAN/uLuiRR+BQ2BchHnqs+APz+RL3xQU5mCRem807vy6CCFmU/YgRXkPJFTBHF4DAexv3y0z1spzUiIzSmIHQEubGztKHrjXbnqVJxrYRM5+YbttcIiM+KrOph2NU98mQkVNsBMCwSqxech3d+KYFC4JwR2SBARZCAZ0=,iv:1bQheE/JgsoQXqhtaKcpWxPDGzLoek6k0i8MhOKwLZY=,tag:n58CkMcgqy4SLk+/FQqCUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
