---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beets-audible
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: beets-audible-secret
    template:
      engineVersion: v2
      data:
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
  dataFrom:
    - extract:
        key: /plex
