---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app beets-audible
spec:
  chartRef:
    kind: OCIRepository
    name: audiobook
  interval: 30m
  values:
    controllers:
      beets-audible:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          setup-dirs:
            image:
              repository: busybox
              tag: 1.37.0@sha256:6b6411e10ab162cfe7e71dcb5253c7d2b6180b37456687e309323a1490cea777
            command:
              - /bin/sh
              - -c
              - |
                mkdir -p /config/audible
                touch /config/.initialized
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
        containers:
          app:
            image:
              repository: ghcr.io/aedot/beets-audible
              tag: 2.5.1@sha256:c6ad177ee25f7482722a6021b32c13d63f00770d982cc01d6f6dc4c398f1aa6c
            env:
              TZ: America/Los_Angeles
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 512Mi
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [65536]
    persistence:
      config-file:
        type: configMap
        name: beets-audible-config
        advancedMounts:
          beets-audible:
            app:
              - path: /tmp/config/config.yaml
                subPath: config.yaml
                readOnly: true
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config
      audiobooks:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/media/audiobooks
        globalMounts:
          - path: /audiobooks
      input:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/m4b-tool/untagged
        globalMounts:
          - path: /input
