---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app beets-audible
spec:
  chartRef:
    kind: OCIRepository
    name: audiobook
  interval: 30m
  values:
    controllers:
      beets-audible:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          setup-dirs:
            image:
              repository: busybox
              tag: 1.37.0@sha256:e3652a00a2fabd16ce889f0aa32c38eec347b997e73bd09e69c962ec7f8732ee
            command:
              - /bin/sh
              - -c
              - |
                mkdir -p /config/audible
                touch /config/.initialized
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
        containers:
          app:
            image:
              repository: ghcr.io/aedot/beets-audible
              tag: 2.5.1@sha256:62c87dce2b6a0cad827c7e53ec6be8da572aac8c312ee02fe123921e12b1c025
            env:
              TZ: America/Los_Angeles
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 512Mi
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [65536]
    persistence:
      config-file:
        type: configMap
        name: beets-audible-config
        advancedMounts:
          beets-audible:
            app:
              - path: /tmp/config/config.yaml
                subPath: config.yaml
                readOnly: true
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config
      audiobooks:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/media/audiobooks
        globalMounts:
          - path: /audiobooks
      input:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/soundbind/untagged
        globalMounts:
          - path: /input
