---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: postgres
        group: guarded
        url: tcp://postgres17-rw.dbms.svc.cluster.local:5432
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
