---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: r2
spec:
  configuration:
    data:
      compression: bzip2
    destinationPath: s3://cnpg-6g2d33/
    endpointURL: https://c04ec44babd84f729574b781430d8417.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cloudnative-pg-secret
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: bzip2
      maxParallel: 8
  retentionPolicy: 30d
