---
apiVersion: v1
kind: Service
metadata:
  labels:
    cnpg.io/cluster: postgres
  name: postgres-rw-external
  annotations:
    io.cilium/lb-ipam-ips: 10.0.20.38
spec:
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    cnpg.io/instanceRole: primary
