---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autom4b
spec:
  chartRef:
    kind: OCIRepository
    name: audiobook
  interval: 30m
  values:
    controllers:
      autom4b:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: seanap/auto-m4b
              tag: latest@sha256:0a8c10ab6b983fcd63e5bb408244f00efc728b86882b9e5e48ceb5e7fe299d64
            env:
              PUID: 1000
              PGID: 1000
              SLEEPTIME: 5m
              MAKE_BACKUP: Y
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 361Mi
              limits:
                memory: 512Mi
    persistence:
      temp:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/autom4b
        globalMounts:
          - path: /temp
      tmpfs:
        type: emptyDir
        advancedMounts:
          autom4b:
            app:
              - path: /config
