---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted

components:
  - ../../components/sops
  - ../../components/namespace

resources:
  - ./actual/ks.yaml
  - ./baby-tracker/ks.yaml
  - ./bambuddy/ks.yaml
  - ./lubelog/ks.yaml
  # - ./sparkyfitness/ks.yaml
  - ./teslamate/ks.yaml
