---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: m4b-tool
spec:
  components:
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync
  interval: 1h
  path: ./kubernetes/apps/media/audiobook/m4b-tool
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: m4b-tool
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: beets-audible
spec:
  components:
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync
  interval: 30m
  path: ./kubernetes/apps/media/audiobook/beets-audible
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: beets-audible
      VOLSYNC_CAPACITY: 1Gi


