---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-postgres"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: "${APP}-postgres-secret"
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        #db
        # username: "${APP}"
        # password: "{{ .${APP}_postgres_password }}"
        # database: "${APP}"
        # host: "${APP}-postgres-rw"
        # ro_host: "${APP}-postgres-ro"
        # port: "5432"
        # uri: postgresql://${APP}:{{ .${APP}_postgres_password }}@${APP}-postgres-rw:5432/${APP}
        # dsn: "host=${APP}-postgres-rw port=5432 user=${APP} password={{ .${APP}_postgres_password }} dbname=${APP} sslmode=disable"
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: cnpg-users
