---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./cluster.yaml
  - ./externalsecret.yaml
  - ./jobs/backup.cronjob.yaml
  - ./jobs/restore.cronjob.yaml
  - ./scheduledbackup.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: not-used
      spec:
        dependsOn:
          - name: cnpg-operator
            namespace: dbms
