---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cloudflare-r2
spec:
  configuration:
    data:
      compression: bzip2
    destinationPath: s3://postgresql
    endpointURL: https://${CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: ${APP}-postgres-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: ${APP}-postgres-secret
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: bzip2
  retentionPolicy: 7d
