---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: nas
spec:
  allowedNamespaces:
    all: true
  backend:
    filesystem:
      path: /repo
      volume:
        nfs:
          server: yemoja.internal
          path: /mnt/alaafin/k8s/kopiur
  credentialProjection:
    allowed: true
  encryption:
    passwordSecretRef:
      name: kopiur-nas-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD
  moverDefaults:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    ttlSecondsAfterFinished: 300
  scheduleDefaults:
    timezone: America/Los_Angeles
