apiVersion: v1
kind: Service
metadata:
  name: traefik-external-metrics
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: traefik-external-network
    app.kubernetes.io/name: traefik
  type: ClusterIP
