---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app soundbind
spec:
  chartRef:
    kind: OCIRepository
    name: audiobook
  interval: 30m
  values:
    controllers:
      soundbind:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/aedot/soundbind
              tag: v1.0.0@sha256-33a6b6100fa674fa62c7fa6cb3283f1aa2833b219bd1978ebf84c95721421b45
            env:
              PUID: 1000
              PGID: 1000
              LOG_LEVEL: INFO
              TZ: America/Los_Angeles
              WATCH_INTERVAL: 10m
              WEB_UI_PORT: &port 8080
              SLEEPTIME: 5m
              MAKE_BACKUP: Y
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 361Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      temp:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/autom4b
        globalMounts:
          - path: /temp
      tmpfs:
        type: emptyDir
        advancedMounts:
          soundbind:
            app:
              - path: /config
