---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: sonarr-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: &dbHost postgres17-rw.dbms.svc.cluster.local
        INIT_POSTGRES_DBNAME: sonarr_main sonarr_log
        INIT_POSTGRES_USER: &dbUser "{{ .SONARR_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .SONARR_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        # App
        SONARR__AUTH__APIKEY: "{{ .SONARR_API_KEY }}"
        SONARR__POSTGRES__HOST: *dbHost
        SONARR__POSTGRES__PORT: "5432"
        SONARR__POSTGRES__USER: *dbUser
        SONARR__POSTGRES__PASSWORD: *dbPass
        SONARR__POSTGRES__MAINDB: sonarr_main
        SONARR__POSTGRES__LOGDB: sonarr_log

  dataFrom:
    - extract:
        key: /sonarr
    - extract:
        key: /cloudnative-pg
