# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: tracearr-secret
    template:
      data:
        JWT_SECRET: "{{ .TRACEARR_JWT_SECRET }}"
        ENCRYPTION_KEY: "{{ .TRACEARR_ENCRYPTION_KEY }}"
        COOKIE_SECRET: "{{ .TRACEARR_COOKIE_SECRET }}"
        BETTER_AUTH_SECRET: "{{ .TRACEARR_BETTER_AUTH_SECRET }}"
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
  dataFrom:
    - extract:
        key: tracearr
    - extract:
        key: maxmind
