---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: postgres-backup-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        POSTGRES_HOST: postgres-ro.dbms.svc.cluster.local
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PORT: "5432"
  dataFrom:
    - extract:
        key: /cloudnative-pg
