---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./chartdb/ks.yaml
