# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readmeabook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: readmeabook-secret
    template:
      data:
        JWT_SECRET: "{{ .READMEABOOK_JWT_SECRET }}"
  dataFrom:
    - extract:
        key: readmeabook
