---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readmeabook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: readmeabook-secret
    template:
      data:
        # App
        POSTGRES_DB: "${APP}"
        DB_HOSTNAME: ${CNPG_NAME:=pgsql-cluster}-rw.dbms.svc.cluster.local
        DB_PORT: "5432"
        POSTGRES_USER: "${APP}"
        POSTGRES_PASSWORD: "{{ .${APP}_postgres_password }}"
        DATABASE_URL: "postgresql://${APP}:{{ .${APP}_postgres_password }}@${CNPG_NAME:=pgsql-cluster}-rw.dbms.svc.cluster.local:5432/${APP}"
        JWT_SECRET: "{{ .READMEABOOK_JWT_SECRET }}"
  dataFrom:
    - extract:
        key: readmeabook
    - extract:
        key: cnpg-users
