---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app docmost
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: docmost-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
        INIT_POSTGRES_DBNAME: docmost
        INIT_POSTGRES_USER: "{{ .DOCMOST_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .DOCMOST_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App
        DATABASE_URL: "postgres://{{ .DOCMOST_POSTGRES_USER }}:{{ .DOCMOST_POSTGRES_PASSWORD }}@{{ .POSTGRES_HOST }}/docmost?sslmode=disable"
        APP_SECRET: "{{ .DOCMOST_APP_SECRET }}"
        # Smtp
        MAIL_DRIVER: smtp
        SMTP_HOST: "{{ .SMTP_HOST }}"
        SMTP_PORT: "587"
        MAIL_FROM_NAME: Docmost Admin
        MAIL_FROM_ADDRESS: notification@${SECRET_DOMAIN}
        SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        SMTP_SECURE: "false"

  dataFrom:
    - extract:
        key: /docmost
    - extract:
        key: /cloudnative-pg
    - extract:
        key: /generic
