apiVersion: v1
kind: Secret
metadata:
    name: docmost-secret
stringData:
    #ENC[AES256_GCM,data:rs3kQw==,iv:KIJ3KQxO1DPyZ974W94yswzox+2eJzyf4JntdhLZOnI=,tag:xZQKVV5jZKxsLICCQqaEdQ==,type:comment]
    APP_SECRET: ENC[AES256_GCM,data:7ahe/vnEOkZs3QxE18MVGHagrMgCb9wRByTJpls8KbA=,iv:wqBaMFAHwgVEQ0oqk8ScqzL+0wRyc8l1L0qzLRzNjk4=,tag:r38ljhJIkeTmczLoOWv3bw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:dNjckYKqojmn6OK5zY2d3W9N2tiwkoHvdPSA4c7cgC4Pnmdb0aDvEg/l53OJjxsuRxNWUQSzRTuo3+E1IxRobj8fQKy1eHltI1vgqFXsSZgTk+nbQJLjz+MaAzhJKymMiuOxxzD3ViJY/7ruiqG5/J54Pk3GrC0jU0c=,iv:kilg0k6WqNlEqSdSTgG1ZeJe8F1ygLxM4n2IZvUcKrU=,tag:DI5z27NsARIgI/5zaWcvVA==,type:str]
    #ENC[AES256_GCM,data:juYw60K2cLka9YuZS/A=,iv:P90bIQsov2URUz04STu2FhIfViu9JC/nq9LtO0prYss=,tag:FRHVkAN++1bMG0rdHOR9OA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:BpciCzbaog==,iv:8krhc2wpeIReO8G4sjzewp4iRfUzo5XQYXo8t1t+8cU=,tag:vlFdaOYaSgg6n5qpBKbuow==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:EmxMgodyXKgPNXw8RPZ6m9WmBSzR,iv:hTSKl37mC3vhEBi693v5XgB/j2AnNXW/JKs/sFiZuhM=,tag:wJirsFeHuKwpkgRXLIbm9w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:LYUdmA==,iv:f5EvhK0nbP7vX6865AvUtoqu65CE4v1vIQJCLf9VYJM=,tag:RYXp8FZ4FH9dsNt+qQJI0w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:FfhvcBjV5V2709dBgB2NbTd4upyk6bNp0/dCAAe16bddvYggChQI7BZlWMGS,iv:4s++D96PnuBQG4UwxDgriS70ME/o2V2v3i4CVnnLz7s=,tag:pParIoewocjoMtz3g2YDrA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:DzK1hJMAdGky5G3musE3iJeDOndUjbVEyYIR,iv:RE3t4/qKhGYJZKArVrGAiVyftfjrshxD5z4NpKwgITQ=,tag:0XvgkJG2BVTJ1BxeajSEbQ==,type:str]
    #ENC[AES256_GCM,data:i8wEDvg=,iv:sJTJMx574ojGZeaDHXDlofeZhttvEqqt35ddJm+h4uw=,tag:j4MWXylYFhaC3mtsSf2MKw==,type:comment]
    MAIL_DRIVER: ENC[AES256_GCM,data:LWfOnw==,iv:ViDRyNKVF1KW7325aZIv1NuiP4xTzjVZfwE2RVN1kds=,tag:ZlxiGEfPFIYUpDbMCjztVg==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:N/SCzuXW4sWp99HNH57sH0lT8FEMEQ==,iv:YGcGxGC9xMbIPqgVbr//qwcGQl02SxT8V34BRWXYBps=,tag:j6KS16A4yWNkEHKTS96pBg==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:/19U,iv:9+UrvFcqYLHQmq322ZhtPMOZTdjYTLLaBqU3DaFL3lc=,tag:n7SHXNrQEgHBKw9V0GjwUQ==,type:str]
    MAIL_FROM_NAMEE: ENC[AES256_GCM,data:Zw9UwX6qEB6ysLkqng==,iv:0L00FhmeFQk0UprnRnrlJWz63UO9X83rkDw4Kv0OjVA=,tag:YMOSx02HN5zXxwLNG5jD3g==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:USSlP4p8O3WqHlDj2qUVqU/saaGqfDnO,iv:OZXTs+hAAAgdHmQVLJncnjrffsQ0xpm3dpzijYFU1UE=,tag:rKoIhPrdWge4l5QP3Lu2Yw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:OMnPAcYJslaqqiwyYLybZTrNToZGIvU=,iv:+9V0QCOaKG9E4nGoZEj4xNTsI9KGp58cbXFT13DMkHw=,tag:RThoDuhV78OKro5y4VvTkA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:zGLj7EpXZAY7Vob+ms48UnWIijJg2k0=,iv:+oX3aKXOOA9YGgEhjiug9zus0bH3ju2rqR6dg9bTFGY=,tag:w7MOKTa4w44OhORG2m/HRQ==,type:str]
    SMTP_SECURE: ENC[AES256_GCM,data:MZ1DZYQ=,iv:IFeVry4iBihiX4FGhYyCsLzAVcXeC8X3Rri32BoG86o=,tag:XZxM3YxWUVqBvnhESosHgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T23:04:32Z"
    mac: ENC[AES256_GCM,data:mtUXmyQtZ2/dhXzZC+GxQQ+CAmq+yhO2CVzQrVg8q/EXE8/gojKmmPx/Ke2dfl9ySmVloz/UOa13RpNYy3dziclIQJLFGCawt55aJ9vQQa83zJOw9d7eLAr2JsX6k663mYX8Dzx6+iVpQvR9EQ9ioZSGF2jJulAcsGlL0XFxlv8=,iv:y57vXyYg2Zh5VY7J6fUrA5e2c5t10Bz8qSaGemiY884=,tag:8TJGCvSDQTJDJz5PZVKhkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
