---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: self-hosted
components:
  - ../../components/common
  - ../../components/repos/app-template
resources: []
  # - ./actual/ks.yaml
  # - ./it-tools/ks.yaml
  # - ./lubelog/ks.yaml
  # - ./gramps/ks.yaml # Remove due to corrupted database
