---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  interval: 1h
  values:
    fullnameOverride: victoria-logs
    retentionPeriod: 14d
    server:
      persistentVolume:
        enabled: true
        storageClassName: longhorn
        size: 20Gi
      serviceMonitor:
        enabled: true
      route:
        enabled: true
        hostnames:
          - logs.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
    dashboards:
      enabled: true
      labels:
        grafana_dashboard: "1"
