---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app scrypted
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
    controllers:
      scrypted:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          # annotations:
          #   k8s.v1.cni.cncf.io/networks: |
          #     [{
          #       "name":"multus-iot",
          #       "namespace": "network",
          #       "ips": ["10.0.101.14/24"],
          #       "mac": "64:16:7f:38:60:01"
          #     }]
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109

        containers:
          app:
            env:
              SCRYPTED_INSECURE_PORT: &port 80
            image:
              repository: ghcr.io/koush/scrypted
              tag: v0.123.58-jammy-full@sha256:d84d2a8cc897e3ddd0635aecb681900f551e3f5bf702200df4b92e4014bc22b3
            command: ["npm"]
            args:
              - "--prefix"
              - "/server"
              - "exec"
              - "scrypted-serve"
            resources:
              limits:
                gpu.intel.com/i915: 1
                memory: 8Gi
              requests:
                cpu: 100m
            securityContext:
              privileged: true

    service:
      app:
        controller: *app
        type: LoadBalancer
        LoadBalancerIP: 10.0.20.33
        annotations:
          io.cilium/lbipam-layer2: "true"
        ports:
          http:
            port: *port
            primary: true
          rebroadcast:
            port: 34135

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          scrypted:
            app:
              - path: /server/volume
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
      cache-npm:
        type: emptyDir
        globalMounts:
          - path: /.npm
      recs:
        type: nfs
        server: shango.internal
        path: /mnt/user/k8s/scrypted
        globalMounts:
          - path: /recs
