---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lubelog
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      lubelog:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17@sha256:e0c87ce7df39d06b93f27cf2cc6a056611f13faaa88cc07ab4dc8bf7a85d0b11
            envFrom: &envFrom
              - secretRef:
                  name: lubelog-secret
        containers:
          app:
            image:
              repository: ghcr.io/hargata/lubelogger
              tag: v1.4.9
            env:
              TZ: America/Los_Angeles
              LC_ALL: lt_LT.UTF-8
            envFrom: *envFrom
            resources:
              requests:
                cpu: 10m
                memory: 80M
              limits:
                memory: 256M
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        # runAsNonRoot: true
        # runAsUser: 1000
        # runAsGroup: 100
        # fsGroupChangePolicy: OnRootMismatch
        # seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 8080
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      app:
        existingClaim: *app
        globalMounts:
          - path: /App/config
            subPath: config
          - path: /App/data
            subPath: data
          - path: /App/wwwroot/translations
            subPath: translations
          - path: /App/wwwroot/documents
            subPath: documents
          - path: /App/wwwroot/images
            subPath: images
          - path: /App/log
            subPath: log
          - path: /root/.aspnet/DataProtection-Keys
            subPath: keys
      tmp:
        type: emptyDir
        globalMounts:
          - path: /App/wwwroot/temp
