apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    #ENC[AES256_GCM,data:tSZJGB2V6A==,iv:mqenMgN6Zsec5dJTKsc2GNdC3ZgK0Ni7yfGi2hvKhms=,tag:A7wlgYjbJCXw1DRLdGmB7w==,type:comment]
    SECRET_DOMAIN: ENC[AES256_GCM,data:IvEXDc4cOf1nCFM=,iv:yOZVrowU/R1XNnps6OyUJFtHQFBaytPCVjIPIX7VekM=,tag:sV/8lI4pfaG61JShhYYutw==,type:str]
    CLOUDFLARE_ID: ENC[AES256_GCM,data:65FeKPXGniSwhRQRjeehsK79nE/dEnuIRoxubcsyTDjIFO71,iv:YYcrtGY3A5ShIcwju/8h3TEU4n+XqNMhdGVGWECcqdo=,tag:KcX0OzFq+AxVo/xwRj7lFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTDJkWmdBS3BJanJSbm5h
            REUwM1BIRGtiYzFCY0NCbWZqYjkxZERKLzAwClhreTNxSUNLOEF6UXBub0JqWkI0
            UExCVzhmZ0pnVHNXbSswcDVLWFNORTAKLS0tIFFQYXAwN1dDbE1reCtiVHpKVGdj
            Yi83eGw1T0Yxc016YkZIQlRjcGpud3MKt4yOStSNl717GePMrk4mV3BT8T+MXJqc
            6g2vJ1/qsj9LJvxIWwtQi+Rm0hbjCP0ZXGLOTtCyCnaruvi+HeyJag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T23:04:11Z"
    mac: ENC[AES256_GCM,data:eSvO4WTw+IM1S3/GZCNm6xo/82+FwC7vCRVA3mDPSnkbgrCAe2N+p1JVBE5BrNT6REAvzZ82DiEJ3qiCwTpMgGbr+RMZHfx3ZfMdLziY5a2O1SDh8OTQMs/1Zq4ZLl7mvgyFwxgodGvhkOO8e2esIx8DZmBUI5EyI6IEAUT5zZg=,iv:F2jYsB3yr+ZqZrbkZtiII8CHdAUqhC9kG0Z7FhgxDIY=,tag:T3Bju0W40o6UySI5oYTfaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
