apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:aPP/rxXSbZu8ePo=,iv:ZjNPjcHDwncb7Y85arEcJA8kwYRSMG6cS8sQs1fS1Fo=,tag:bkL+tu9yBRVQlpIRwSlnLg==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:WgomuxncAQHl5G7CRptFV5XTddSoOlEshbG7CoBAv5TqJ7BB,iv:FVQ2U2pmzci4i9NDZsaZkC75M6JQ+5mqCv6PQH9WxJI=,tag:DLE2INyGznMXwQr44RYCIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Ym45aHZiaEVIT0NrdmxY
            dngxVlZDRk84K2UyNE9jOGtsV1FtSElBOW1nCjZ4TnhYbDVtN2FWdlBKVW8zTmFx
            U3JBSzNIUExMY21FbkoyWlI5VEszSzAKLS0tIDZObm5CMzd1ZUFtRGc3bmN3d09j
            b3BkMTh1WFNWVWVXalEzSmh4K1oyUEEK05tIJycXX/0G3pJa5n9kuXF1B6Kbe5+p
            EGtSbEs3USY0fkufZlb+o7YtD0/giez+Y4x4MCzyP+0e1okqJa0Kbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-23T14:23:52Z"
    mac: ENC[AES256_GCM,data:XWfkYlHuURwLbBdUviYifAlfTENyxuFwoiDy+JjRxVdZ4/XqCy0AXN0aKYUNNVjFcwel8LULY9AidG21EE3qeFRkCRDD63efzCRahlsb8wTWAxuVX9LRkXqs05LRqZOYTWgjhD1vc9Ho9s0CS9lViY7Q9RnH+W15xC4MtcywtAY=,iv:ePT0Aem281NNNoFplajI17MpU/2jQJy95e/dPDL7HuE=,tag:7DBqaVkQuvvtf4gi25J/vw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
