apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:IvEXDc4cOf1nCFM=,iv:yOZVrowU/R1XNnps6OyUJFtHQFBaytPCVjIPIX7VekM=,tag:sV/8lI4pfaG61JShhYYutw==,type:str]
    CLOUDFLARE_ID: ENC[AES256_GCM,data:65FeKPXGniSwhRQRjeehsK79nE/dEnuIRoxubcsyTDjIFO71,iv:YYcrtGY3A5ShIcwju/8h3TEU4n+XqNMhdGVGWECcqdo=,tag:KcX0OzFq+AxVo/xwRj7lFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTDJkWmdBS3BJanJSbm5h
            REUwM1BIRGtiYzFCY0NCbWZqYjkxZERKLzAwClhreTNxSUNLOEF6UXBub0JqWkI0
            UExCVzhmZ0pnVHNXbSswcDVLWFNORTAKLS0tIFFQYXAwN1dDbE1reCtiVHpKVGdj
            Yi83eGw1T0Yxc016YkZIQlRjcGpud3MKt4yOStSNl717GePMrk4mV3BT8T+MXJqc
            6g2vJ1/qsj9LJvxIWwtQi+Rm0hbjCP0ZXGLOTtCyCnaruvi+HeyJag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T01:02:55Z"
    mac: ENC[AES256_GCM,data:odw6k9woV+7TgWcz5SaHjzilwYDNyjIPP6L+NLaMUcCqa7b1TUDMsP3DCu+9toM6KpBr6FaaWk/ev9VmKWvrHte6IycT4LaSy8iPYKvLz66Asfku4oGExkCESZt2KfNvWsBnSZdZJXkdY1Cd8T7tl0+7wiomTTmOmVDgtNpXl/I=,iv:ZQ6ZZQSiBcwFD1ST0q3RegHFtOwZPqKZ5igw8yFTmBc=,tag:CDELwgiH3FYvoDL1pfyR1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
