---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: radarr-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: &dbHost postgres17-rw.dbms.svc.cluster.local
        INIT_POSTGRES_DBNAME: radarr_main radarr_log
        INIT_POSTGRES_USER: &dbUser "{{ .RADARR_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .RADARR_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        # App
        RADARR__AUTH__APIKEY: "{{ .RADARR_API_KEY }}"
        RADARR__POSTGRES__HOST: *dbHost
        RADARR__POSTGRES__PORT: "5432"
        RADARR__POSTGRES__USER: *dbUser
        RADARR__POSTGRES__PASSWORD: *dbPass
        RADARR__POSTGRES__MAINDB: radarr_main
        RADARR__POSTGRES__LOGDB: radarr_log

  dataFrom:
    - extract:
        key: /radarr
    - extract:
        key: /cloudnative-pg
