---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: alertmanager-secret
    template:
      engineVersion: v2
      data:
        # Notification
        PUSHOVER_API_TOKEN: "{{ .ALERTMANAGER_PUSHOVER_TOKEN }}"
        PUSHOVER_API_USERKEY: "{{ .PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: /pushover
