apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    slack_api_url: ENC[AES256_GCM,data:Zb56ZS40J6etWtOiG3LUzCSdfRREpX+21huOqOnI1/qKOfyDp7UpEQPEmnaveVEsbQz2KJbueZDRSBv1jSmbdAstvV5uhwOqBDE2InM09Zm2,iv:eOdzAGN//1MjqFmRMaYH8VTY7789aJZ7rQcNP3Y27w8=,tag:KbgVqmeTgneCR24krrJFlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T22:02:09Z"
    mac: ENC[AES256_GCM,data:7+lDG/+LOaRReeyr31UCmw8iJ6wRFYdc7E8clcZoPTAW0EeMkX7h22b8kCTxz1tE7xm1Q16o9WNA55MMBD5coBcaH1XDUka3Ez2Sk8awrAddiXDFT8ncyXt71HunyMzqibbhmgBZgz6qlepXPQ4t1QW72Q2hPt8KWU2jBTfBPa8=,iv:NxlxtDC7Y8+sPpy6Ky2g/1Kl57AnVk8eFG6v+XNffpw=,tag:3NikcUvaFoABrmXdnfKM0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
