apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    PUSHOVER_API_TOKEN: ENC[AES256_GCM,data:+6Xst+VmWGjrtXljXG04w8uG1FZASccU+UMfTc1e,iv:v/gcmDQ23U6HBebclsLmkZEuTqQCWmPDWZoB+17w99w=,tag:OUpnqdXl4dSsHVmpMZO4Fg==,type:str]
    PUSHOVER_API_USERKEY: ENC[AES256_GCM,data:Cym4AELYOwAuPxqJK65PdKmHJa/UZGXFQS79kXWl,iv:LW1tYz/voos7TOA0zODoD3IW2J0pu3wZ/PeXWKTOVTw=,tag:R5gMibHAqErY3RyA0kIkZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-26T01:37:16Z"
    mac: ENC[AES256_GCM,data:2dK9wW/QIvSiVmMbxLFAZATZv87twc5kAMR0FW7HZ0FwE8L5d1A0gpnmF6TAuerEl8YNvzXh2856W2eMHiCo0hwXhjkYR9TLyvimMybXyDS14pjdEvwxf8xKaituocalRRKJNW3Spyd9RMJ/ZC6CRI4dK0Q2Eu+mA1LamnvdWWg=,iv:QffeJnv/2k5oygk3YnhMn4kOaIADIEcNIRTk/bq8Uc8=,tag:6IrJM6plK5iJ+wN4jho3vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
