---
web:
  port: ${WEB_PORT}

debug: false

ui:
  title: Status | Gatus
  header: Status

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

metrics: true

storage:
  type: sqlite
  path: /config/sqlite.db
  caching: true

