---
ui:
  title: Status | Gatus
  header: Status
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: flux-webhook
    url: https://flux-webhook.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
metrics: true
web:
  port: ${GATUS_WEB_PORT}
storage:
  type: sqlite
  path: /config/gatus.db
  caching: true

