---
web:
  port: ${GATUS_WEB_PORT}

debug: false

ui:
  title: Status | Gatus
  header: Status

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Lumen
    group: connectivity
    url: icmp://4.2.2.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

metrics: true

storage:
  type: sqlite
  path: ${GATUS_CONFIG_PATH}/gatus.db
  caching: true

