# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:uKpepMsB1Wf+lx2uqU73+zHHRcsPVPkdLmMAjxGw89qOzdpXSSffkA==,iv:JiKqu6iRvlP1vqekHfpatyd7xbv9E6n/wyTKdG0/HrM=,tag:kqKbEqgg0kKKA/952qPemw==,type:str]
sops:
  age:
    - recipient: age1pj705hhyh9u9dwxsj2ak9l49tv3nqqlfxj4zxsj0wkrpnlywdvzqf7vz08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiblRXQ2hUZ280UDlwekZF
        RUU1YWNCR1RvNktCcWt3QUhSS2FadDhTOGl3CkIxd01rZEpDb0ZObEs0b0U1TDVM
        VHJncTdXTUdOUnFMT0xmZ0p2Z0YyWkEKLS0tIHlrbzVtdUZxUlpTWjBrODZBVyty
        SzRnaUkvcXRPcGdicytpUGM0aEFkemMKG9+SwjfR8nE2KHCmqiacl0RoPp7cVSQw
        ZQNWK3gFx4ErOLb8eB0rcStLMtgR4yPMKIa7K1bdNueU5ysKwapsPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-12T16:55:42Z"
  mac: ENC[AES256_GCM,data:5fheDbGpMIPBav6aCwxSA9j21iljBWHMey/rR+T0qAUo+yCyFMjAb68OMVPmV5q8jm4ha3jlXFiyYefw0Tj6RYBIZWAslF+BiaT2r3pv5H1nHSnrGuGUNjkO0CW9EUFDE0Y79Jawj3POcWXM3q++vsHqimyFHvtPfTOdKMpLctM=,iv:zTtqxYaSnjTkla0jKgaJApijp2HA4g63pQ72qRGaIrg=,tag:rxfXOWs/aoPlfickDHGPoQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
