apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Da685ALgquWmGuJHxtm0PlZ8E9dJDoCWzqMyf3Su0tYNlW+0eGGSnw==,iv:BOGnyIgMRq5iQ/08dVAmm96lE1AHVIuxd09gR/G/k24=,tag:U+62cy1k/pYO4k1NSjhATA==,type:str]
sops:
  age:
    - recipient: age1qez67uw84ygk7q39yr3ht5nxzr32c8pf2zxc4znvn8lvtx3kqgmqv5wgu5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK0JjeEVNbHR6bURxV1BZ
        R1lVa0NsNHhUVUN6UDlvdEZUQ0dMckNYVUVnClFlRmdRaFplSEhhbmZuZzZuZUhH
        WlRiT3F4TStVTzgzenpjSmRoVHFSbk0KLS0tIGozYW4zOEU1cElmWU5RMURIQ21U
        YmhxVXZjT250bW1SRi9BTXUxL0lRa1kKLB5NNk9+obeoVP1aC2ALDpIjpwx4zdFL
        dNe2u1MNplNxcfsuHEa28xRe/aJfQZcm8JJEcQOKcTU1kgT9qGGdVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T09:09:52Z"
  mac: ENC[AES256_GCM,data:2v1JuBgGqf/+lpcHzF5HzxRa0vWqvJBmw/wny+C7DiD0k967bUJxaLDeCpVbbcK1xA38MH5xa7bWvyJwbTm2z3uu+IGW2oGS+QhK3ThA2e43oF8E+GVtFeJ1l6ev9HOjVmeush5H7g8abrPfF52x7EZq/MlLvu8CDPvXEE02zjc=,iv:Fjv2Lj3IVbHj+jUICUooLopIGzNZ07LdD0V/nthCPJo=,tag:lifhvcjPxNPxk2IkepqzBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
