apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:XwIUov2X+ER+53Ob3NcpLZq1WAIEP/kfNQ4tt5/7DIlPHiLQMTcTPPhMChwdav3X+4Jj4d0=,iv:WSlASxu6g70rOEAcPH5qZWwhA0gzy82uQ46I6P6azGI=,tag:tbgxyi0rbYibV3ZiqlsJzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIKzFtajhSYVo4TFpRT1Qx
            a2xOZ2dnbTREMm9mOW05TE5OQU1BelU3YTFFCmFXZHJ1cmdzOE5SdFMvT0VkZjV2
            QjduRTdxMGx5NHZCVHBkN1lqZ0UvaFEKLS0tIDhKYmRDZXZyTXJDTFhlUzBJZ0xF
            aEJ0RWNNeHZmd2pRT2crWjUrZDU5b1kKG1HVam+sEyPom0FlnDAu0X2ZnqiwBScp
            7OBezgRWIXXH0QZqDMBN97IkRSqHRzIzCb4NuNQAITR7KawUfWKJFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12s85l6vmg08smu66rskhpaupg7htdzdvdrj0ca6rzwn3ujneaq9q7nzaxn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T22:15:45Z"
    mac: ENC[AES256_GCM,data:8RaOfPWwSD79z84UdXVlQO9FnYyCmfMVz9Ki+OXWQUgQZeIlGzC33ho+5zwxriGpA6jJYxlB6XVv/sbv838Kefz9V3K+zGqsUqA8JfvG4/8ptScxqZJsDdycReuPWBYZyI6HQw3YMB5QcCFppK56yI/rnZWGYmVXUWRL0lY+3bs=,iv:ohIy68IKdiQ5enrMGTfQUgznAXruEiY93P/2Hbq26e8=,tag:SzGMEiceAzMlIMARAft9lg==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
