---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/volsync.backube/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: daily
spec:
  enabled: true
  activeDeadlineSeconds: 21600
  trigger:
    schedule: "0 */8 * * *" # Every 8 hours
  repository:
    repository: volsync-maintenance-secret
  successfulJobsHistoryLimit: 1
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
