apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6z1tPjIYnyV62c4ChX+R/xw8,iv:8xQwF+aCLwT1O3ihO8aGASXb5vK0ohbFn2ABlV/jKuE=,tag:KSMLHwFRG8ObTRJEqSY7YQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Sqq9daa2ZPi+jfYhbVtSuLiktyiv8A==,iv:50t5qgPnw3tBmNTjdaNKW6cBnoL3cbKwufuBaxj9n7A=,tag:Rv9uSeshj0OLsjFk+ma5gQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaFBxdUk1TzA0Q2hreCtx
            NDJvUDlpeW9xR04xRTFSMXhzRlBtV3ZNd21JCnVYSVRaNUxmTWVyZWhYYkpua0Rq
            QkpVN2JiTWdqUzZkWklCMWJMT3BsbzAKLS0tIHJlVTJQM3hMaEQ2T05wWUxzQ2J1
            MkZPMkkxTmN4ZWd2c2pLdHZCZTc2UWMKo16dhqOOWKeHCGmdqBDrzilFIhBvjRJC
            yCWO4SrpwZqhu2SR2swHbTZdJHpH5cpF3FNBhxJEyLgu6hmaYaMGVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T03:12:09Z"
    mac: ENC[AES256_GCM,data:JNg3QJI+YDEKEszXQx30OKYru1bH+4FERKJsLJA7DvMYP/WA/2c73ItQD7uYcnH4beQH0nMdjXh4x5gAcKI4BXoDLh+rlROzK8cECd4FB9qUxtjwHt7CWjq8iO2NMrnpNU/itXKULd3rJO3we0ZIO8H+vOb9uCWA650R6APs2J8=,iv:hrgBRTe6NxgddXmgeBg2RAHzIswG67sb9XgcuOmUmPA=,tag:2SwoQvEw/pjLd9iloAA38A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
