---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx-operator
spec:
  interval: 1h
  path: ./kubernetes/apps/dbms/emqx/app
  prune: true
  dependsOn:
    - name: akeyless-store
      namespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: dbms
  wait: false
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx-cluster
spec:
  interval: 1h
  path: ./kubernetes/apps/dbms/emqx/cluster
  prune: true
  dependsOn:
    - name: emqx-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: dbms
  wait: false
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
