---
clusterName: k8s-gitops

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://172.24.20.11:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "172.24.20.11"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "oya"
    ipAddress: "172.24.20.12"
    installDiskSelector:
      serial: A0D6073B184B00007040
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/8af8cf71310e5eeddc32fa523441d6a0f181e0fb859e66bf7dbed7affb2e73c9
    controlPlane: true
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: disk.serial == "50026B73839504FD"
          minSize: "300GiB"
          grow: true
    networkInterfaces:
      - interface: bond0
        bond:
          deviceSelectors:
            - hardwareAddr: "58:47:ca:7b:e6:e4"
          mode: active-backup
        dhcp: true
        vlans: &vlans
          - # IoT VLAN
            { vlanId: 40, dhcp: false, mtu: 1500 }
          - # Vpn VLAN
            { vlanId: 50, dhcp: false, mtu: 1500}
        vip:
          ip: &vip "172.24.20.11"

  - hostname: "aje"
    ipAddress: "172.24.20.13"
    installDiskSelector:
      serial: AA202302171T21213049
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/8af8cf71310e5eeddc32fa523441d6a0f181e0fb859e66bf7dbed7affb2e73c9
    controlPlane: true
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: disk.serial == "50026B7383950E6D"
          minSize: "300GiB"
          grow: true
    networkInterfaces:
      - interface: bond0
        bond:
          deviceSelectors:
            - hardwareAddr: "58:47:ca:7b:e9:48"
          mode: active-backup
        dhcp: true
        vip:
          ip: *vip
        vlans: *vlans

  - hostname: "oba"
    ipAddress: "172.24.20.14"
    installDiskSelector:
      serial: AA230711NV01KG10664
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/8af8cf71310e5eeddc32fa523441d6a0f181e0fb859e66bf7dbed7affb2e73c9
    controlPlane: true
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: disk.serial == "50026B7383951A37"
          minSize: "300GiB"
          grow: true
    networkInterfaces:
      - interface: bond0
        bond:
          deviceSelectors:
            - hardwareAddr: "58:47:ca:7b:ea:1c"
          mode: active-backup
        dhcp: true
        vip:
          ip: *vip
        vlans: *vlans

# Global patches
patches:
  - "@./patches/global/machine-features.yaml"
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kernel.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  # - "@./patches/global/machine-udev.yaml"
  - "@./patches/global/machine-nodelabel.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

  schematic:
    customization:
      extraKernelArgs:
        - init_on_alloc=0                     # Less security, faster puter
        - init_on_free=0                      # Less security, faster puter
        - intel_iommu=on                      # PCI Passthrough
        - iommu=pt                            # PCI Passthrough
        - mitigations=off                     # Less security, faster puter
        - security=none                       # Less security, faster puter
        - talos.auditd.disabled=1             # Less security, faster puter
        - i915.enable_guc=3                   # Enable GuC and HuC for better graphics performance and stability
        - i915.force_probe=!a7a0              # Disable iGPU deviceID for i915
        - xe.force_probe=a7a0                 # Enable iGPU deviceID for xe
      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/iscsi-tools
          - siderolabs/mei
          - siderolabs/nfsrahead
          - siderolabs/util-linux-tools
          - siderolabs/xe

