---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-exporter
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: emqx-exporter-secret
    template:
      engineVersion: v2
      data:
        EMQX_EXPORTER_API_KEY: "{{ .EMQX_EXPORTER_API_KEY }}"
        EMQX_EXPORTER_API_SECRET: "{{ .EMQX_EXPORTER_API_SECRET }}"
  dataFrom:
    - extract:
        key: /emqx
