---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-exporter
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: emqx-exporter-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          metrics:
            target: emqx-dashboard.dbms.svc.cluster.local:18083
            api_key: {{ .EMQX_EXPORTER_API_KEY }}
            api_secret: {{ .EMQX_EXPORTER_API_SECRET }}
          probes:
            - target: emqx-listeners.dbms.svc.cluster.local:1883
  dataFrom:
    - extract:
        key: /emqx
