---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - ./alloy/ks.yaml
  - ./blackbox-exporter/ks.yaml
  - ./fluent-bit/ks.yaml
  # - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./karma/ks.yaml
  - ./keda/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./nut-exporter/ks.yaml
  - ./silence-operator/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./teslamate/ks.yaml
  - ./unpoller/ks.yaml
  - ./victoria-logs/ks.yaml
