---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: babybuddy
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: babybuddy
  values:
    controllers:
      babybuddy:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/babybuddy
              tag: 2.9.2@sha256:39a1b52b053d892f805b5a8f31bdee093ff0ac5c62fb9d81bba262d1aa3e4e87
            env:
              TZ: America/Los_Angeles
              CSRF_TRUSTED_ORIGINS: https://baby.${SECRET_DOMAIN},https://{{ .Release.Name }}.${SECRET_DOMAIN}
              PUID: 1000
              PGID: 1000
              DB_ENGINE: django.db.backends.postgresql
              DEBUG: 'True'
              REVERSE_PROXY_AUTH: "True"
              PROXY_HEADER: HTTP_REMOTE_USER
              SECURE_PROXY_SSL_HEADER: "True"
              DB_HOST:
                valueFrom:
                  secretKeyRef:
                    name: babybuddy-psql-app
                    key: host
              DB_PORT:
                valueFrom:
                  secretKeyRef:
                    name: babybuddy-psql-app
                    key: port
              DB_NAME:
                valueFrom:
                  secretKeyRef:
                    name: babybuddy-psql-app
                    key: dbname
              DB_USER:
                valueFrom:
                  secretKeyRef:
                    name: babybuddy-psql-app
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: babybuddy-psql-app
                    key: password
            envFrom:
              - secretRef:
                  name: babybuddy-secret
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "iot",
            "namespace": "kube-system",
            "ips": ["172.24.40.31/24"]
          }]
    service:
      app:
        ports:
          http:
            port: 8000
    route:
      app:
        hostnames:
          - "baby.${SECRET_DOMAIN}"
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
    persistence:
      config:
        type: emptyDir
