apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:gDQlnNXQ5XtXARqAVUQs2m5WtPA=,iv:OpO1u5VJlISsy/c+0dPuUDpX5V6ElEdQT9+joIne5nY=,tag:oZUyTeLK/VQpK9kRG7CXjA==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:w9E+W5k2frdgZSnvPO9UiOdQMX4NG0/gdkrgbvgqlf6osFvL,iv:JRBZmS8dB7uxaYqZLfKbk4V9mrqc3ID6x+KM1FZYERs=,tag:uE0yBWRTQQOlJIT1bd20DA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaFBxdUk1TzA0Q2hreCtx
            NDJvUDlpeW9xR04xRTFSMXhzRlBtV3ZNd21JCnVYSVRaNUxmTWVyZWhYYkpua0Rq
            QkpVN2JiTWdqUzZkWklCMWJMT3BsbzAKLS0tIHJlVTJQM3hMaEQ2T05wWUxzQ2J1
            MkZPMkkxTmN4ZWd2c2pLdHZCZTc2UWMKo16dhqOOWKeHCGmdqBDrzilFIhBvjRJC
            yCWO4SrpwZqhu2SR2swHbTZdJHpH5cpF3FNBhxJEyLgu6hmaYaMGVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T21:28:25Z"
    mac: ENC[AES256_GCM,data:eCz+NARCYnfTpuc+wYa/cvI4oYaVnVfIE+6VfLTf+YJa/lgK4xfDs7r1TVUVaP7mbR8AgqZTNOKhhrL8iUrS2tCUVLvcGGZ2AzqghY6vsX4itSCX4cH9BiiGd1rd50LN6bpgwrvqW65s1W27icBCiV5Kf1WnZMsbuTK2AZuJa4Y=,iv:68ANMhiELPuE/QISfevkiYfmQppfgk0BcuPKSnPSDms=,tag:Qo2fdIaeNhRXeBV01cPV+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret-auth
stringData:
    config_local.py: ENC[AES256_GCM,data:B28Czjo5qP9oOpMO0097/4hzlcq8cjydSCu9AuWhQlksEHx1jU5t2+UBNxXl/VLueqyXQF0vhPN4MHHU5BJkKIGEkS0MHejJEUETJhww7VW5ep4x7mhnTUDbo+2cij/HQTQzYp8beCzTZYOjmzTTF5wNbyjaub6qUnT2OWgkJOC4TQijzaIauXqkY+RxzeA26B+0yMazI4sPCIv0M5RgyCNxPCplUQ1jA3xESVE13TKpW+kFOImrgBoVc0z6HgIY9NkkfImfSAkeDuEUBGyJfORXZsV/8WR/SoWGBLztOPxEvvBe63eKf+xcALEpT2ryahSg9qg2vM12mE220U3lVuA8FIWz/N2RfyQAUBcWpDHCdYmaLkgUa4lTkIY9saZyIvT2yHYhmpi4coLu1dveAuUv3voBMMq5vd7eeXRAoi/aW8Rp94+QPp3/a/Fut0or6VvoXH0OAlViUH29oGShcdE2f0alQ31GFiQBGXCfi7hsvnY3AYd6tq7bSzNSRb2V3kOpT/AEdNHM2NAXmIwZwWQqauMTBFuuWrp/H+IRX+TCz0GlSEZ0VVq4gaC5pG5xVwJ/gYdHgcVVOyKgcJwgQY03QZ0+9Ntdq2s9I9I6vyK1XIn77BJHVkHmCS0wJprII949PBQKeVrNXScHB1BeLeocF9BIN04MsWfkm8hvO2Bzpxnt7nWK3oHqOlrfrdjjdmFK06qBzvxIE55hD5otyB+AKyq1Xjh0Wx9jCLOwwUAikbRIn+kDDDhuT5atLLFkjKIMa8JIM0oyyPlRKJp/aJBYUyn8IpS4m6/bqXf2iXcsqKwkw7+gbyfLZCEAcmEJZlLpw/DFpFC3fj8zsF0M3VbBimT9BTfItBcqTT3+qq9aacSfLKFYie+ydDyw8FPgVqMdk7XoJ+ZncQiZ19ENNMlvL7+P2NQiu3AeI/C/mz4RzswaSIHvcM+xUVJDa9GLhbQdS4uCv1RrEtsLErt8XS2DhdSax/ONSHiAG/Bkg84n+m+raAyWrmDzYi62MUayR+TL5Q+tyYa4w7IBQQ396sCtNPkPwfaIQraenRBBZo3mIrle1v+pkSkmNhTXA0avqLovQsRp9qrAheycCsa3t6FAhM+MXjlxQ46Qj3+s3b5O27+Hn5Fzx6N1vCYtHXLy2jaT,iv:6W9NtP5WvbiDGKzqqrtzqGrSHpoSZ5UGlbXRa6hNPNg=,tag:rlTqoDgb3uT78lH7PUKCXg==,type:str]
    pgpass: ENC[AES256_GCM,data:WIUhfytNpL3yUIZYayxO0guplunAioLeYUs7EDu1/ACBEmmrjQ+pe4Lz7DFzfOXrVuxpYtfLlyehV3wXzYexh6cZy9TNNmE8t2jWeOkMDwNxlPAPQ/bqh2ngvqFk2KDZ8l6oF2aBIOsS7qG7vA==,iv:zakQUxxezX1RXTKv6gQwXoFacgAWjOZSsdR4ktqgiT4=,tag:mz0wzX9Ev4gh/Mpbp8Mv/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaFBxdUk1TzA0Q2hreCtx
            NDJvUDlpeW9xR04xRTFSMXhzRlBtV3ZNd21JCnVYSVRaNUxmTWVyZWhYYkpua0Rq
            QkpVN2JiTWdqUzZkWklCMWJMT3BsbzAKLS0tIHJlVTJQM3hMaEQ2T05wWUxzQ2J1
            MkZPMkkxTmN4ZWd2c2pLdHZCZTc2UWMKo16dhqOOWKeHCGmdqBDrzilFIhBvjRJC
            yCWO4SrpwZqhu2SR2swHbTZdJHpH5cpF3FNBhxJEyLgu6hmaYaMGVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T21:28:25Z"
    mac: ENC[AES256_GCM,data:eCz+NARCYnfTpuc+wYa/cvI4oYaVnVfIE+6VfLTf+YJa/lgK4xfDs7r1TVUVaP7mbR8AgqZTNOKhhrL8iUrS2tCUVLvcGGZ2AzqghY6vsX4itSCX4cH9BiiGd1rd50LN6bpgwrvqW65s1W27icBCiV5Kf1WnZMsbuTK2AZuJa4Y=,iv:68ANMhiELPuE/QISfevkiYfmQppfgk0BcuPKSnPSDms=,tag:Qo2fdIaeNhRXeBV01cPV+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
