apiVersion: v1
kind: Secret
metadata:
    name: emqx-exporter-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:5lJOgZerPgD2wEPpjnx6+oksYe43cH6jEgLacJ3HBHXgX9atLYGSxu5lQBgG69ntgTicLAYWVuVxYAdqGt/sS1pBWGcF+uvOYT4kjsgQDK+9oXkLa+y3pTVbfLi5Pa1ETg+84/v5vRrqM0mZ2Un7Uk+bLo2MZQvYcOGNpTQ/2/toM9knbcQK7LThYX3tFtjdTd5LqKSyvDBeuAixAQqhv5TMeBDDx6ArlkKTr6PV0s7m1o5cC6pEpWwFuDA2xD2Mx+Sb3sPrEm7VDcME1Bzx5D5SxgxaCt8B,iv:8LQMVIGY/c+NjNh3dAAfu34WEjJnjeOf8xWV0qRHYIs=,tag:dXzWbrSExBv9WLjfrsGGuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaFBxdUk1TzA0Q2hreCtx
            NDJvUDlpeW9xR04xRTFSMXhzRlBtV3ZNd21JCnVYSVRaNUxmTWVyZWhYYkpua0Rq
            QkpVN2JiTWdqUzZkWklCMWJMT3BsbzAKLS0tIHJlVTJQM3hMaEQ2T05wWUxzQ2J1
            MkZPMkkxTmN4ZWd2c2pLdHZCZTc2UWMKo16dhqOOWKeHCGmdqBDrzilFIhBvjRJC
            yCWO4SrpwZqhu2SR2swHbTZdJHpH5cpF3FNBhxJEyLgu6hmaYaMGVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T03:57:11Z"
    mac: ENC[AES256_GCM,data:3PHh0sT7NsnjgJ+LOgk0NgHFCG8snjno3IFUlfyk1L5ReTz23tJOocRkXQS2T5TYpIndvia6qRBVmIncJaW2ocjgvHHJuIEb0oxc4eTPUkmho73/KS30nWt3EXmWxthqDjOPnAFD2n1Zb9/eRUF9eP7g8LcnwfGbfoenoFjJd2k=,iv:Nslb+R3RblzmB1zfDSJLOMY09g3pMFD4ChOTNaWPqTU=,tag:vNEf4ktOB+dJtprxtBaD2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
