apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nut-exporter-network
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: servers
    app.kubernetes.io/name: nut-exporter
    prometheus: kube-prometheus
spec:
  endpoints:
    - interval: 30s
      path: /ups_metrics
      port: metrics
      scheme: http
      scrapeTimeout: 30s
      params:
        server:
          - oduduwa.internal
        ups:
          - network-ups
      metricRelabelings:
        - action: replace
          replacement: network
          sourceLabels: [instance]
          targetLabel: instance
        - action: replace
          replacement: network
          sourceLabels: [server]
          targetLabel: server
        - action: replace
          replacement: nut-exporter-network-ups
          targetLabel: job
        - action: labeldrop
          regex: (pod)
  jobLabel: nut-exporter
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      app.kubernetes.io/instance: nut-exporter
      app.kubernetes.io/name: nut-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nut-exporter-server
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: servers
    app.kubernetes.io/name: nut-exporter
    prometheus: kube-prometheus
spec:
  endpoints:
    - interval: 30s
      path: /ups_metrics
      port: metrics
      scheme: http
      scrapeTimeout: 30s
      params:
        server:
          - oduduwa.internal
        ups:
          - server-ups
      metricRelabelings:
        - action: replace
          replacement: server
          sourceLabels: [instance]
          targetLabel: instance
        - action: replace
          replacement: server
          sourceLabels: [server]
          targetLabel: server
        - action: replace
          replacement: nut-exporter-server-ups
          targetLabel: job
        - action: labeldrop
          regex: (pod)
  jobLabel: nut-exporter
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      app.kubernetes.io/instance: nut-exporter
      app.kubernetes.io/name: nut-exporter
