---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sparkyfitness
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      server:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17@sha256:86a1992d46273c58fd4ad95b626081dfaabfe16bd56944675169e406d1a660dd
            envFrom: &envFrom
              - secretRef:
                  name: sparkyfitness-secret
        containers:
          app:
            image:
              repository: ghcr.io/codewithcj/sparkyfitness-server
              tag: v0.15.1
            envFrom: *envFrom
            env:
              SPARKY_FITNESS_SERVER_HOST: "0.0.0.0"
              SPARKY_FITNESS_SERVER_PORT: &server-port 3010
              SPARKY_FITNESS_FRONTEND_URL: "https://sparkyfitness.${SECRET_DOMAIN}"
              SPARKY_FITNESS_LOG_LEVEL: "info"
              SPARKY_FITNESS_DISABLE_SIGNUP: "true"
              NODE_ENV: "production"
              TZ: "America/Los_Angeles"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *server-port
                  initialDelaySeconds: 60
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *server-port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *server-port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 30
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi

      frontend:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/codewithcj/sparkyfitness-frontend
              tag: v0.15.1
            env:
              TZ: America/Los_Angeles
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &frontend-port 80
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *frontend-port
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *frontend-port
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 20
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
            # Nginx container, needs to run as root
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
              runAsNonRoot: false

    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      server:
        controller: server
        ports:
          http:
            port: *server-port
      frontend:
        controller: frontend
        primary: true
        ports:
          http:
            port: *frontend-port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: sparkyfitness-frontend
                port: *frontend-port
    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          server:
            app:
              - path: /app/data
                subPath: server-data
      nginx-config:
        type: emptyDir
        advancedMounts:
          frontend:
            app:
              - path: /etc/nginx/conf.d
                readOnly: false
      nginx-tmp:
        type: emptyDir
        advancedMounts:
          frontend:
            app:
              - path: /tmp/nginx
                readOnly: false
      nginx-run:
        type: emptyDir
        advancedMounts:
          frontend:
            app:
              - path: /run
                readOnly: false
