---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: n8n
spec:
  interval: 30m
  path: ./kubernetes/apps/selfhosted/n8n/app
  components:
    - ../../../../components/postgres
    - ../../../../components/volsync
    - ../../../components/kopiur
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  dependsOn:
    - name: cnpg-operator
      namespace: dbms
    - name: akeyless-stores
      namespace: external-secrets
    - name: longhorn
      namespace: longhorn-system
    - name: volsync
      namespace: volsync-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false
  postBuild:
    substitute:
      APP: n8n
      VOLSYNC_CAPACITY: 1Gi
      KOPIUR_CAPACITY: 1Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
