apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
stringData:
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:2tQztQf1SJU=,iv:eL85IDN65VQN9HFW/mBiGwvgkYzEcc8kJn3Dhr0GEMw=,tag:Q+q4FJg5Q7AT9e/nf6yl3g==,type:str]
    POSTGRES_SUPER_PASSWORD: ENC[AES256_GCM,data:OSeCcDfgvESWF/E5pgqp5iHsZe+zoolGhAGFCXX6QFAeRFN3SSp1cXjdTYk7W+k=,iv:JBC97L5SRb6mmqaGGqnu6jrAuwBvZGw5fUr/OpNfqyo=,tag:Q4V3NmPPX1oS733mdWLeUw==,type:str]
    username: ENC[AES256_GCM,data:VdPdXKNLU2M=,iv:SKqTK6l1GGfH1N8aFOIAGkfIY+pcQhvU8IudBOUFF1I=,tag:WUQU4EaqKGse5O3QGDpE5g==,type:str]
    password: ENC[AES256_GCM,data:P3qD0lv6c3Pg55LmY5u7l7eZR0Xx31a1xYNVga4My10MMD0oxjgdhBPtzQGocnc=,iv:w4bybKSQU9mOqXfMj1Pu23O+KwXFWQf/7kA/4d9e6S0=,tag:Eqvb2M4Z7aqmWVrobHVjyA==,type:str]
    #ENC[AES256_GCM,data:kGAl++Goxm9eSI8=,iv:VjUI1ydXHI2oOjsszcZYz/FUBgmhXmPO4Sp+ZzzE49c=,tag:2iSFk8H+iW7MIDE1SJUbeQ==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6z1tPjIYnyV62c4ChX+R/xw8,iv:8xQwF+aCLwT1O3ihO8aGASXb5vK0ohbFn2ABlV/jKuE=,tag:KSMLHwFRG8ObTRJEqSY7YQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Sqq9daa2ZPi+jfYhbVtSuLiktyiv8A==,iv:50t5qgPnw3tBmNTjdaNKW6cBnoL3cbKwufuBaxj9n7A=,tag:Rv9uSeshj0OLsjFk+ma5gQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaFBxdUk1TzA0Q2hreCtx
            NDJvUDlpeW9xR04xRTFSMXhzRlBtV3ZNd21JCnVYSVRaNUxmTWVyZWhYYkpua0Rq
            QkpVN2JiTWdqUzZkWklCMWJMT3BsbzAKLS0tIHJlVTJQM3hMaEQ2T05wWUxzQ2J1
            MkZPMkkxTmN4ZWd2c2pLdHZCZTc2UWMKo16dhqOOWKeHCGmdqBDrzilFIhBvjRJC
            yCWO4SrpwZqhu2SR2swHbTZdJHpH5cpF3FNBhxJEyLgu6hmaYaMGVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T03:07:52Z"
    mac: ENC[AES256_GCM,data:xM8CZ0y8rtJ2D7oQfQUs7U6lnN8M7Dv18SDDnTI565deKfR01leJWFQeFi0v0UsbtAo24j1BLnG8FT18O6W8N87xjw4LWpEa4m8bLVv7mQEH9mnGGuiFDu+w+YbJPJPU/ARtQwrKp/rChnNw8ZBVKg8ZFYuSh4mchA0MpxyayA0=,iv:vONbZcwjE9QoG12yHeOJMcf/J6DrXiAPLHC0YcDrr1Y=,tag:Muc0NihULxD1vyhJ4KwNHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
