---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      zigbee2mqtt:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.4.0@sha256:dd7479e5416c4b95725333d0a69ff504bcbda9a7a3431e5d5dd1e27c16465cdd
            env:
              ZIGBEE2MQTT_DATA: /config
              ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: "ISO_8601"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: "info"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
              ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: "zigbee2mqtt"
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://emqx-listeners.dbms.svc.cluster.local:1883"
              ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
              ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: "tcp://10.0.101.12:6638"
              ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: "115200"
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: "zstack"
              ZIGBEE2MQTT_CONFIG_SERIAL_RTSCTS: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_TRANSMIT_POWER: "20"
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: true
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_STATUS_TOPIC: homeassistant/stat
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee2mqtt.${SECRET_DOMAIN}
              ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: &port 80
            envFrom:
              - secretRef:
                  name: zigbee2mqtt-secret

            securityContext:
              privileged: true
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 512Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        existingClaim: *app
      config-logs:
        type: emptyDir
        globalMounts:
          - path: /config/log
