---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lubelog
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: lubelog-secret
    template:
      data:
        # App
        POSTGRES_CONNECTION: 'Host=${CNPG_NAME:=pgsql-cluster}-rw.dbms.svc.cluster.local:5432;Username=${APP};Password={{ .${APP}_postgres_password }};Database=${APP}'
        # Smtp
        MailConfig__EmailServer: "{{ .SMTP_HOST }}"
        MailConfig__EmailFrom: "{{ .SMTP_FROM }}"
        MailConfig__Port: "{{ .SMTP_PORT }}"
        MailConfig__Username: "{{ .SMTP_USERNAME }}"
        MailConfig__Password: "{{ .SMTP_PASSWORD }}"
        # Oidc
        OpenIDConfig__Name: Pocket-ID
        OpenIDConfig__ClientId: "{{ .LUBELOG_CLIENT_ID }}"
        OpenIDConfig__ClientSecret: "{{ .LUBELOG_CLIENT_SECRET }}"
        OpenIDConfig__AuthURL: https://sso.${SECRET_DOMAIN}/application/o/authorize/
        OpenIDConfig__TokenURL: https://sso.${SECRET_DOMAIN}/application/o/token/
        OpenIDConfig__RedirectURL: https://lubelog.${SECRET_DOMAIN}/Login/RemoteAuth
        OpenIDConfig__UserInfoURL: https://sso.${SECRET_DOMAIN}/application/o/userinfo/
        OpenIDConfig__Scope: email
        OpenIDConfig__LogOutURL: https://sso.${SECRET_DOMAIN}/application/o/lubelog/end-session/
  dataFrom:
    - extract:
        key: lubelog
    - extract:
        key: cnpg-users
    - extract:
        key: smtp
