---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: lubelog-postgres
spec:
  provider:
    kubernetes:
      remoteNamespace: &namespace default
      server:
        caProvider:
          type: "ConfigMap"
          name: "kube-root-ca.crt"
          key: "ca.crt"
      auth:
        serviceAccount:
          name: external-secrets-pg-lubelog
          namespace: *namespace
