---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app autom4b
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      autom4b:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          autom4b:
            image:
              repository: seanap/auto-m4b
              tag: latest@sha256:0a8c10ab6b983fcd63e5bb408244f00efc728b86882b9e5e48ceb5e7fe299d64
            env:
              CPU_CORES: 2
              SLEEPTIME: 60m
              MAKE_BACKUP: Y
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    persistence:
      temp:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/autom4b

      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config
