---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app autom4b
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      autom4b:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          autom4b:
            image:
              repository: seanap/auto-m4b
              tag: latest@sha256:bf50bb8c674a6cced23115fc260791a72782e1ab57dbeff5184b848f4737bc6e
            args:
              - --input-dir=/import
              - --output-dir=/import
              - --watch
              - --delete
              - --output-format=m4b
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    persistence:
      temp:
        type: nfs
        server: shango.internal
        path: /mnt/user/data/autom4b
        globalMounts:
          - path: /temp
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config
