---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: espresense
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: espresense
  values:
    controllers:
      espresense:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: espresense/espresense-companion
              tag: 2.2.0-b17@sha256:449b0b4c2059a4cf5f74deb7d688c8e5d479eaeb337303e0ab9f579eae5f63d1
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  periodSeconds: 5
                  failureThreshold: 30
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                memory: 4Gi
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.117.0@sha256:e6702766518b961c7e3c41095c129c7c9a82b041578c53326c52fa363a057727
            args: ["--auth", "none", "--disable-telemetry", "--user-data-dir", "/config/.vscode", "--extensions-dir",
              "/config/.vscode", "--port", "12321", "/config"]
            env:
              TZ: America/Los_Angeles
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 500Mi
    service:
      app:
        ports:
          http:
            port: &port 8267
          update:
            port: 8268
          codeserver:
            port: &codeserverPort 12321
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: "{{ .Release.Name }}"
                port: *port
      code-server:
        annotations:
          gatus.home-operations.com/enabled: "false"
        hostnames:
          - "esp-code.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: "{{ .Release.Name }}"
                port: *codeserverPort
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
