apiVersion: v1
kind: Secret
metadata:
    name: akeyless-secret-creds
stringData:
    accessId: ENC[AES256_GCM,data:FLJYcLyWv/uFBLi/xZBVMQ==,iv:g9A9LJGjYoHkeiRZXIUjYR/4ylEYcUGglc8yhzQkkJ4=,tag:nQCTkCULlsJ18yrf8uLV0g==,type:str]
    accessType: ENC[AES256_GCM,data:IZD9MVq4ig==,iv:c+YD9DrlQ6LJTQvSHJ15yTdFxPJkfeSZpynlsdXJges=,tag:0px3u7eHJ+IaVfZ1jUSTmw==,type:str]
    accessTypeParam: ENC[AES256_GCM,data:IGDhV4dPrvfhtg==,iv:Ak5f+HxXuk9+loel5+D5aSrh8NAvlMi2uu2AObnu26E=,tag:O4u9s8orAq44ogkEUZ8ZBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T00:54:38Z"
    mac: ENC[AES256_GCM,data:qyWtsqLKWLU0JsqkTRU2Yg9xP3NG7eFRGEJJh3Eznak3WzWoQZRI0gqAyQAwhJgwpDk48qAeZuCKuc0saeFZf2zY4pOpiFKWWsGFd6wOT3uADMtC38K56CoKCzjjYVgx5JJdEpys44q8zvVmNEDT+kzBKZglHJkZx8CtuQNI49w=,iv:hIxn87wiOUwc7K5i0I+9fGHtP+DDWQorVNV93n5ijew=,tag:QP2SOJm2rQ7dfUQqGVzGyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
