apiVersion: v1
kind: Secret
metadata:
    name: akeyless-secret-creds
stringData:
    accessId: ENC[AES256_GCM,data:tXgrlWSIMbaytfK2WiNw6g==,iv:xEEPRUNcuc6Mb7EIDqbIxG4+3NvtDzJ7GfPt/asNkrg=,tag:2wLPZp18rtwImBg9jvmQUw==,type:str]
    accessType: ENC[AES256_GCM,data:zueKvg0jVg==,iv:HpceUAr9S1YKeJi+64BK48E+Gov05Hx/6A7W+BaCU/Y=,tag:GBSOitKTimCe1PiJMNkmxA==,type:str]
    accessTypeParam: ENC[AES256_GCM,data:A33KUegpIn4L+A==,iv:WNNvh3WyUSvGNOdvu9ZAJ+Te9T4qnCugO58h5R2CuHs=,tag:hnKrgsQ05VFEy+4CuW18Ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-26T17:21:44Z"
    mac: ENC[AES256_GCM,data:IGuxU34h9KQ/8Gyj98WqJlN2e0q6I3G/7r11TGkepdXqwGF7PqcVfSzJa4TR8CxFz2mgI0Il8YtGS8fWLaQ814mQHSYV3L0Sh/Ku1zuvVHW2pUgnzQ9LWzi9PzOufK7D7iDt+jlLbKnfMGTZhu+I6pTnnhsKL0dbBTMrH2kIrAA=,iv:zfhPItOMZy6mh0VF3vLPGon9TrftoiAgngaBNjJ36ms=,tag:HEbgjc3J7vG0kFFmiHPfrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
