apiVersion: v1
kind: Secret
metadata:
    name: akeyless-secret-creds
stringData:
    accessID: ENC[AES256_GCM,data:tYX8N1SUiFedJEI6Pvb+dg==,iv:3vH8XmLfFKwyQvT9PmcjGcVXaQJdZRHC+83G2A6DKNc=,tag:5gVkCcOsbrEHMRP62xSjWA==,type:str]
    accessType: ENC[AES256_GCM,data:zueKvg0jVg==,iv:HpceUAr9S1YKeJi+64BK48E+Gov05Hx/6A7W+BaCU/Y=,tag:GBSOitKTimCe1PiJMNkmxA==,type:str]
    accessTypeParam: ENC[AES256_GCM,data:S1ySejlHYqCS9Q==,iv:GE7926Mj6kQ4PYZt/Fs1eYTvOAgJjY3iSedbWl3i9ek=,tag:VnCyVIbTA7pt5bUrZLB/ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-26T05:30:11Z"
    mac: ENC[AES256_GCM,data:tdtUUgy5Wn36+EtLW39dOkh6z+J1nYBLzoLTRZ7UN4jfHvuH/bafUBIbIREyy/CRpZnLX3mHBw/1gPm8nYFI75/piv0re4kqLETR+b/MxN6i0SPrCp3Nt6nhVHm1wD93Bm7l5T5CqBhwQOGj1Utc6AF1XkaSsGLJ15ORWyrTzTk=,iv:H0KDH5bR3UFm5yrANps7f2B1mAIqEWT9pfMcJIw0d8c=,tag:ADQrSzoD43gNOoXXAKlfMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
