---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cloudnative-pg-postgres-pgdump-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        POSTGRES_HOST: postgres-rw.dbms.svc.cluster.local
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PORT: "5432"
  dataFrom:
    - extract:
        key: /cloudnative-pg
