---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-postgres-backups
spec:
  storageClassName: immich-postgres-backups
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: shango.internal
    path: "/mnt/user/k8s/immich/postgres/backups"
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-backups
spec:
  storageClassName: immich-postgres-backups
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
