---
apiVersion: v1
kind: Service
metadata:
  name: &app immich-db
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: immich.${SECRET_DOMAIN}
    lbipam.cilium.io/ips: 10.0.10.62
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: immich
    role: primary
