---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: home-assistant
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2026.4.4@sha256:589e4c1c93025d01320c14329427197c8b52d4f2e241a6bc1d6207837e07b4a7
            env:
              HASS_HTTP_TRUSTED_PROXY_1: 172.16.0.0/12
              HASS_HTTP_TRUSTED_PROXY_2: 10.42.0.0/16
              TZ: America/Los_Angeles
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
                add: ["NET_RAW"]
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.117.0@sha256:e6702766518b961c7e3c41095c129c7c9a82b041578c53326c52fa363a057727
            args: ["--auth", "none", "--disable-telemetry", "--user-data-dir", "/config/.vscode", "--extensions-dir",
              "/config/.vscode", "--port", "12321", "/config"]
            env:
              TZ: America/Los_Angeles
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 500Mi
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "iot",
            "namespace": "kube-system",
            "ips": ["172.24.40.22/24"]
          }]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: &port 8123
          codeserver:
            port: &codeserverPort 12321
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames:
          - hass.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - name: "{{ .Release.Name }}"
                port: *port
      code-server:
        annotations:
          gatus.home-operations.com/enabled: "false"
        hostnames:
          - "hass-code.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: "{{ .Release.Name }}"
                port: *codeserverPort
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      config-cache:
        existingClaim: "{{ .Release.Name }}-cache"
        globalMounts:
          - path: /config/.venv
      tmp:
        type: emptyDir
