apiVersion: v1
kind: Secret
metadata:
    name: akeyless-secret
stringData:
    accessId: ENC[AES256_GCM,data:WwXXmSByRkANLcgHwNtg1g==,iv:NZ+VUle7pwgVJO0t2VarkNcoZSIsE9H7B1Pt9BxuFU8=,tag:YMvGS6/roZu4E1BukU0Y1g==,type:str]
    accessType: ENC[AES256_GCM,data:IZD9MVq4ig==,iv:c+YD9DrlQ6LJTQvSHJ15yTdFxPJkfeSZpynlsdXJges=,tag:0px3u7eHJ+IaVfZ1jUSTmw==,type:str]
    accessTypeParam: ENC[AES256_GCM,data:IGDhV4dPrvfhtg==,iv:Ak5f+HxXuk9+loel5+D5aSrh8NAvlMi2uu2AObnu26E=,tag:O4u9s8orAq44ogkEUZ8ZBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T06:41:07Z"
    mac: ENC[AES256_GCM,data:LiOoOWGUQDyf9h4Xm0HtR61nP5zpe4/cP7ALIfR5yRy8E6RUNYR7xL0F+vqrXA7MgH/tJeIjaNXdVpbRzluNjLKe1Boy84uCtXYbVVDwh82GGKHON9T/9XLgkG8IiS68m+5XfQfxYq74Kmwd03YsT/TAYqeP6XacVRCSVtHKP4M=,iv:9SnmYItXjcjNdxc6sYzrH5VVaBq00dThA6/zBxus6As=,tag:peFOskzqfS30KOwAELJ6pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
