apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:nI+WJEfyXQjY/s0=,iv:pHCNhEbIyA6PKQ8lNAODOZ9LRGrIjRsK05uz8i/hQHg=,tag:uzybaj1Lyy7+Zin+1klD9A==,type:str]
sops:
  age:
    - recipient: age1pj705hhyh9u9dwxsj2ak9l49tv3nqqlfxj4zxsj0wkrpnlywdvzqf7vz08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnazlHK3R6eW1adDl4M2t0
        SkRibWhyTnVxMHJDcG9hQ2ZtMkFPa01rQ1cwCjFoZlZRVWNRd2tHS1Y4UjU3cDdk
        NElPWEE4SkNJenlpMjJ0V09mQ2hVcFUKLS0tIFFrS3p1NUYxbGg4aE1HK0FwS2NN
        RHdUUkZBTzdRckNOVWtiYnZGWGYzclEKLJHXmLZzjXqR641opBrhBnm/XLB7alCP
        Mi51oVHxY6Yca2Pgv7SJJ05DpjFaAbry/QBrw7CAY5pOWXdmvVIafA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-12T16:55:42Z"
  mac: ENC[AES256_GCM,data:Ek+GCIsUWRkhiPSjHD2/hU1igbuIi/kgR9KO9K42uIDsOkX9rWMI+mlec8eBHyEGi/Pw8M9KLJ3NGw1PPOepfR4IMC1lpet2N28TsGpTuJHsMtTLN18tUOrUhvuvlM2ixGnvV+ytflzlWDjKbwqYCZ9qXZJHs3YW4bLfFNJDFPo=,iv:FYE4cnfjm+4PwmZ2X+emLCUsKkPkkedEojRsZzGJi1U=,tag:LQry0ziwYGMz4/AEBeuw2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
