---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: baby-tracker
  labels:
    components.postgres/cnpg: init
spec:
  interval: 30m
  path: ./kubernetes/apps/selfhosted/baby-tracker/app
  components:
    - ../../../../components/postgres
    - ../../../../components/volsync
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  dependsOn:
    - name: "{{ .Release.Name }}-psql"
    - name: longhorn
      namespace: longhorn-system
    - name: volsync
      namespace: volsync-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false
  postBuild:
    substitute:
      APP: baby-tracker
      VOLSYNC_CAPACITY: 5Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
