---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: pocket-id-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
        INIT_POSTGRES_DBNAME: pocket-id
        INIT_POSTGRES_USER: "{{ .POCKET_ID_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POCKET_ID_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Database
        DB_CONNECTION_STRING: postgres://{{ .POCKET_ID_POSTGRES_USER }}:{{ .POCKET_ID_POSTGRES_PASSWORD }}@{{ .POSTGRES_HOST }}/pocket-id
        # App
        ENCRYPTION_KEY: "{{ .POCKET_ID_ENCRYPTION_KEY }}"
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
        # # LDAP
        # LDAP_BASE: dc=home,dc=arpa
        # LDAP_BIND_DN: cn=admin,dc=home,dc=arpa
        # LDAP_BIND_PASSWORD: "{{ .POCKET_ID_LDAP_BIND_PASSWORD }}"
        # LDAP_USER_SEARCH_FILTER: (&(objectClass=person)(cn=ID*))
        # SMTP
        SMTP_HOST: "{{ .SMTP_HOST }}"
        SMTP_PORT: "587"
        SMTP_USER: "{{ .SMTP_USERNAME }}"
        SMTP_PASS: "{{ .SMTP_PASSWORD }}"
  dataFrom:
    - extract:
        key: /cloudnative-pg
    - extract:
        key: /pocket-id
    - extract:
        key: /generic
