---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: pocket-id-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
        INIT_POSTGRES_DBNAME: pocket-id
        INIT_POSTGRES_USER: "{{ .POCKET_ID_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POCKET_ID_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App
        DB_CONNECTION_STRING: postgres://{{ .POCKET_ID_POSTGRES_USER }}:{{ .POCKET_ID_POSTGRES_PASSWORD }}@{{ .POSTGRES_HOST }}/pocket-id
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
        #Smtp
        SMTP_HOST: "{{ .SMTP_HOST }}"
        SMTP_PORT: "587"
        SMTP_FROM: POCKET-ID Admin <noreply@${SECRET_DOMAIN}>
        SMTP_USER: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        SMTP_TLS: "starttls"



  dataFrom:
    - extract:
        key: /cloudnative-pg
    - extract:
        key: /pocket-id
    - extract:
        key: /generic
