---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app teslamate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: teslamate-secret
    template:
      engineVersion: v2
      data:
        # Database Init
        INIT_POSTGRES_HOST: postgres17-rw.dbms.svc.cluster.local
        INIT_POSTGRES_DBNAME: teslamate
        INIT_POSTGRES_USER: "{{ .TESLAMATE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .TESLAMATE_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Teslamate
        ENCRYPTION_KEY: "{{ .TESLAMATE_ENCRYPTION_KEY }}"
        DATABASE_PASS: "{{ .TESLAMATE_POSTGRES_PASSWORD }}"
        DATABASE_USER: "{{ .TESLAMATE_POSTGRES_USER }}"

  dataFrom:
    - extract:
        key: /teslamate
    - extract:
        key: /cloudnative-pg
