---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app teslamate
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      teslamate:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17@sha256:e0c87ce7df39d06b93f27cf2cc6a056611f13faaa88cc07ab4dc8bf7a85d0b11
            envFrom: &envFrom
              - secretRef:
                  name: teslamate-secret
        containers:
          app:
            image:
              repository: teslamate/teslamate
              tag: 2.1.0@sha256:e580b5e806e07baa204823d5cf7873a733e9dbebcf3993dbe5df029fefdec38c
            envFrom: *envFrom
            env:
              TZ: America/Los_Angeles
              DISABLE_MQTT: "true"
              DATABASE_NAME: "teslamate"
              DATABASE_HOST: "postgres-rw.dbms.svc.cluster.local"
            resources:
              requests:
                memory: 250Mi
                cpu: 50m
              limits:
                memory: 500Mi
    service:
      app:
        ports:
          http:
            port: &port 4000
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
