---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lldap
spec:
  chartRef:
    kind: OCIRepository
    name: lldap
  interval: 30m
  dependsOn: []
  values:
    defaultPodOptions:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    controllers:
      lldap:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/lldap/lldap
              tag: v0.6.3
            env:
              - name: TZ
                value: America/Los_Angeles
              - name: LLDAP_HTTP_PORT
                value: "8080"
              - name: LLDAP_HTTP_URL
                value: https://lldap.${SECRET_DOMAIN}
              - name: LLDAP_LDAP_PORT
                value: "5389"
              - name: LLDAP_LDAP_BASE_DN
                value: dc=home,dc=arpa
              - name: LLDAP_DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: lldap-psql-app
                    key: uri
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            resources:
              requests:
                cpu: 5m
                memory: 36Mi
              limits:
                memory: 128Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
          ldap:
            enabled: true
            port: 5389
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: 8080
    persistence:
      data:
        type: emptyDir
        globalMounts:
          - path: /data
