apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
stringData:
    #ENC[AES256_GCM,data:rs3kQw==,iv:KIJ3KQxO1DPyZ974W94yswzox+2eJzyf4JntdhLZOnI=,tag:xZQKVV5jZKxsLICCQqaEdQ==,type:comment]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:8JCtgq95DVbxQKcmkYa4mieRAg+lMaa2m+qvULaubxnDBuijRracf8nz6kV3xOW5skO0su6ROI6N60CmebCfsVSzG7XjruN0B+9m57GyvmkCo8c/hA==,iv:JQq5+fh4HVvIRVqeCmz3kkZj+MSktZ4vjLZCe1fTNOA=,tag:wdkWKc5s786s0I6fh36cGA==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:aENv42Egag5biIaNnatmxxUfFKyKpu/EJ+OqFb8srOqn,iv:HdE+63NZWk3BXC6H9H1TyltaIgVqS8bp6zv5pyKqZYc=,tag:LrF7TVpCyvDS+4BGIYarzg==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:RK3Af+z0PVVhkLPK2gZx4as=,iv:vKODb8vMV2PUS9saFTDK9TeTXhBBumaOwwv88fv675M=,tag:+iA5eC6Lu0KfXBXo9iWX3w==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:U9i8tqC9W/EIyTgaEyKWOzq0KE5Q4nQuQfHUYLQS7c3GpNl7zshc5BWCW7xsZiE3TjFeKQg9u/Xy5tPZ1WLj8QI9Qi7dpKwIFdIk4slEjQvUGylOSnp1InOF27amI2PhQ/o=,iv:WQJ0p5NEQju9sS6cSlFqgU7lyAJiOTxsAnmBZIO7i6s=,tag:gyxCmoCqQs+2wWeSmoq83Q==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:2RuhsDkL17RzSs9IWdfzL+i2xCqdWoBVUeJbz7A9YhHKzNns6mw8PDosNOoD3q9Y/noCWN8zblcz+fDgKH4ZcXEmIXsVZro+Jjb7J5o99KKb2VlPFpEdbNpo4h0Z9aV3/LKshxjyi0p8xpQ=,iv:3RXfM2pS9t1UDoVyLOTpnmX8wCHpwtOwKWYiJjJk1Hs=,tag:SKhVqEWz7o5FJUo9Ytuwag==,type:str]
    #ENC[AES256_GCM,data:juYw60K2cLka9YuZS/A=,iv:P90bIQsov2URUz04STu2FhIfViu9JC/nq9LtO0prYss=,tag:FRHVkAN++1bMG0rdHOR9OA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:GUSHOHk=,iv:AnJaIZWvf1e/jgex3l83wTH1Ywjjps9bFN+P/7TfdF8=,tag:U1hJ5xTCv0gdUv7QYoN65g==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:EmxMgodyXKgPNXw8RPZ6m9WmBSzR,iv:hTSKl37mC3vhEBi693v5XgB/j2AnNXW/JKs/sFiZuhM=,tag:wJirsFeHuKwpkgRXLIbm9w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:KZsQNvg=,iv:aINr7lmHBrRfqd8PeK++yrbfNaEOGvEpeCu7Di4j2mc=,tag:plaTAXTO4YlClnW43Q4ibw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:fodIzHlGAyIMF/kDDIKX+bFnypJwFFMJxVU2TQ7YYtW9Qaw4n184UOxGvOCplX0=,iv:99cuEtkTlaRAiC/VI39ziYGBFiXk9Iin6530yeTfJ30=,tag:XQr5cLmeWKse/eR11m7G2w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:DzK1hJMAdGky5G3musE3iJeDOndUjbVEyYIR,iv:RE3t4/qKhGYJZKArVrGAiVyftfjrshxD5z4NpKwgITQ=,tag:0XvgkJG2BVTJ1BxeajSEbQ==,type:str]
    #ENC[AES256_GCM,data:Ii6O3CA=,iv:10UZsJQAAqkQRUc8ttTfUxwBxcZvJj0eLDr73GrBmHo=,tag:Mh3PL1/4y/OW4GtRPB09qg==,type:comment]
    LLDAP_SMTP_OPTIONS_SERVER: ENC[AES256_GCM,data:rIs2TeuZf7ldU1nsbp6gwCv1LZ0q5A==,iv:grAnBbiskBM3mt+ht8m/EjnOe+oWEk9kySdkEHklIyk=,tag:WHqi0IzQOR96mqD7YW70tQ==,type:str]
    LLDAP_SMTP_OPTIONS_PORT: ENC[AES256_GCM,data:2hKA,iv:1R+O/YaAl8ZRHuKB65eiQ9/c8rGS1tfazHT5halKMOw=,tag:Ssw2pfRhUeUYWs81O5oTiA==,type:str]
    LLDAP_SMTP_OPTIONS_USER: ENC[AES256_GCM,data:kDGG0rpOH9u3lZYfaH5oNEJF3MdNeMQ=,iv:sRZnRyuGEUVdTnHNhltSiwpH0YmU10VV3VHVFUyyXBM=,tag:xrqdXfXhaLy0bCYydDlsHQ==,type:str]
    LLDAP_SMTP_OPTIONS_PASSWORD: ENC[AES256_GCM,data:/Se02EaVcQhngQXHSLG2GVxNoC7RMDY=,iv:x8+Cbcvf7N8/XpYhm8rP0oh5d9KXYIL3eh46SbdH8MQ=,tag:+6Xuhwmin76NcLEP+yPDBQ==,type:str]
    LLDAP_SMTP_OPTIONS_FROM: ENC[AES256_GCM,data:pHrjiGtXwbFCXfAOYUWoA3XmitF4V4xbPf6HIFv6NsPG,iv:PsMTGkMWgM0mqMlFFaqazgzYorGNWyEjee0WxIERnVc=,tag:uASySjTYuE94jp3Zjcu7ZA==,type:str]
    LLDAP_SMTP_OPTIONS_REPLYTO: ENC[AES256_GCM,data:T+DgrFooiF6PQYOcTuHXQNpdH4Z63Pk9Y9Z7taBC9zvFjQ==,iv:X/L5hPGbpAzE56mx4mpvqCaIc5R5OKEiigSW03i/TWg=,tag:9Ydbd4rwrQ8y7WBN9ZyRbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nx9uteydh4deec6vfqqzsy89e32mj560cchyzu3fsfp33hmfeslqfml8wy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFp3N09BYTliZjdjOTBY
            T2Z4RHJiams1elcwaWdaRTJKU3ZCcTFtMTNFCmdNUS9CbnpqclgxY1FtZURCajRp
            bEhZMTJ2dmIrbjJzMTNDUk45UjFiU2MKLS0tIFI3SmZwaEhidW5FcXgreHc0UFhQ
            ZGQ5bVV4RlNmM0JadWdBd2pKSHRqNDAKSVo/Aa/7ai8XcZd0l6H01150ZKvevsUv
            t7M8pMesuXI55gCbb2wU7mzKVDdv/0cvpIKStWJneF6NKidYtbLkhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-24T22:49:08Z"
    mac: ENC[AES256_GCM,data:vEgjomT5tQ6+TIeLO6Jsp/KSxSiTgG+YvcvNlpqbfrJaAkWKD59577hF26CREfrN7BFxmQJbT0esISMqrTuyQZB8VDtsODR1G/pZotxnTYuILZvIU/Lpg68VYXU4PvMSUQzH/b+cAfH0+IobcUsPpOhD+jnUBoONTY3l5fQDVsk=,iv:dxr3GeasodVa33x6lENBwkSSd3M0XhKxLlCWIcFUzc8=,tag:E5Slfz7h7CRlmB9KCAcohA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
