---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  chartRef:
    kind: OCIRepository
    name: open-webui
  interval: 15m
  values:
    controllers:
      open-webui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: v0.11.0@sha256:72c0ba641ba75e7aa52655cb242570906ececd09b1140fb736483038a22b3228
            env:
              TZ: America/Los_Angeles
              # Open-webui settings
              WEBUI_URL: https://chat.${SECRET_DOMAIN}
              CORS_ALLOW_ORIGIN: https://chat.${SECRET_DOMAIN}
              DEFAULT_LOCALE: en
              ENABLE_OPENAI_AI: true
              OPENAI_API_BASE_URL: http://litellm:4000/v1
              ENABLE_OLLAMA_AI: true
              OLLAMA_BASE_URL: http://sys-mini-1.internal:11434
              ENABLE_WEBSOCKET_SUPPORT: "true"
              ENABLE_SIGNUP: false
              WEBSOCKET_MANAGER: "redis"
              WEBSOCKET_REDIS_URL: "redis://{{ .Release.Name }}-dragonfly:6379"
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-db-app"
                    key: uri
            resources:
              requests:
                cpu: 500m
              limits:
                memory: 2Gi
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/backend/data
      tmpfs:
        type: emptyDir
        advancedMounts:
          open-webui:
            app:
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames: ["chat.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8080
