---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-gitops
spec:
  secretName: k8s-gitops-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames: ["${SECRET_DOMAIN}", "*.${SECRET_DOMAIN}"]
