---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-gitops-tls
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    name: k8s-gitops-tls
    template:
      engineVersion: v2
      data:
        tls.crt: '{{ .tls.crt | b64enc }}'
        tls.key: '{{ .tls.key | b64enc }}'

  dataFrom:
  - extract:
      key: /k8s-gitops-tls
