---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: k8s-gitops-tls
spec:
  secretStoreRefs:
    - name: akeyless
      kind: ClusterSecretStore
  selector:
    secret:
      name: k8s-gitops-tls
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: k8s-gitops-tls
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: k8s-gitops-tls
          property: *key
